### PR TITLE
Add Density ≤ aleph0 alias to P26 Separable to parallel P209

### PR DESCRIPTION
**Pull request by danflapjax**

### CODE REVIEW

**Comment by prabau** [comment]
The new alias is just a restatement of the definition.  It does parallel P209 (density less than continuum), but P209 had to be phrased that way because there is no consecrated word for the concept.

So I am wondering if this alias here is really necessary.  How is it going to help?

Would be good to get input from more people here.

@StevenClontz

**Comment by StevenClontz** [comment]
I'm inclined to improve. If a user wants to know about density, they can write "density" in their Explore page formula and choose from all the properties related to density that we know about.

**Comment by GeoffreySangston** [comment]
What about separable and P209 linking to each other in their descriptions with a 'Compare with' line?

Also, I noticed P209 doesn't have any references. It appears on page 11 of *Encyclopedia of General topology*, page 25 of *Engelking's General Topology*, and Google Scholar has a lot of hits for [Cardinal Functions in Topology](https://scholar.google.com/scholar?start=0&q=Cardinal+Functions+in+Topology&hl=en&as_sdt=0,21).

**Comment by StevenClontz** [comment]
> What about separable and P209 linking to each other in their descriptions with a 'Compare with' line?
> 
> Also, I noticed P209 doesn't have any references. It appears on page 11 of _Encyclopedia of General topology_, page 25 of _Engelking's General Topology_, and Google Scholar has a lot of hits for [Cardinal Functions in Topology](https://scholar.google.com/scholar?start=0&q=Cardinal+Functions+in+Topology&hl=en&as_sdt=0,21).

All sounds reasonable, but they could be proposed in a separate PR perhaps.

**Comment by prabau** [comment]
Regarding P209, the only thing that could be explained/referenced is the notion of "density".  But the property itself, i.e., the fact that the density has some upper bound, does not really require a reference to explain the meaning.

**Comment by GeoffreySangston** [comment]
@prabau I'm referring to the concept of 'density'.

(Though it's possible someone has written on this specific property, I had 'density' in mind.)

**Comment by StevenClontz** [comment]
@prabau are you satisfied with the rationale for adding this alias?

**Comment by prabau** [comment]
Yes, I think it's fine.

Apart from that, @GeoffreySangston made a good point.  If we are going to mention density (even as an alias), shouldn't the post mention what is meant by "density"?

**Review by StevenClontz — APPROVED** [review]
I'd be in favor of adding references for defining "density", but I don't think they are necessary to merge in this contribution.

**Pull request merged**
