### PR TITLE
provide example of t2 and anti-t2 space

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
See also https://twitter.com/StevenXClontz/status/1588284193699958784 🤣

**Comment by prabau** [comment]
I have been wanting to get rid of the anti-Hausdorff property (https://topology.pi-base.org/properties/P000101) for a long time, as it's identical to Hyperconnected (https://topology.pi-base.org/properties/P000039).

Suggest to replace P101 with P39 in the PR, and also add the same for the empty space (S163).

And separately, you may not prefer that, but I would just get rid of P101 entirely, under the assumption that pi-base is continually evolving towards a more coherent and informative state. My 2 cents :-)

**Comment by prabau** [comment]
Also, an observation (not directly relevant to this PR).  The terminology "anti-Hausdorff" is taken from the article of van Douwen referenced in (P101) (he does not quite define it, but the reader can infer it means the same as hyperconnected).  

This is independent of the terminology "anti-Hausdorff" in the sense of Bankston (https://doi.org/10.1215/ijm/1256048236 = the article that also defined anticompact, etc).  Since there are spaces with two elements that are not T_2 and any space with 0 or 1 element is T_2, the Bankston-anti-Hausdorff spaces would be the ones where the topology is totally ordered, i.e., for any two open sets, one of them is contained in the other.  And there are plenty of hyperconnected spaces that don't satisfy that.

**Comment by StevenClontz** [comment]
Will think about this more carefully later, but I think fleshing out the conventions for our canonical adjectives/prefixes (e.g. "locally") to be standard across pi-Base is worthwhile. So using how published article defines "anti" properties seems like the reasonable way to go.

**Comment by prabau** [comment]
I think the following would take care of it: add a theorem: Indiscrete implies hyperconnected.

That would provide the hyperconnected property (and the connected property) for the Singleton and the Empty space in one shot, as well as any other indiscrete space.

**Comment by StevenClontz** [comment]
I'm convinced about removing P101 - it was never used manually, and just utilized a theorem which is equivalent to T262 for hyperconnected.

**Review by prabau — APPROVED** [review]

**Pull request merged**
