### PR TITLE
Strengthen T170, T452

### PR DESCRIPTION
**Pull request by yhx-12243**
From $T_2 \wedge \mathrm{Paracompact} \implies \mathrm{Fully} T_4$ we can directly know $R_1 \wedge \mathrm{Paracompact} \implies \mathrm{Fully} \mathrm{normal}$, and the original theorem can be automatically deduced by the new one. However, the strengthen one can't be deduced by the original one in current pi-base system.

### CODE REVIEW

**Comment by yhx-12243** [comment]
Also [Regular](https://topology.pi-base.org/properties/P000011) implies [$R_1$](https://topology.pi-base.org/properties/P000134), [T452](https://topology.pi-base.org/theorems/T000452) can be dropped.

**Comment by prabau** [comment]
I can see how
- (T170) T2 + paracompact ==> fully T4
- (T452) regular + paracompact ==> fully normal

could be combined into a single theorem [R1 + paracompact ==> fully normal].

But T453 [normal + paracompact ==> fully normal] cannot be derived just from that, as far as I can tell.  In general, there are normal paracompact spaces that are not R1.

**Comment by yhx-12243** [comment]
> I can see how
> 
> * (T170) T2 + paracompact ==> fully T4
> * (T452) regular + paracompact ==> fully normal
> 
> could be combined into a single theorem [R1 + paracompact ==> fully normal].
> 
> But T453 [normal + paracompact ==> fully normal] cannot be derived just from that, as far as I can tell. In general, there are normal paracompact spaces that are not R1.

Yes you're right, T453 should be recovered.

**Review by StevenClontz — APPROVED** [review]
Part of me feels like T170 is now a bit heavy, and could have been just R1+paracompact=>regular, and by keeping T452 we'd get fully normal.

However, I always prefer to err on the side of whatever completes pi-Base, and this answers the search https://topology.pi-base.org/spaces?q=R1%2Bparacompact%2B%7ERegular as-is, so I'm approving.

**Comment by StevenClontz** [comment]
Thank you @yhx-12243 for your recent contributions! You've been invited to help maintain pi-base/data, so in the future you can make branches directly on this repository, which can be previewed by everyone on the live website via https://topology.pi-base.org/dev

**Comment by prabau** [comment]
@StevenClontz I agree that it is a little "heavy".  In any case, I was planning more comments here before you approved.  I think the current justification for T170 is too verbose and unclear.  What should I do?

**Comment by StevenClontz** [comment]
Sorry @prabau! In the future we should be better about self-requesting reviews in this situation, so folks know when someone is preparing a review.

If you think changes are critical, please create an issue with your concerns. Otherwise you can leave the feedback here and @yhx-12243 can consider a follow-up PR to make the suggested changes.

**Comment by prabau** [comment]
Ok.  Nothing critical.  I may end up doing another PR which you guys can review.

**Comment by prabau** [comment]
@StevenClontz How does one self-request a review?

**Comment by StevenClontz** [comment]
image

**Pull request merged**
