### PR TITLE
Results on compactly generated spaces

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
I have wondered: does pi-base have "compactly generated"/"k-space' as a property?  I could not see it.

**Comment by StevenClontz** [comment]
I don't think so. That's part of my plan here.

**Comment by prabau** [comment]
I added something to my response to https://math.stackexchange.com/questions/4585825.  The reference there could be relevant to this topic.

**Comment by StevenClontz** [comment]
More can be done but I didn't want this to get any staler. Worth considering if proposed T322 can be improved from T1+1st countable to sequential (n.b. I haven't thought hard about this).

**Comment by prabau** [comment]
In the definition for P98, need to add that the union of all the $K_n$ is all of $X$.

**Comment by prabau** [comment]
We can also add the theorem: komega + anticompact + T1 ==> discrete (shown in my answer in the same https://math.stackexchange.com/questions/4585825).

This is particularly useful in its contrapositive form to show that something is not komega (in particular Arens-Fort space and Appert space). Gives examples of hemicompact spaces that are not komega.

**Comment by prabau** [comment]
I see that (Alexandrov + $\sigma$-compact ==> $k_\omega$) is already a consequence via "exhaustible by compacts", so nothing to add here.

But this seems it can be added: $k_\omega$ ==> k-space.

**Comment by StevenClontz** [comment]
> But it seems this can be added: 

I posed the question here as a quick proof eludes me: https://math.stackexchange.com/questions/4633318/is-every-k-omega-space-a-k-space

In doing so I realized that we need to take more care in these definitions: specifying closed or subspace-closed isn't important in KC (compacts are closed, such as T_2) spaces, but we should decide which one we want to track. (Probably subspace-closed.)

**Comment by StevenClontz** [comment]
If the current PR appears valid as-is, I'd like to merge and enhance it in a follow-up PR.

**Comment by prabau** [comment]
I made a minor tweak: changed the order of the properties in T322 and T323
so that it looks better in the list of theorems in https://topology.pi-base.org/properties/P000098.

Also replaced my mathse username with a link to the particular answer.

The implication $k_\omega$ ==> k-space may be more subtle than I thought.  Will take a closer look.  Approving in the mean time.

**Review by prabau — APPROVED** [review]

**Pull request merged**
