### PR TITLE
improve regular to t3

### PR DESCRIPTION
**Pull request by StevenClontz**
Add T3 (and therefore T0) to S77.

### CODE REVIEW

**Comment by prabau** [comment]
Or something slightly stronger:  S77 is the product of S63 and S28. (We could add links to those in the README for S77).  Then add T5 to S63 (that's items 1 and 2 in counterexample 63 of S&S).  That would deduce T3.5 for S63.  And finally, add a new trait to S77 claiming T3.5 because each of the factors have it.

**Comment by StevenClontz** [comment]
Before merging - S63 is not perfectly normal according to https://dantopology.wordpress.com/2012/10/28/michael-line-basics/ so this should be added. Trying to find a mathse reference or may create one.

**Comment by StevenClontz** [comment]
It's also paracompact

**Comment by prabau** [comment]
Yeah, would be good to add those.  Adding that S63 not a $G_\delta$ space (P132) is maybe better that adding it's not perfectly normal (it's equivalent for normal spaces), as danma shows that $\mathbb Q$ is not a $G_delta$.  Looking for ref too.

**Comment by prabau** [comment]
sorry, have to step out for an hour.

**Review by prabau — APPROVED** [review]

**Pull request merged**
