### PR TITLE
Use citation cff

### PR DESCRIPTION
**Pull request by rschwiebert**
This takes advantage of the inbuilt citation feature for github.

### CODE REVIEW

**Comment by prabau** [comment]
@rschwiebert Thanks for fixing the line endings for T326, T327.  I kept having problems with these two files suddenly showing up as modified when creating a new branch.  Just curious, how did you detect that was the problem?

**Comment by rschwiebert** [comment]
> @rschwiebert Thanks for fixing the line endings for T326, T327. I kept having problems with these two files suddenly showing up as modified when creating a new branch. Just curious, how did you detect that was the problem?

Hi @prabau :
Git is automatically rectifying the line endings because of the .gitattributes setting on the repository. I did not have to take any action beyond adding and committing the changes that were presented, since they seemed valid according to the repo's settings.

Is it still an issue for you if you check out my branch locally?

**Comment by prabau** [comment]
> Is it still an issue for you if you check out my branch locally?

I did not check, but I am sure it will be fine.  More interesting would be to figure out how this line ending mismatches happened in the first place.  @StevenClontz, it seems the two files T326, T327 were added in #244.

**Comment by rschwiebert** [comment]
In case it's not obvious what the effect of this file is, I'm attaching a screenshot:
Screen Shot 2023-03-21 at 11 20 15 PM

I'm definitely wondering who you would like to put for the authors. I figured Austin was a safe bet but of course probably more are deserving.  I also see for some reason I put literally π there in one spot but maybe `pi` is actually more canonical :)

**Comment by StevenClontz** [comment]
> > it seems the two files T326, T327 were added in #244.
> 
> Perhaps the author of the branch had .gitattributes modified locally so that the wrong line endings could be committed, and then snuck in in the merge? Probably not important... looks like it sorts itself out.

Well we can go back to the video to find out, fortunately! (-:

https://www.youtube.com/watch?v=TKxN8xxz0VY&t

**Comment by StevenClontz** [comment]
Austin hasn't been active in the project for many years. Since Buzzard cited James and myself in https://arxiv.org/pdf/2112.11598.pdf I took that lead.

As a whole this works, but this is a blunt instrument. I'd love to have individual contributions be citable, e.g. if you visit https://topology.pi-base.org/theorems/T000332 you'd get a citation that makes it clear that @ccaruvana contributed it. (Then again, maybe one of the answers from https://math.stackexchange.com/questions/103774/every-manifold-is-locally-compact is more appropriate?)

**Review by StevenClontz — APPROVED** [review]

**Pull request merged**
