### PR TITLE
introduce realcompact and basic theorems

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
I think this is ready and makes progress on #332. It'd be nice to have a counterexample for the converse of https://topology.pi-base.org/theorems/T000384 but I'd delay that to a future contribution.

**Comment by StevenClontz** [comment]
Actually there's a pretty direct example, asserted at https://math.stackexchange.com/questions/4731883/

**Comment by prabau** [comment]
- P162: the name of the property used in the literature is "realcompact".  Everybody who knows or cares about the property uses that name.  So I think that should be the main name, not an alias.  (It's also shorter, easier to parse in lists of theorems.)

- As for "Closed subset of Euclidean space", that seems misleading.  As far as I know, Euclidean space always refers to some $\mathbb R^n$ with a finite $n$.  So would recommend to drop that, even as an alias.

- P162 README: It would be good to add some equivalent more intrinsic definition, of which there are several, usually in terms of the Stone-Cech compactification.  I am not familiar enough with them to make a recommendation here.  This could be added later in a separate PR.

- S3 is P162:  The same argument shows more generally that any discrete space is realcompact (embed D into $\\{0,1\\}^D$ (itself a closed subspace of $\mathbb R^D$) by sending $x\in D$ to its characteristic function.  So turning this into a theorem instead would be more general.

**Comment by Moniker1998** [comment]
Not all discrete spaces are realcompact. If there were a proof of that, you'd prove that it's inconsistent that measurable cardinals exist, which is highly unlikely.

**Comment by StevenClontz** [comment]
Thanks @Moniker1998, I'm reverting this to a draft until this is addressed.

**Comment by Moniker1998** [comment]
> P162 README: It would be good to add some equivalent more intrinsic definition, of which there are several, usually in terms of the Stone-Cech compactification. I am not familiar enough with them to make a recommendation here. This could be added later in a separate PR.

One definition using Stone-Cech compactification is by first defining the Hewitt realcompactification of $X$, If $X\subseteq \beta X$, consider the largest subspace of $\beta X$ in which $X$ is $C$-embedded. This is Hewitt realcompactification $\upsilon X$ of $X$. If $\upsilon X = X$ we say that $X$ is realcompact. Alternatively you can define $\upsilon X$ as set of those $x\in X$ such that if we consider any $f\in C(X)$ and $f^*:\beta X\to \mathbb{R}^*$, the map into extended reals, then $f(x)\in\mathbb{R}$.

There's also a definition using $z$-ultrafilters that I mentioned before. A space $X$ is realcompact iff every real z-ultrafilter $\mathcal{U}$ on $X$ is fixed i.e. we can find $x\in X$ such that $\mathcal{U} = \{Z\in Z(X) : x\in Z\}$. Here $Z(X)$ are zero sets of $X$.

**Comment by prabau** [comment]
@Moniker1998 So the characterization you used for the Mysior plane is the one in terms of z-ultrafilters then.

**Comment by Moniker1998** [comment]
Yes, I used that definition to prove Mysior plane is not realcompact. It seems to be the most topological and direct, and seems to be the best tool in dealing with proving that something is realcompact when all other methods and theorems fail.

**Comment by Moniker1998** [comment]
So as a summary, T000387 is false and unless we add the property of having non-measurable cardinality (which I don't see why anyone would do that), it's not fixable. 
S000003 is realcompact, but not for the reasons given in the file
All regular Lindelof spaces are realcompact, and all pseudocompact spaces are realcompact iff they are compact.
Those properties should be deduced from other theorems, so the only concerning spaces for which property is yet to be determined should be those Tychonoff spaces that are not pseudocompact and not Lindelof, and I will only discuss those below:
Theorem 15.25 in Gillman and Jerison "Rings of continuous functions" states that any metric space of non-measurable cardinal is realcompact. Thus S000003, S000133, S000134 are realcompact.
This leaves us with six spaces S000057, S000074, S000091, S000107, S000135, S000137.
Corollary 8.18 in Gillman and Jerison tells us that since the identity map from S000107 to $\mathbb{R}^\omega$ with product topology, and $\mathbb{R}^\omega$ is hereditarily realcompact, it follows that S000107 is hereditarily realcompact. The same corollary applied to map from S000057 to $\mathbb{R}$ tells us that S000057 is hereditarily realcompact. Also the map from S000074 to closed half-plane $\{(x, y) : y\geq 0\}$ is continuous so S000074 is hereditarily realcompact. The identity map from S000135 to S000134 is continuous, so S000135 is hereditarily realcompact.
For S000091, I think I have a proof that it's not realcompact.

**Comment by Moniker1998** [comment]
- In this paper, https://doi.org/10.4153/CJM-1972-081-9 corollary 2 states that if $X$ is any normal metacompact $T_1$-space with the property that all discrete subspaces are realcompact (i.e. of non-measurable size), then $X$ is realcompact. In particular a normal metacompact $T_1$-space $X$ of non-measurable size is realcompact.
- S000137 is a normal metacompact $T_1$-space of size $|Y| \leq |X| = 2^{2^\mathfrak{c}}}$. Since $2^{2^{\mathfrak{c}}}$ is non-measurable, S000137 is realcompact

**Comment by Moniker1998** [comment]
I'm new to github and how it all works, so let me know if I'm writing in a wrong place.

**Comment by StevenClontz** [comment]
Sorry for letting this slide. I'm going to try to fix up the PR now but if time runs out I'll take a stab next week.

**Comment by StevenClontz** [comment]
Okay let's try this again @prabau.

Thanks for the notes @Moniker1998 - I haven't done much with large cardinals in my work, but I'm hoping I'm right in understanding that the reals have non-measurable cardinality in ZFC, so we have theorems to get all metrizable spaces of cardinality $|\mathbb R|$ or less listed as realcompact.

I don't like to make huge pull requests, so I did not implement all your notes. I encourage you to move what I didn't address to an appropriate Issue or Discussion. You're also welcome to join us at the next community meeting https://github.com/orgs/pi-base/discussions/334 and we can find a time for someone to sync up with you to walk through how to make a pull request yourself if you like.

**Comment by Moniker1998** [comment]
I only have few comments on your additions.

T000387 and T000387 could be one theorem by using P000059 which already exists in pi-base

Additionally it could be strengthened by:

> * In this paper, https://doi.org/10.4153/CJM-1972-081-9 corollary 2 states that if X is any normal metacompact T1-space with the property that all discrete subspaces are realcompact (i.e. of non-measurable size), then X is realcompact. In particular a normal metacompact T1-space X of non-measurable size is realcompact.

i.e. T_4 + metacompact + smaller than or equal continuum => realcompact

It would be good to replace those two theorems with this one.

As for measurable cardinals, if $\exp^n(\kappa) := \exp(\exp^{n-1}(\kappa))$ and $\lambda\leq \exp^n(\aleph_0)$ for some $n$, then $\lambda$ is non-measurable. Here $\exp(\kappa) = 2^\kappa$ so that $\exp^n$ is iterated exponentiation of cardinals. Reference could be found in "Rings of continuous functions" by Gillman and Jerison, though it could probably be also found in some set theory texts. Measurable cardinals are unimaginably huge.

**Comment by StevenClontz** [comment]
So I think "non-measurable cardinality" might be worthwhile to add as a property. As a ZFC database, no space in the pi-Base will ever be marked as "not non-measurable cardinality". But we could have P59 imply this property, and then we could use this property with your suggested theorem, mostly for future-proofing (e.g. if we add "Cardinality $=\aleph_7$", we could mark it as non-measurable with a theorem).

**Comment by StevenClontz** [comment]
At this point I'm waiting to merge in #350 before this.

**Comment by prabau** [comment]
> So I think "non-measurable cardinality" might be worthwhile to add as a property. As a ZFC database, no space in the pi-Base will ever be marked as "not non-measurable cardinality". But we could have P59 imply this property, and then we could use this property with your suggested theorem, mostly for future-proofing (e.g. if we add "Cardinality =ℵ7", we could mark it as non-measurable with a theorem).

I agree wholeheartedly.  That was going to be my first comment.

**Comment by StevenClontz** [comment]
Okay maybe now this is really, really ready. @prabau

**Comment by StevenClontz** [comment]
ah nuts let me add the other realcompact characterization

**Comment by prabau** [comment]
P164 (non-measurable cardinality): I don't think "Certain Subsets of Products of metacompact ..." should be a reference for this.  How about replacing it with mention of Gillman & Jerison, ch. 12, which explains the notion of measurable cardinality very clearly.

T383: "inaccessible" means strongly inaccessible in this case, right?  Could be good to spell it out.  I don't see measurable cardinals mentioned in the wikipedia article about Inaccessible cardinal.  On this other hand, inaccessible is mentioned in the wikipedia article about Measurable cardinal, so that might be a better reference.  Also Gillman & Jerison section 12.6 says: "Theorem 12.5 states that the smallest measurable cardinal (if any exist) is strongly inaccessible."  That could be another ref.
https://babel.hathitrust.org/cgi/pt?id=uc1.b4407145&view=1up&seq=179

**Comment by StevenClontz** [comment]
Sounds good. Feel free to incorporate those and merge if you get to it before I do.

**Comment by prabau** [comment]
> Sounds good. Feel free to incorporate those and merge if you get to it before I do.

Sure, I'll do that.  I may also have a few more substantial comments, still taking a look.

**Comment by prabau** [comment]
My last comment was about T382 (T4 + metacompact + nonmeasurable card ==> realcompact), which I had some reservations about.  The justification given is a paper of Zenor, which I have not read, but seems difficult and also using results involving notions not in pi-base, and make use of results referenced in other papers.  All fine for a research article, but maybe not exactly the best for a reference in pi-base?  I tried to find a more self-contained account of this, but in particular could not find the result even mentioned in the realcompact chapter of Encyclopedia of Gen Topology (Hart, Nagata, Vaughan) or in Engelking.
On the other hand, there are more basic results about realcompact spaces that are not even in pi-base.

Also, the first sentence of the Zenor paper refers to the more basic result that in discrete spaces realcompactness is equivalent to nonmeasurable cardinality.  That is also proved in Gillman & Jerison and Engelking.  One half of this: [discrete + realcompact ==> nonmeasurable] cannot currently be deduced in pi-base and would seem to be worth having.  The other half [discrete + nonmeasurable ==> realcompact] is not there, but deducible from the proposed T382, assuming we want T382.

Maybe I am mistaken about this, but I would find it worthwhile, if only just for myself, to have a brief discussion in the meeting tomorrow about how to approach a result like T382.

**Comment by Moniker1998** [comment]
It'd be hard to find something like this in Engelking when it's an article from 2018, I think. It's very new research.

We could stick to result for metrizable spaces instead, being well-established, if using such a new result bothers you, and switch to this one when someone carefully checks its validity.

**Comment by StevenClontz** [comment]
I think https://www.cambridge.org/core/services/aop-cambridge-core/content/view/CF5EC3B7193934ABD4F84FD8C8504467/S0008414X00037986a.pdf/certain_subsets_of_products_of_metacompact_spaces_and_subparacompact_spaces_are_realcompact.pdf is pretty clear? Cor 2 says T4 metacompact spaces with (*) are realcompact, and according to the introduction (*) is equivalent to discrete subspaces having non-measurable cardinality. Phil taught me topology as an undergrad so I'm willing to trust him on this. ;-)

**Comment by prabau** [comment]
Ok, sounds good.  I'll approve a little it later.  Need to be off my computer right now.

**Comment by prabau** [comment]
> As for [discrete + realcompact => non-measurable], it certainly wouldn't hurt to have, but it probably wouldn't serve much of a purpose other than being a theorem on pi-base.

I agree it wouldn't be used to determine any traits of any sample spaces.  Still, seems it would be good to have for the record.

**Review by prabau — APPROVED** [review]

**Comment by StevenClontz** [comment]
Thanks @Moniker1998 for pushing this forward! Please feel free to contribute more PRs fleshing out realcompact results in the pi-Base now that we've got some scaffolding for them.

**Pull request merged**
