### PR TITLE
Properties of countability [local mirror of PR374]

### PR DESCRIPTION
**Pull request by StevenClontz**
Extension of #374 for preview on topology.pi-base.org

### CODE REVIEW

**Comment by StevenClontz** [comment]
@Moniker1998's original notes from #374

> I've replaced [separable => weakly Lindelof] by the sharper [CCC => weakly Lindelof] (since [separable => CCC]).
> 
> I've also added [metrizable + weakly Lindelof => second-countable].
> 
> Perhaps [separable + metrizable => second-countable] should be deleted since it's already implied by [metrizable + weakly Lindelof => second-countable]?
> 
> @StevenClontz tell me what you think about deletion of that theorem.
> 
> Another thing is that we might want to give a more explicit proof instead of citing a theorem like I did

**Comment by Moniker1998** [comment]
Thank you for fixing this pull request!

**Comment by StevenClontz** [comment]
No problem! I was in the middle of writing my review but got caught in meetings and other work. Will follow up ASAP.

**Comment by prabau** [comment]
For T34, I have asked https://math.stackexchange.com/questions/4743591/weakly-lindelof-metrizable-spaces-are-separable, as it seems the Handbook does not have a full proof of it.

**Comment by StevenClontz** [comment]
See also https://math.stackexchange.com/questions/4743458/is-every-weakly-lindel%c3%b6f-space-ccc as the direct proof isn't bad and I thought it should be used here.

**Comment by prabau** [comment]
> See also https://math.stackexchange.com/questions/4743458/is-every-weakly-lindel%c3%b6f-space-ccc as the direct proof isn't bad and I thought it should be used here.

Yeah, that looks fine, except that the title in the mathse post is backwards?  We can mention both the Handbook and this in the refs.

**Comment by StevenClontz** [comment]
> except that the title in the mathse post is backwards

whoop, fixed now thanks

**Comment by prabau** [comment]
> For T34, I have asked https://math.stackexchange.com/questions/4743591/weakly-lindelof-metrizable-spaces-are-separable, as it seems the Handbook does not have a full proof of it. Feel free to provide one, or someone will.

Hmm, I just read the standard proof of Willard (Thm 16.11) that in metric spaces Lindelof implies second countable.  It seems that pretty much the same argument works with "weakly Lindelof".  So it's pretty straightforward.

**Comment by prabau** [comment]
I have added the mathse refs.

**Comment by prabau** [comment]
@Moniker1998 was wondering if some of the existing theorems should be removed as a result.  I'll take a look.

**Comment by Moniker1998** [comment]
Yes, one of the theorems, namely [separable => second-countable].

**Comment by prabau** [comment]
It seems we can eliminate two theorems if we want to:
- T61: separable + metrizable ==> second-countable
- T62: Lindelof + metrizable ==> second-countable

The nice thing about the new T34 [weakly Lindelof + metrizable ==> second countable] is that is allow to complete the circle of equivalences between the various related properties (second countable, separable, Lindelof, CCC, weakly Lindelof) in the case of metrizable spaces, by starting with weakly Lindelof, which is the weakest of the properties.  Before we could not even deduce [CCC + metrizable ==> separable] for example, and now we can.

In this particular case, I think it would make the circle of implications easier to organize and would not noticeably increase the complexity of deductions in general.  So I would be in favor of removing T61 and T62.  (Or course we would have to check references from mo/mathse as we discussed in our previous meeting.)  Could be done in a separate PR.

What do you guys think?

**Comment by prabau** [comment]
@ccaruvana fyi

**Comment by StevenClontz** [comment]
I'd edit T62 from Lindelof to weakly Lindelof rather than create a new theorem, but otherwise I was thinking the same thing.

**Comment by prabau** [comment]
> I'd edit T62 from Lindelof to weakly Lindelof rather than create a new theorem, but otherwise I was thinking the same thing.

Good call.  We should do that.

**Comment by prabau** [comment]
Move T34 to T62 and removed T61 as discussed (after changing https://math.stackexchange.com/questions/4727903/is-every-second-countable-space-k-lindel%c3%b6f, which was the only reference to it from mathse/mo).

**Comment by StevenClontz** [comment]
Looks good to me. Since I "created" this PR, I cannot approve it, so @prabau can approve and merge. Thanks @Moniker1998 for the contribution!

**Review by prabau — APPROVED** [review]

**Pull request merged**
