### PR TITLE
remove S25|P65 (reals are size continuum) as redundant

### PR DESCRIPTION
**Pull request by StevenClontz**
New pi-Base feature: https://topology.pi-base.org/spaces/S000025/properties/P000065 shows why this assertion is redundant with the others.

(note to self: should refactor that feature so it appears more like the list on a deduced trait)

### CODE REVIEW

**Comment by yhx-12243** [comment]
One question about redundancy is that, should we remove ALL the redundancy, or just like something T106 that, we would keep some redundancy for simplicity? What do you think @StevenClontz

**Comment by StevenClontz** [comment]
I'm open to discussion; we've decided we're okay with redundant theorems, should we preserve certain traits as well?

**Comment by prabau** [comment]
In this case, it does not seem to be a good idea to me to remove the fact that the cardinality of $\mathbb R$ is the continuum.
It's a basic result that does not need any topology, and it would be replaced by a chain of theorems, some of which are nothing obvious.

But often when we see something like this, it can go both ways between groups of properties.  Namely, we can ask:

Can we keep this trait and instead remove some of the other traits that could be derived from P65 in combination with some of the other traits?

**Comment by prabau** [comment]
I guess if we can't find anything to replaced it with, I would not object to removing P65.

**Comment by GeoffreySangston** [comment]
> In this case, it does not seem to be a good idea to me to remove the fact that the cardinality of R is the continuum. It's a basic result that does not need any topology, and it would be replaced by a chain of theorems, some of which are nothing obvious.

Since it's the definition of [Cardinality = c](https://topology.pi-base.org/properties/P000065), I vote to keep the 'By definition' trait file. It's nice that the trait file also displays a derivation from the other traits, though.

**Comment by StevenClontz** [comment]
I do think I want to tweak the UI so it doesn't appear to be a warning, but instead just a "heads up". I think it will be particularly useful during the review of new PRs.

**Comment by prabau** [comment]
Another parallel thought.  Would there be a benefit in hiding that warning by default, and have a button somewhere near the bottom of the screen somehow to show this derivation if it exists? That way, ordinary users who don't care about redundancy of traits would no be bothered by that.

Or maybe we could have a very subtle indication, like the button at the bottom would be in a different color, or even better, the button would only appear if the trait is redundant, and then a reviewer click on that to check it.

**Comment by StevenClontz** [comment]
Yeah, having it pop-out like our Markdown button makes sense.

**Comment by prabau** [comment]
> (Edit: I might try to brush up on my git skills a bit to look through the graveyard of deleted traits to see if any might be worth reviving, if that seems like a worthwhile thing to do.)

Nobody will stop you, but I am not sure we want to spend time reviving deleted traits at this point.  It can happen organically as people do changes to a particular space and notice something about their favorite trait.

**Comment by StevenClontz** [comment]
I couldn't find any other asserted property I could weaken to require cardinality, but I think I agree it seems silly to remove such an easily seen property, so I'm closing this and leaving the redundancy.

**Pull request closed without merging**
