### PR TITLE
k-Hausdorff

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
We have to find out if this matches the more commonly used definition of "k-Hausdorff".

This is related to compactly generated spaces.  At one point, I rewrote a big part of https://en.wikipedia.org/wiki/Compactly_generated_space to make clear the distinction of between the CG1, CG2, CG3 of pi-base.

k-Hausdorff is mentioned in Rezk, section 4 (see link in the References section of the wikipedia article:
"a space $X$ is k-Hausdorff if the diagonal in $X\times X$ is k-closed."  Rezk uses k-closed in the sense of CG2, as far as I can tell.  Rezk's main claim is that k-Hausdorff is easier to work with than weak Hausdorff, and CGWH (= CG2 + weak Hausdorff) is the same as CG2 + k-Hausdorff, as far as I can tell.  See section 11.  In particular, (11.2) weak Hausdorff implies k-Hausdorff.

But this last statement seems to contradict T424: k-Hausdorff ==> KC, as it would imply that KC, weak Hausdorff, k-Hausdorff are all the same, which is not the case.

That wiki article also mentions k-Hausdorff in the k-ification, which the only section I have not cleaned up.  Everything about k-Hausdorff in there should be taken with a grain of salt, because it's unsourced, and the person who wrote that part had introduced so many erroneous statements in the rest of the article that had to be weeded out.  I asked him in the Talk page, but he never responded.

There is also https://en.wikipedia.org/wiki/Weak_Hausdorff_space, which has a full section on k-Hausdorff.  That would have to be checked out and maybe something cleaned up at some point.  (Among other things, it's fuzzy about the notion of k-closed: CG1 or CG2?  Seems to be using CG1, following Lawson & Madison.  This should really be checked.

Maybe the discrepancies are due to the existence of two different notions of "k-Hausdorff": CG1-k-Hausdorff and CG2-k-Hausdorff?  Or something else.

In any case, need to check carefully all assumptions (where compact follows the French convention or not, etc)

**Comment by prabau** [comment]
I did not have the time to write an answer today, but I hope to do it tomorrow.

**Comment by StevenClontz** [comment]
I've added a few more results on the weaker $k$-Hausdorff.

My pitch: merge this for now, but we should follow up with the weaker $k$-Hausdroff in a future PR.

One thing to consider: should bigger numbers always mean stronger properties in pi-Base? This matches $T_n$ properites, but other properties from the literature, e.g. Arhangelskii $\alpha_i$ properties, are pointed the opposite direction. But given that we're strictly between $T_2$ and $T_1$, perhaps a numbering scheme that matches big->small makes sense.

**Comment by prabau** [comment]
We got a pretty nice chain of implications now from the mathse post.

**Comment by StevenClontz** [comment]
Yeah it's quite nice how it all worked out:

$T_2\Rightarrow k_1H\Rightarrow KC\Rightarrow wH\Rightarrow k_2H\Rightarrow US\Rightarrow T_1$

I'm working this all into my preprint (which I hope to share with the pi-Base community soon), and will make 1-2 more PRs updating pi-Base to match.

**Comment by prabau** [comment]
I am ok with releasing just this version of k-Hausdorff for now.  But I think P170 should first be phrased with the usual definition in terms of the diagonal being k-closed in $X\times X$.  And then mention the equivalence with the other formulations.
Do you mind if I try to add a sentence about that?

Later on, if we introduce the other variant of k-Hausdorff, we can tweak as necessary.  I can't really think of good names to distinguish them at the moment.  $k_1$-Hausdorff, $k_2$-Hausdorff, is nice in the sense that it indicates some sort of progression, and the numbers 1, 2 match the corresponding progression for compactly generated spaces CG1, CG2, ... But not fully enlightening either.

I think the most important thing in numbering similar properties is to follow some kind of logical progression, usually from easier to more complex.  That usually corresponds to getting stronger properties.  But in this case, the $k_i$-Hausdorff are dual to the CGi properties in a way; as CGi gets stronger, $k_i$-Hausdorff gets weaker.  This logic seems to make sense to me.

**Comment by prabau** [comment]
btw, what reference would you recommend for  Arhangelskii $\alpha_i$ properties?  I am not well-versed in those.

**Comment by StevenClontz** [comment]
Trailhead for arhangelskii stuff (classic definition uses convergent sequences): https://arxiv.org/abs/1911.02627

Feel free to add the usual definition to kH

**Comment by prabau** [comment]
Please take a look.

For T424, it follows from the equivalence in Theorem 2.1 mentioned in P170.  But we could keep T424 the way it is and remove the third characterization from P170.  What do you think?

**Comment by StevenClontz** [comment]
P170 edit looks good.

I think 06d5267 addresses the point you made with T424.

**Review by prabau — APPROVED** [review]

**Pull request merged**
