### PR TITLE
Long spaces (S38, S39, S40, S153 S196) cut point properties / removing homogeneous traits / trait cleanup

### PR DESCRIPTION
**Pull request by GeoffreySangston**
(Don't be intimidated by the number of commits. There's a lot simply because I hadn't yet learned of danflapjax's tool for listing redundant traits and wanted to stay organized. There's really nothing to this PR.)

The removed 'Homogeneous P86' traits already referenced cut point properties, so it makes sense to change those to the actual cut point traits.

(Let's just move this to a follow-up since this PR looks bigger than it really is.) I haven't asserted ~Has a cut point for [Long circle S196](https://topology.pi-base.org/spaces/S000196) yet since I didn't know how much detail to include. Essentially, the complement of the identified point is the open long ray, hence connected, and the complement of any other point is homeomorphic to the closed long ray minus its first endpoint glued to $[0, 1)$, hence also connected.

### CODE REVIEW

**Comment by Moniker1998** [comment]
I am looking at S38 and I don't see why homogeneous was removed. Are you planning to add more properties to S38?

**Comment by Moniker1998** [comment]
So far everything looks good.

**Comment by prabau** [comment]
@GeoffreySangston Sorry about my rant here, but I hope this will not snowball into a monster PR, like we've had a few in the past that take forever to review and get merged.  It's always better to split into several more manageable pieces if necessary. Steady progress by little steps :-)

**Comment by GeoffreySangston** [comment]
@prabau What would you say about the status of it right now? The only missing piece is '~Has a cut point for [Long circle S196](https://topology.pi-base.org/spaces/S000196)', and that's just because I didn't think I had the slickest possible argument.

**Comment by david20000813** [comment]
I've checked that all the removed traits are now automatically derived, and the newly added traits all seem correct to me. Before approving though, one question: Given the wording is "S40 is P204", have you intended to remove "S40 is P36" but forgotten to do that?

**Review by david20000813 — APPROVED** [review]

**Pull request merged**
