### PR TITLE
updates to selection principles

### PR DESCRIPTION
**Pull request by ccaruvana**
Updates related to comments in https://github.com/pi-base/data/pull/329

- S22 P151 was updated to have a math stack exchange reference.
- I also fixed an omission in the description of {S61}.
- {S59} was updated to reflect the fact that it's sigma-relatively-compact. I also added the straight-forward reason {S59} is not regular in as an addition to the reference to Counterexamples.
- T382 and T383 were added to obtain results like "Fortissimo space is not Markov $\omega$-Menger" as deductions.

### CODE REVIEW

**Comment by StevenClontz** [comment]
Instead of https://topology.pi-base.org/theorems/T000383/references we should just merge https://topology.pi-base.org/properties/P000154 into  https://topology.pi-base.org/properties/P000069 as they're equivalent for all topological spaces, see Theorem 35 of https://www.sciencedirect.com/science/article/pii/S0166864119300847

The Markov variants are equivalent assuming regular (they're equivalent to sigma-compact); I'm not sure if regularly is necessary offhand.

**Comment by StevenClontz** [comment]
Note that in https://github.com/StevenClontz/research/blob/master/articles/applications-of-limited-information-strategies-in-mengers-game/article.pdf I proved that Markov Menger is equivalent to sigma-relative-compactness for all spaces. So https://topology.pi-base.org/properties/P000071 shouldn't be distinct from https://topology.pi-base.org/properties/P000070.

Oh dip, that's probably my fault in the first place.

**Comment by StevenClontz** [comment]
Looking closer, we already know they are equivalent: https://topology.pi-base.org/theorems/T000165 and https://topology.pi-base.org/theorems/T000166.

**Comment by StevenClontz** [comment]
I'm pretty sure Markov omega-Menger is equivalent to sigma-relative-compact. Proof sketch:

`<=`: Sigma-relative-compact is closed under finite products: if $K_n$ is an increasing cover by relative compacts, $K_n^m$ is an increasing cover of $X^m$ by relative compacts. So given an open omega-cover in round $n$, lift it to the natural cover of $X^m$, then finitely cover $K_n^m$, then drop back to the finite members of the original omega-cover.

`=>` Markov omega-Menger implies Markov meger: given an open cover, close it under finite unions to obtain an omega-cover, pick a finite sub-omega-cover, then use that to get your finite subcover.

**Comment by prabau** [comment]
@StevenClontz Regardingthe proof of [sigma-rel-compact ==> Markov omega-Menger] it's not immediate clear to me that the product set $R\times S\subseteq X\times Y$ of two relatively compact sets $R\subseteq X$ and $S\subseteq Y$ is also rel. compact.  Trying to use the usual tube lemma argument, but not entirely clear how to conclude in the general case where the closures of $R$ and of $S$ are not compact.

**Comment by ccaruvana** [comment]
So I take it that we should collapse Markov Menger and $\sigma$-relatively-compact into one property. Is there any easy way to check if Markov Menger is asserted for any spaces?

I'll go ahead and collapse strategically Menger and strategically $\omega$-Menger.

**Comment by prabau** [comment]
> So I take it that we should collapse Markov Menger and σ-relatively-compact into one property.

Is that what we want to do?  It is true that the two properties are equivalent.  On the other hand, the two properties are very dissimilar from each other, and various theorems relate other properties naturally with one version and not the other, or vice versa.  So I could see some advantages in keeping them separate. Not sure what's best.

**Comment by ccaruvana** [comment]
> So https://topology.pi-base.org/properties/P000071 shouldn't be distinct from https://topology.pi-base.org/properties/P000070.

I was mostly just following on this comment from @StevenClontz . I could also see benefits to keeping them separate.

As a sort of meta question, do we have any criteria for when to merge equivalent properties, in general? This is a sort of tame example, but the equivalence of strategic $\omega$-Menger and strategic Menger is relatively new in the literature. If other properties we are currently tracking are shown to be equivalent in the future, would we simply add two theorems for the equivalence or would we rather collapse properties and leave the deprecated property as a legacy item?

**Comment by StevenClontz** [comment]
In general I think we should avoid equivalent properties, and when they're introduced by accident we should clean them up if possible in a timely fashion. But since I was rude and introduced two equivalent properties years ago, we should deprecate the less natural one as best we can. For now, I think that means checking that only the more natural property is referenced throughout the pi-Base, except for two simple theorems that establish the equivalence.

**Comment by StevenClontz** [comment]
I thought about adding in a commit here that turns all references to P70 (Markov Menger) to P71 (sigma-relatively-compact). But when I looked at it, I realized that it would be awkward: the references all referred to the Menger game and its strategies.

I'm adding discussions of equivalent properties to our next meeting.

**Comment by prabau** [comment]
Not directly relevant, but I am just curious about the notion of "relatively compact to X" used in Steven's paper:
https://math.stackexchange.com/questions/4702452/definitions-of-relatively-compact

I have added an answer to complement Tyrone's answer and have a question at the end: Can one have a subset $A$ that is relatively compact to $X$ without being contained in a compact subset of $X$?
(maybe Tyrone's example fits the bill, need to check it first)  But feel free to comment.

**Comment by StevenClontz** [comment]
Chris and I cleaned up most of the loose ends I believe.

**Comment by StevenClontz** [comment]
I've asked a question at https://math.stackexchange.com/questions/4730419 to wire up the strategy stuff for Menger and Omega-Menger.

**Review by StevenClontz — APPROVED** [review]
This is correct, and the properties in question were already added, so approving. The equivalency of the [$\Omega$]-Menger properties should be established sooner than later, but this won't be (and isn't) the first situation where we have equivalent properties that weren't caught on first submission, so I'd err on the side of keeping PRs fresh rather than delaying this.

**Pull request merged**
