### PR TITLE
Rewrite S000133

### PR DESCRIPTION
**Pull request by gregorynisbet-google**
Rewrite the description of https://topology.pi-base.org/spaces/S000133 using 
the construction given here: https://math.stackexchange.com/q/4833751
    
 Also cite the proof below that the two spaces are equivalent.
    
 https://math.stackexchange.com/a/4834226

### CODE REVIEW

**Comment by prabau** [comment]
Cool.  Regarding the "DO NOT MERGE", you can also mark the PR as in progress by clicking on "Convert to draft" (link at the top of the column on the right).

**Comment by prabau** [comment]
What Steven Clontz shows in https://math.stackexchange.com/questions/4833751 is that (assuming $n\ge 1$) all the spaces $\mathbb R^n$ with the post office metric are homeomorphic to each other.  (He even shows it in a more general situation, but no need to give the full details here I would say.)  Since pi-base only classifies spaces up to homeomorphism, for definiteness I think we could choose the case of $n=1$ as the primary name.

Your suggested name is too long (and there is no such thing as "standardly open" in general).  Best is a name that is short and unambiguous if possible.  How about "Real line with post office metric" as the primary name?

We can keep "Post office metric on the plane" as an alias.  Maybe add "$\mathbb R^n$ with post office metric" as another alias?

Need to add the mathse reference to the refs at the top.

As for the text itself, it could be reorganized to make things clearer.  But I'll let @StevenClontz make comments first.

**Comment by StevenClontz** [comment]
Sorry for the delay here - I'm doing an uncharacteristic amount of travel but things are settling back down.

What do y'all think of #516 to put a pin in this?

**Comment by gregorynisbet-google** [comment]
I would like to apologize for not iterating on this quickly.

I merged in 516 and the most recent changes to the `main` branch.

Do you folks use merge commits or not really?

**Comment by StevenClontz** [comment]
We use the "Squash and merge" strategy generally.

Updating this PR with a merge commit has made the Files Changed diff a bit difficult to read. If the intent is to accept the update I proposed in #516 to this PR, then I'm inclined to squash and merge #516 and close this. Is that okay wiht you @gregorynisbet-google?

**Comment by gregorynisbet-google** [comment]
Yes, that is totally fine. Thanks!

**Pull request closed without merging**
