### PR TITLE
Add Weakly Locally Compact + KC => Locally Relatively Compact

### PR DESCRIPTION
**Pull request by Jianing-Song**
(I used T81, which is the smallest unused number.)

I noticed that the S119 now have both properties P23 and P24, and I'd like to delete either one.

The contents of the files are:
S119/P23: See item #2 for space #122 in DOI 10.1007/978-1-4612-6290-9_6.
S119/P24: Asserted in the General Reference Chart for space #122 in DOI 10.1007/978-1-4612-6290-9_6.

Since the book explicitely mentions the property P23 for the space, while P24 is only shown in the general table, I would like to remove P24. However, there are many spaces (S57, S91, S116, and S120) that have P24 kept, and P23 deducted manually. We could also remove P23 for the sake of unicity.

Any suggestions?

(By the way, I had asked the question on Math SE on whether Weakly Locally Compact + US => Locally Relatively Compact (https://math.stackexchange.com/q/4964467), but I received no answer, so I'll let it go, and any improvement can be done in the future.)

### CODE REVIEW

**Comment by prabau** [comment]
I have various comments about this.  But need to step away from my desk now.  Will reply later.

**Comment by Jianing-Song** [comment]
> I have various comments about this. But need to step away from my desk now. Will reply later.

OK, thanks.

**Comment by prabau** [comment]
A lot of the theorems on the Weakly locally compact page (https://topology.pi-base.org/properties/P000023) have hypotheses of the form [WLC + some separation axiom].  So I have swapped the properties to make it easier to compare the theorems on that page.

**Comment by prabau** [comment]
I think the proposed T81 makes sense.  It cannot be derived from other theorems already in pi-base.

Let WLC = weakly locally compact, LC = locally compact, LRC = locally relatively compact.

The combination [WLC + Hausdorff] implies the more general condition [WLC + regular], which in turn implies both LC and LRC.  (Aside: That's why many of the theorems on the WLC page use WLC + regular as hypotheses.  Note that this is equivalent to WLC + R1 (preregular), but WLC + regular is more common and easier to work with.  That's why we chose that combination.)

Now, there are some examples of LRC + not LC + KC.  These spaces are necessarily not regular.  And one could deduce the LRC properties from asserting WLC directly in this case.  But those examples are also compact, which by itself implies LRC.
So, with the current spaces in pi-base, adding this new theorem T81 will not enable to derive any new traits for spaces.

Still, T81 is a good addition that could be useful for other spaces.

**Comment by prabau** [comment]
Which property to assert when WLC, LRC, LC are all valid and something needs to be asserted? If the space is also T2 or regular, I would say it's easiest to assert WLC, as it is easiest to check for a space and it implies the other two.

**Comment by Jianing-Song** [comment]
> Which property to assert when WLC, LRC, LC are all valid and something needs to be asserted? If the space is also T2 or regular, I would say it's easiest to assert WLC, as it is easiest to check for a space and it implies the other two.

Thanks for your consideration and your comments!
I've kept WLC (P23) and removed LRC (P24) for S119. Is that OK?

**Review by prabau — APPROVED** [review]

**Pull request merged**
