### PR TITLE
Add P180 (Hereditary separability) and S140 (Reals extended by point with cocountable neighborhoods)

### PR DESCRIPTION
**Pull request by marswill**
This PR adds the property of hereditary separability ([P180](https://topology.pi-base.org/properties/P000180)), as well as new theorems to deduce separability [P26](https://topology.pi-base.org/properties/P000026)  ([T440](https://topology.pi-base.org/theorems/T000440)) and countable tightness [P81](https://topology.pi-base.org/properties/P000081)  ([T441](https://topology.pi-base.org/theorems/T000441)) from [P180](https://topology.pi-base.org/properties/P000180).  We also update [T93](https://topology.pi-base.org/theorems/T000093) and [T271](https://topology.pi-base.org/theorems/T000271) to conclude [P180](https://topology.pi-base.org/properties/P000180).

The PR also adds the space [S140](https://topology.pi-base.org/spaces/S000140) discussed [here](https://math.stackexchange.com/q/4854178/1210477) and [here](https://math.stackexchange.com/a/4850979/1210477), as an example of https://topology.pi-base.org/spaces?q=pseudoradial+%2Bcountably+tight+%2B%7Esequential

### CODE REVIEW

**Comment by prabau** [comment]
Would have been easier to have separate PRs for P180 and S140.  But lots of good stuff in there.  Will read it later (or Steven).

**Comment by marswill** [comment]
> Would have been easier to have separate PRs for P180 and S140.

Yeah, when I set out to begin it seemed like a smaller chunk of work.  Didn't quite process how much it had grown until the end.  Lesson learned, I'll be more careful about separating into more manageable pieces in the future so it's easier to review.

**Comment by prabau** [comment]
For T93, the previous version was already referencing item 4 of space 26 from S&S.  But that reference does not do anything.  I would just remove it and clean up the text.

P280: Replace `... is separable` with `... is {P26}`.  It's really the same, but would it be better to say `every subspace` instead of `every set`?

Otherwise, no problem with P280 and theorems.  Onward to the new space.

**Comment by prabau** [comment]
S140 README:
I really like the name for the space, not too long and nicely descriptive.  The alias on the other hand does not add anything, as it does not uniquely characterize the space and the result is available directly via a pi-base search.  I think it should be removed. (There are possibly other spaces with a similarly unhelpful alias/name because we could not find anything better?  But it's not optimal.)

The first sentence is very useful, but I think it should be moved to a later paragraph.  The text can start with "Let $X=...$" so the space is defined right away.

"with $\mathbb R$ having the Euclidean topology" --> "with $\mathbb R$ having the Euclidean topology and open in $X$" (because I think the fact that $\mathbb R$ has the Euclidean topology as a subspace of $X$ does not immediately imply that every open subset of $\mathbb R$ belongs to the topology of $X$).

"and neighborhoods of $\infty$ given by ..." --> "and open neighborhoods of $\infty$ given by ..."

**Comment by prabau** [comment]
P42 (locally path connected = false) is redundant (follows from connected (via strongly connected) + path connected = false)

**Comment by prabau** [comment]
There seems to be some circularity.  T1 follows from P101 (has closed retracts).  But the justification for P101 invokes T1.

**Comment by prabau** [comment]
I am confused by https://topology.pi-base.org/spaces/S000140/properties/P000101 (has closed retracts).
Why is the second paragraph mentioning a path from a point of $\mathbb R$ to $\infty$?  I am missing how that fits with the retraction $r$.

**Comment by marswill** [comment]
> There seems to be some circularity. T1 follows from P101 (has closed retracts). But the justification for P101 invokes T1.

$T_1$ also follows from $k_2H$ (It's also sort of immediate from the definition of the space.)  So circularity shouldn't be a problem.  But maybe there's a preferable way to communicate that fact?

**Comment by prabau** [comment]
> > There seems to be some circularity. T1 follows from P101 (has closed retracts). But the justification for P101 invokes T1.
> 
> T1 also follows from k2H (It's also sort of immediate from the definition of the space.) So circularity shouldn't be a problem. But maybe there's a preferable way to communicate that fact?

Yeah, I can see it's not a problem.  Maybe repeat the obvious T1=true in the proof of P101=false if it uses it, and without linking to {P2}?

**Comment by prabau** [comment]
P39 (hyperconnected = false) may be an easier property to show that P49 (extremely disconnected = false).  They are equivalent under the assumption of connectedness.  Does not matter much.

**Comment by marswill** [comment]
> I am confused by https://topology.pi-base.org/spaces/S000140/properties/P000101 (has closed retracts). Why is the second paragraph mentioning a path from a point of R to ∞? I am missing how that fits with the retraction r.

The upshot is that $\infty$ and $\mathbb R$ are not connected by paths, so by continuity (which preserves path-connectedness), either $r(\mathbb R)=\{\infty\}$, or $r(\mathbb R)\subseteq \mathbb R$.  Then we continue reasoning from there.

Maybe its a little jarring to suddenly have a path-connectedness argument seemingly come out of the blue like that.  I'm thinking a bit on how to rephrase.

**Comment by prabau** [comment]
I see what you mean now.  We also don't need to repeat the full argument that points of $\mathbb R$ and $\infty$ cannot be joined by a path.  I think we can just let the reader look at the proof that the space is not path connected.  There is currently no slick way to refer to that from text, but we can put a direct link `<https://topology.pi-base.org/spaces/S000140/properties/P000037>`.

**Comment by prabau** [comment]
Sorry for the interruption.  For P101, I was thinking of some more radical streamlining.  Let me write it up below.

Where are you doing this development?  On your computer in a private branch?  Or via the github.dev interface directly on the `hered-sep` branch in the official repo?

**Comment by prabau** [comment]
We can wrap this up tomorrow.

**Comment by prabau** [comment]
Nice streamlining.  We can also remove the refs for P101, not used anymore.
And P89 (fixed point property) could have a similar simplification.

Will look at the rest tomorrow.

**Comment by marswill** [comment]
> Sorry for the interruption. For P101, I was thinking of some more radical streamlining. Let me write it up below.
> 
> Where are you doing this development? On your computer in a private branch? Or via the github.dev interface directly on the `hered-sep` branch in the official repo?

Doing it on the official branch via github.dev, and while it's mostly been fine, I'm starting to realize the downsides of that, since after I do a pull request, any revisions I make in response to comments can't really be previewed by me before they're committed. May have to rethink my setup for all of this.

**Comment by prabau** [comment]
> Doing it on the official branch via github.dev, and while it's mostly been fine, I'm starting to realize the downsides of that, since after I do a pull request, any revisions I make in response to comments can't really be previewed by me before they're committed. May have to rethink my setup for all of this.

I don't know how to preview without committing either.  Maybe we can discuss this in the next zoom meeting.
I was asking about github.dev because it allows to have more than one person make changes to a branch.  One person can do minor changes on top of the other person's work and vice versa.  Steven and I have done that in the past when it's convenient.

**Comment by prabau** [comment]
For P172 ($k_2$-Hausdorff), I am trying to follow the proof of [KIP + T1 ==> $k_2$-Hausdorff] in https://math.stackexchange.com/a/4854148/52912.

It shows that given any $f,g\colon Z\to X$ continuous maps from a compact Hausdorff space $Z=(Z,\tau)$ into $X$, the set $A=\\{a\in Z\mid f(a)=g(a)\\}$ is closed. How is that a characterization of the $k_2$-Hausdorff property exactly?

**Comment by StevenClontz** [comment]
I feel like I recall that being a characterization from the same paper I got the characterization I like (2nd paragraph of https://topology.pi-base.org/properties/P000171/ )

**Comment by prabau** [comment]
See Rezk 4.2(3) maybe.  It's a little different.

**Comment by StevenClontz** [comment]
Oh, it's just the vanilla definition of $k_2$-Hausdorff lol.

>  and since this holds for arbitrary pairs of maps into X, the diagonal is k2-closed. Thus X is k2-Hausdorff.

In particular, every map $h:Z\to X^2$ can be decomposed into continuous maps $f,g:Z\to X$. Then $h^{-1}[\Delta]=\\{a\in Z:f(a)=g(a)\\}$.

**Comment by prabau** [comment]
Of course.  Nice.

**Comment by prabau** [comment]
All right.  It all looks good to me.  This space was really interesting to nail down, illustrates lots of maybe unexpected properties.

Approving this.
@marswill fyi procedurewise, when I approve a PR (with "squash and merge"), I don't like to have "git log" later show the full list of little commits that were used to get the final result (18 of them in this case).  Most of them are totally uninformative and can be recovered from github anyway.  And all the commits get squashed into a single commit anyway.  So I usually blank out the detail panel and just keep the informative title before pressing "squash and merge".  (But as we discussed before, it's optional, as some folks prefer to leave these details in.)

**Review by prabau — APPROVED** [review]

**Comment by prabau** [comment]
Exception to what I said about squash and merge.  When more than one person contributed, the detail panel shows the list of contributors.  I leave this in in that case.

**Comment by StevenClontz** [comment]
> (But as we discussed before, it's optional, as some folks prefer to leave these details in.)

It's not so much as I prefer to leave the details, as much as I'm lazy and don't want to discourage similarly lazy contributors from participating. 🙃

**Pull request merged**
