### PR TITLE
Add hereditarily connected property

### PR DESCRIPTION
**Pull request by danflapjax**
Adds hereditarily connected property, 11 theorems for it plus another theorem that arose during my work, and some traits for spaces where the property holds.

Addresses #796

### CODE REVIEW

**Comment by prabau** [comment]
P196: The most important property, structurally, is the fact that the family of open sets is totally ordered by inclusion.  The other equivalent properties directly follow from that, and it's also the easiest to check for a given space.  So it seems to me that should preferably be the primary name.

Based on previous discussions in community calls, for names that are nouns instead of adjectives we have usually followed the pattern "Has ...".  Thus "Has a totally ordered topology".  Note that this convention was not always followed (e.g., "Partition topology").  So we can ask @StevenClontz for advice about that.

When referencing a paper which is also in the `refs:` list, we normally use the same reference in the text.  So in this case, `{{zb:0396.54009}}` instead of referencing the pdf file directly.  The pdf file is accessible via the doi link on the zbmath page.
(Alternatively, use the doi directly?)

I think the last sentence should say: "For proof of the equivalences and further characterizations, see ...".

Is the third bullet meant to mean "The specialization preorder is a total order"?  Also, which property does that correspond to in Theorem 22 of the paper?

P185: same comment about the reference, which should also be added to the `refs:` section.

**Comment by prabau** [comment]
T550: seems redundant

**Comment by danflapjax** [comment]
I agree that a property name that the open sets are totally ordered would be much clearer, but I was reluctant to invent a name for the database.

You are correct about T550; it holds that countable + well-based -> second countable.

**Comment by StevenClontz** [comment]
"Hereditarily connected" feels more natural, while "has a topology totally ordered by subset relation" feels more artificial, even though they end up to be equivalent, and the latter characterization ends up being more useful. So I'd vote for "hereditarily connected" as the main name.

I don't have strong feelings of "Has a partition topology" or "Partition topology", though I'd like to pick one for consistency and put it in the wiki for future reference.

**Comment by prabau** [comment]
Yeah, thanks.  I am fine with "hereditarily connected".  And since it's only an alias and not the main name, I am ok with "Totally ordered topology" and not "Has a totally ordered topology".

**Comment by prabau** [comment]
P196: "totally ordered by set inclusion" --> "totally ordered by inclusion" (is there another kind of inclusion?).
It's obvious, but I think it would be useful to have both "The family of open sets is totally ordered by inclusion" and "The family of closed sets is totally ordered by inclusion" (since the second one is used explicitly in the proof of some of the theorems).

T547: "the property is hereditary": not clear if "the property" refers to Normal or to Hereditary connected.  But it's obvious, so maybe remove that phrase and all becomes clearer.  Also typo: "disjoint".

T548: Should we mention condition (10) of Theorem 23?  Plus link to the pdf not working, like in many other files.

T555: the definition of biconnected is specifically phrased in terms of a partition into two subsets, etc.  But probably clearer would be to use the equivalent characterization for P44.  So something like: "$X$ has two disjoint subsets, each with at least two points.  And each of the subsets is connected."

T556: I am confused by this proof, and the business of second largest open set.  The following seems easier:
"Let $\mathscr U$ be an open cover of $X$.  By compactness, $\mathscr U$ has a finite subcover $\mathscr V$.  Since $\mathscr V$ is totally ordered by inclusion, it has a largest element $V$.  So $X=\bigcup\mathscr V=V$.  Therefore $X\in\mathscr U$ and $\\{X\\}$ is a clopen refinement of $\mathscr U$ partitioning the space."

**Comment by danflapjax** [comment]
I replaced T556 with stronger theorems and addressed the rest of your comments.

**Comment by prabau** [comment]
T550 [shrinking + hyperconnected ==> ultraparacompact]  This is a good result.
For the proof, "every open cover must contain $X$": not hard, but it would be worth adding something to explain.

For the last sentence, showing every open cover admits a clopen refinement is not enough to have ultraparacompact.  One also needs the refinement to be a partition of the space, or equivalently, to be locally finite.  So easier to say for example something like "Thus $\mathscr U$ admits $\\{X\\}$ as a clopen refinement that partitions the space." (if you name the open cover as $\mathscr U$ in the previous sentence).

**Comment by prabau** [comment]
T551: The proof is incomplete.  The first part needs some more explanation.  And the last part is not trivial, needs a reference to something.  Here is a suggestion:

`By {P93} choose a countable open neighborhood of each point.  So $X$ can be covered by a family of countable sets, forming a chain under inclusion by {P196}.  And the union of a chain of countable sets has cardinality at most $\aleph_1$ (see {{mathse:342091}} for example).`

And add https://math.stackexchange.com/questions/342091 to the `refs:`.

**Comment by prabau** [comment]
T552: I don't understand this proof.  Can you explain it to me here?

**Comment by danflapjax** [comment]
> T552: I don't understand this proof. Can you explain it to me here?

That turned out to be another theorem relating to ultraparacompact + connected, which is equivalent for nonempty spaces to 'there exists a point whose only neighborhood is $X$'. If such a space is homogeneous, then every point has $X$ as its only neighborhood.

**Comment by prabau** [comment]
Thanks for the new T552.  Again there is a minor problem (to have an ultraparacompact space it's not enough to require that every open cover has a clopen refinement).  Let me fix this.

**Comment by prabau** [comment]
Updated T551 as suggested earlier.

I also checked for myself that T554 is true.  Rephrased the last part in terms of a successor ordinal, which seemed easier than a non-limit ordinal (assuming nonempty).  Also added that the topology should be homeomorphic to the left-ray topology on a successor ordinal.  Please double check me on this.

That would indicate for example that the left-ray topology on $\omega+1$ or $\omega_1+1$ is spectral.  These would be good examples to add at some point, I think.

**Comment by prabau** [comment]
Next, need to check the changes for the spaces, which should wrap things up.

**Comment by prabau** [comment]
@danflapjax I checked the changes for the spaces and everything looks good.  As far as I am concerned, this is ready to go.

Please see if you have any comments about my changes, and if not, I'll approve.

**Comment by StevenClontz** [comment]
@prabau should this be approved, or did you want another reviewer to take a look?

**Comment by danflapjax** [comment]
> Please see if you have any comments about the changes I added.

Your changes look great to me.

**Review by prabau — APPROVED** [review]

**Pull request merged**
