### PR TITLE
S44 Nested interval topology P201 Has a generic point

### PR DESCRIPTION
**Pull request by danflapjax**

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
Question: Is this one quasi-sober (because it is a product of quasi-sober spaces?)? 

Then [(S44|Hyperconnected)](https://topology.pi-base.org/spaces/S000044/properties/P000039) will imply it has a generic point: https://topology.pi-base.org/theorems/T000594

**Comment by danflapjax** [comment]
> I wonder if Hereditarily connected + Has a generic point implies quasi-sober already?

It would in fact. Every closed strict subset automatically has a generic point, so the only issue is whether the entire space does.

**Comment by prabau** [comment]
The Kolmogorov quotient of this space is S199 (left ray topology on $\omega$).  And probably most of the properties in question hold iff they hold for the Kolm. quotient.

So it may be easier to show things for S199 and refer to that space for the current S44.

And like @GeoffreySangston said, asserting quasi-sober would be a more efficient way to go.

**Comment by david20000813** [comment]
S199 is indeed sober, as is quite easy to check (closed sets are $[n, \righarrow)$, which is the closure of exactly one point, $n$), and quasi-sober is equivalent to the Kolmogorov quotient being sober, as mentioned in the property page for quasi-sober.

Should a new PR be written for this? Just add sober for S199 and quasi-sober for S44.

**Pull request closed without merging**
