### PR TITLE
Add Michael Line

### LINKED ISSUE #216: Add Michael Line
https://math.stackexchange.com/q/4597483

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #216

### CODE REVIEW

**Comment by StevenClontz** [comment]
Opening PR but appreciate a reference for the name.

**Comment by prabau** [comment]
Engelking 5.1.32.  And also the historical notes at the end of the section have the reference to Michael's original article.

**Comment by prabau** [comment]
If you want to add a reference mentioning Michael line, https://dantopology.wordpress.com/2012/10/28/michael-line-basics could be a good one.

What do you think of making Michael line the primary name for this space?  It's much more well known than the name in Counterexamples.

And possibly remove the other alias currently there, which does not seem to add anything.

**Comment by lyengulalp** [comment]
Deleted unhelpful alias, added Ernest Michael wikipedia reference.

**Review by lyengulalp — APPROVED** [review]

**Comment by prabau** [comment]
> Deleted unhelpful alias, added Ernest Michael wikipedia reference.

Hmm, the wikipedia reference you added does not really identify what the Michael space is.  Shouldn't we replace that with something else that more specifically identifies the space as such?  I suggested one above, but other alternatives would be fine too.

**Comment by StevenClontz** [comment]
I'd accept a PR to that effect - this was mostly an instructive exercise for Lynne, and at least the citation given attributes the space to Dr. Michael.

**Comment by prabau** [comment]
See #222.

**Pull request merged**
