### PR TITLE
Add path connected => σ-connected and the property for K-topology

### PR DESCRIPTION
**Pull request by Jianing-Song**
As for now for K-topology is σ-connected, I am refering to my answer giving in https://math.stackexchange.com/questions/4975686. We can change it if a separate question is needed.

I also replaced the "general reference chart" content with a math SE link for K-topology is not path-connected.

### CODE REVIEW

**Comment by prabau** [comment]
One question (https://github.com/pi-base/data/issues/769#issuecomment-2362855393):

What would be your preferred primary name for this space:
- "Smirnov's deleted sequence topology"
- "K-topology on $\mathbb R$"

The second one is used in Munkres and many mathse posts refer to that name due to that. But it seems both names are used in the literature.

(@ccaruvana, @StevenClontz feel free to give your opinion too)

**Comment by Jianing-Song** [comment]
> One question (see [#769 (comment)](https://github.com/pi-base/data/issues/769#issuecomment-2362855393) for more details about the name of Smirnov in this context):
> 
> What would be your preferred primary name for this space:
> 
> * "Smirnov's deleted sequence topology"
> * "K-topology on 
>     
>       R
>     
>   "
> 
> The second one is used in Munkres and many mathse posts refer to that name due to that. But it seems both names are used in the literature.
> 
> (@ccaruvana, @StevenClontz feel free to give your opinion too)

I personally prefer Smirnov's deleted sequence topology because the name "$K$-topology", despite being short, is quite random. It could have been called $M$-topology if the set $\\{1/n\\}$ were labelled $M$, or $N$-topology, or named after any letter the author may have chosen.

**Comment by prabau** [comment]
> I personally prefer Smirnov's deleted sequence topology because the name "$K$-topology", despite being short, is quite random. It could have been called M -topology if the set { 1 / n } were labelled M , or N -topology, or named after any letter the author may have chosen.

Yeah, that's true.  Seems like a good reason to keep the current name.

What about changing the name to "Smirnov's deleted sequence topology on $\mathbb R$" ?

**Comment by Jianing-Song** [comment]
> > I personally prefer Smirnov's deleted sequence topology because the name "$K$-topology", despite being short, is quite random. It could have been called M -topology if the set { 1 / n } were labelled M , or N -topology, or named after any letter the author may have chosen.
> 
> Yeah, that's true. Seems like a good reason to keep the current name.
> 
> What about changing the name to "Smirnov's deleted sequence topology on R " ?

I'm not sure. I think there are no other sets on which there is a "Smirnov's deleted sequence topology"?

**Comment by prabau** [comment]
For the P189 trait of the K-topology, I changed the reference to the specific relevant answer to the mathse post (because the question itself and the title don't mention anything about that space, and neither does the other answer).

**Pull request merged**
