### PR TITLE
Deleted sequence of intervals topology

### PR DESCRIPTION
**Pull request by david20000813**
As suggested in #926.

### CODE REVIEW

**Comment by Almanzoris** [comment]
Nice! I will review it in detail tomorrow.

**Comment by Almanzoris** [comment]
I find it good. Nice proofs!

**Review by Almanzoris — APPROVED** [review]

**Comment by Almanzoris** [comment]
In #926, you say that, as far as you can tell, it is a new construction. I wonder if you can add your name to the space's name, like it was done for S100.

**Comment by david20000813** [comment]
@Almanzoris The construction is quite close to that of S56, Smirnov's deleted sequence topology, so, unlike S100, I wouldn't be surprised if this has been thought of before and I'm just unaware of it, which is why I chose to not add my name to the space's name.

**Comment by prabau** [comment]
@david20000813 One thing I forgot to mention.

When you do a "squash and merge", it is recommended to first blank out the associated description before clicking on "squash and merge".  I.e., only keep the title.

For an explanation, see 
https://github.com/pi-base/data/pull/912#issuecomment-2477251798 and the following comment,
and https://github.com/pi-base/data/pull/779#issuecomment-2366952604.

**Comment by david20000813** [comment]
@prabau Understood. Thanks for letting me know.

**Pull request merged**
