### PR TITLE
add s105 T4 property

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
Not sure it's worth adding an explicit trait if the only justification is referring to the General Reference Chart of S&S.  Is there a better reference maybe?

**Comment by StevenClontz** [comment]
While a stronger reference or justification is preferable, I think it's always better to add accurate data to the repo. (In this case in particular, I think most of our assertions are of this form.)

I'm working on my goal to remove all unknown spaces for $T_0$: https://topology.pi-base.org/properties/P000001/spaces

**Comment by prabau** [comment]
On the other hand, one could argue that the goal is also to not have justifications that are merely pointing to the general chart in S&S.  

In this case, it seems that without external references we can instead claim it's T2 as a subspace of S103. (We should probably tweak the README to mention it's a subspace of S103.)  And since it's compact, T4 will follow automatically.

**Comment by StevenClontz** [comment]
> the goal is also to not have justifications that are merely pointing to the general chart in S&S.

Well, acktually, the original purpose of pi-Base was to be a digital version of the appendix of S&S's *Counterexamples*, and the rest came later.

I like the compromise to use the subspace argument, and will add it to this PR.

**Review by prabau — APPROVED** [review]

**Pull request merged**
