### PR TITLE
S133 is not locally countable

### PR DESCRIPTION
**Pull request by StevenClontz**
Answers https://topology.pi-base.org/spaces?q=%24G_%5Cdelta%24+space%2BT_1%2Bscattered%2B%7ELocally+countable

### CODE REVIEW

**Comment by prabau** [comment]
Since we are removing P53 (metrizable), I think P55 (completely metrizable) should have the following sentence at the beginning, since P55 in defined as being metrizable plus some extra condition:
"The space is metrizable by construction."

Also, in the README file the post office metric is denoted by $p$.  In P55, some of the $d$ should be replaced by $p$.

**Comment by prabau** [comment]
Also, looking at the trait for P26 (separable), it gives as justification "It contains an uncountable discrete set, namely ...".
That does not seem valid.  One can have an uncountable discrete set and still be separable.
Maybe we should just say: Every point $x\ne 0$ is isolated.

**Comment by prabau** [comment]
And P129 can also be removed.

**Comment by prabau** [comment]
Hmm, I see more stuff that needs to be cleaned up, from the time that the space was based on $\mathbb R^2$.  If you want, I can do all these little changes in a separate PR.  Or feel free to do it all here.

**Comment by StevenClontz** [comment]
Thanks for the careful eye. I'll do the housekeeping now...

**Comment by prabau** [comment]
- README: not sure what the last sentence is adding, as the first one already mentioned that all points $x\ne 0$ are isolated.  And as for the corresponding parallel construction for $\mathbb R^n$, it was already mentioned.  No need to mention $\mathbb R^n$ again.
- I don't really see that calling the origin a "particular point" helps the overall understanding.  But if you want to have that, it could be mentioned as part of the first sentence in the README: "with basic open neighborhoods of the "particular point" $0$ ..."
- P23: no problem.  Possibly use interval notation $(-\varepsilon,\varepsilon)$, etc
- P26: redundant, thanks to P29
- P29: The README already said that $0$ is the particular point.  Repeating this here is puzzling.
- P129: redundant

**Comment by prabau** [comment]
FYI, I added an answer to https://math.stackexchange.com/questions/4833751 to expand on yours.  That level of generality will be useful to show the space is a LOTS (which could be done in a separate PR).

**Comment by StevenClontz** [comment]
> which could be done in a separate PR

could, but wasn't. I think it's ready to merge here.

**Comment by prabau** [comment]
I realized my mathse answer is missing something.  One must additionally require that the $V_n$ form a neighborhood base at the particular point.  That is needed, but not guaranteed as currently written.

It's also needed to have $V_0=X$ to ensure $X$ is continuum-sized; otherwise the cardinality of the whole space is not even guaranteed.  Plus other minor things need to be fixed.  Let me fix a few of these things, and then you can take a look.

**Comment by prabau** [comment]
Fixed a few things and added P126 (Door) and P166 (has a coarser separable metrizable topology).  Please take a look.

**Review by StevenClontz — COMMENTED** [review]
Looks good. (Someone else has to approve/merge.)

**Review by prabau — APPROVED** [review]

**Pull request merged**
