### PR TITLE
add sequentially discrete and omega-C

### LINKED ISSUE #387: Spaces where all convergent sequences are eventually constant
Spaces where all convergent sequences are eventually constant keep appearing in various arguments.  I think it would be useful to add this as a property in pi-base.

I have asked https://mathoverflow.net/questions/451796/topological-property-of-convergent-sequences-being-eventually-constant to see if there is a usual terminology for this.

What do you think?

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #387

### CODE REVIEW

**Comment by StevenClontz** [comment]
I'm unaware of a canonical name for $\omega C$. The closest concept I know of is $\omega$-bounded, but that means the closure of countable is compact. But it's an easily-checked property that implies sequentially discrete.

**Comment by prabau** [comment]
Added a few theorems that allow to automatically deduce some of the traits, and removed the redundant traits.

**Comment by prabau** [comment]
The notion of "countable sets are closed" is good to have in pi-base.  Not entirely sure about the name ωC.  Nothing about introducing a new name if there is nothing out there.  And it does not feel bad at all, but tossing ideas around for possible alternatives.  "ω" hints to countable (better than σ here I would say).  But the "C" for closed is kind of cryptic.  Would there be another term with C meaning closed out there, for comparison?

**Comment by prabau** [comment]
There may be some duplication right now between T417 and T418.  Please take a look if we want to collapse something.  And also if we need to add more basic results.

**Comment by StevenClontz** [comment]
> Would there be another term with C meaning closed out there, for comparison?

I went with $\omega C$ to compare with $KC$ and $RC$.

**Comment by StevenClontz** [comment]
I'd prefer to defer more theorems to another PR.

I think what we have is correct, though T415-T418 could use references outside the pi-Base.

**Comment by prabau** [comment]
> I went with ωC to compare with KC and RC.

That makes some sense.  So it's as good a name as any.

**Comment by prabau** [comment]
> I'd prefer to defer more theorems to another PR.
> 
> I think what we have is correct, though T415-T418 could use references outside the pi-Base.

Yeah, we can add more theorems later.  The reason I added some of the theorems T415-T418 was to obviate the need for some of the explicit trait files.

I did not add a reference for T415 to T418 because they are each one or two lines in the "immediate from the definitions" category.  Hard to find a reference for these things (given that they don't have standard names) and adding something to mathse would be really trivial in this case.  It would be a good example to discuss in our next community meeting.


I would also say T415-T418 are more "immediate" that T413 and T414 (some parts of the arguments for those two seem to be left for the reader to do in their heads).

**Comment by prabau** [comment]
Since both Steven and I contributed to this, adding Chris and Lynne as reviewers.

@ccaruvana @lyengulalp Hope you guys see this!

**Comment by prabau** [comment]
One more observation for https://topology.pi-base.org/spaces/S000017 (cocountable topology on the reals).

Using T415 [P-space + T1 ==> ωC] and [ωC ==> T1] (via T413, T414), it's equivalent to:
- remove T1 and assert ωC
- keep T1 and deduce ωC

**Comment by StevenClontz** [comment]
> One more observation for https://topology.pi-base.org/spaces/S000017 (cocountable topology on the reals).
> 
> Using T415 [P-space + T1 ==> ωC] and [ωC ==> T1] (via T413, T414), it's equivalent to:
> 
> * remove T1 and assert ωC
> * keep T1 and deduce ωC



Yep. I went with $\omega C$ as the space is precisely the minimal topology with that property.

**Comment by StevenClontz** [comment]
> I did not add a reference for T415 to T418 because they are each one or two lines in the "immediate from the definitions" category. Hard to find a reference for these things (given that they don't have standard names) and adding something to mathse would be really trivial in this case. It would be a good example to discuss in our next community meeting.

Linked here from https://github.com/orgs/pi-base/discussions/364

**Comment by ccaruvana** [comment]
Maybe I'm missing something, but the following line from P167 , according to https://en.wikipedia.org/wiki/Sequential_space, relates to P79.

> "Equivalently, every sequentially closed set is closed. That is, the topology is equal to its own sequential coreflection."

**Comment by ccaruvana** [comment]
@prabau In the wikipedia article, it says that P79 is equivalent to "every sequentially closed subspace is closed," as does the description of P79. So are P79 and P167 equivalent?

**Comment by prabau** [comment]
> @prabau In the wikipedia article, it says that P79 is equivalent to "every sequentially closed subspace is closed," as does the description of P79. So are P79 and P167 equivalent?

Now I see what you mean.  That's a big mistake.  We mean: "every set is sequentially closed", right?

**Comment by prabau** [comment]
Fixing this, I hope :-)

**Comment by ccaruvana** [comment]
> Now I see what you mean. That's a big mistake. We mean: "every set is sequentially closed", right?

Yeah, and probably "the sequential coreflection is discrete." Some very subtle wording with the sequential closure one!

**Review by ccaruvana — APPROVED** [review]

**Pull request merged**
