### PR TITLE
Adds contractible = true to spaces with excluded/particular point topologies

### PR DESCRIPTION
**Pull request by GeoffreySangston**

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
I asked on [MSE](https://math.stackexchange.com/questions/4993007/is-a-path-connected-space-with-a-dispersion-point-necessarily-contractible) if a general condition which would simultaneously cover the particular + excluded point topologies is true.

**Comment by StevenClontz** [comment]
"Has a dense point" seems like a fine utility property.

It's kind of made up, but define a **global limit point** to mean "a point which belongs to the closure of every non-empty set", equivalently, "a point that belongs to no proper open set". Then we could add "Has a global limit point".

I know @jamesdabbs has some plumbing to support more elaborate logic than `AND(properties) => property`; for example, we used to have several `P+Q => R+S` theorems, until we split them up for editorial reasons. And as you note, `P+Q => R or S` can be expressed as two theorems. I don't have a great idea of the best model right now.

**Comment by prabau** [comment]
FYI, a "dense point" is usually called a "generic point" of the space.

**Comment by prabau** [comment]
I need to read in detail what you wrote.  But FYI, see also this answer from Eric Wofsey:
https://math.stackexchange.com/questions/2965227/are-minimal-neighborhoods-in-an-alexandrov-topology-path-connected

showing that a space with a point satisfying a similar condition is contractible.  And similarly for the dual condition.

**Comment by prabau** [comment]
Some comments.

Item 2: Adding "Has a generic point" seems reasonable to me.  It's used in the literature, and there are connections to the notion of quasi-sober (obvious theorem to add).

I don't understand your suggestions A1, A2.  
Please double check me on this, but the following are always equivalent for a point $p\in X$: (redundant, but just for clarity)

- $p$ is in every nonempty open set in $X$
- $p$ is contained in no proper closed set
- $X$ is the only closed set containing $p$
- The closure of $\\{p\\}$ is $X$
- $p$ is a generic point of $X$

And also these are equivalent:
- $p$ is in every nonempty closed set in $X$
- $p$ is contained in no proper open set
- $X$ is the only open set containing $p$
- $X$ is the only neighborhood of $p$
- NEED TO GOOD TERMINOLOGY HERE

For the second batch, I don't know what a good terminology would be.  But repeating what @StevenClontz has said multiple times, I don't think we want to introduce terminology of our own here.  (see several comments to @Moniker1998 recently). Most probably somebody has come up with something in the literature already.  And preferably it should be justified by simplifications or extensions of pi-base theorems and traits.  (I guess the discussion above kind of does it. There are more examples than the excluded point topologies).

**Comment by prabau** [comment]
Items 9 and 10: Please don't add any Zariski topology stuff as part of this.  It's a lot more involved and would deserve its own PR at the least.

**Comment by GeoffreySangston** [comment]
> Item 2: Adding "Has a generic point" seems reasonable to me. It's used in the literature, and there are connections to the notion of quasi-sober (obvious theorem to add).
> 

What do you think about 'Has a dense point' as an alias? I was influenced by [this answer](https://math.stackexchange.com/a/4694817/444923) which says, "such a point is usually called a *dense point*", and which also says, "The related term generic point is used in algebraic geometry [sic] even when there is not an actual point that is in every open set, so to be unambiguous I would stick to dense point." I can't actually confirm if they're correct, since they don't specify where this is called a dense point. I could look around Google scholar.

> I don't understand your suggestions A1, A2. 

A and B are just alternative ways of getting a proposition of the form X => Y or Z into pi Base. A is to add both [X and ~Y => Z] and [X and ~Z => Y]. B is to create a new property named "Y or Z".

> Please double check me on this, but the following are always equivalent for a point p ∈ X : (redundant, but just for clarity)

These lists look good. I'll likely use them to form the lists of equivalent definitions when I add the two new properties.

> For the second batch, I don't know what a good terminology would be. But repeating what @StevenClontz has said multiple times, I don't think we want to introduce terminology of our own here.

I'll look around Google scholar.

**Comment by prabau** [comment]
> What do you think about 'Has a dense point' as an alias? I was influenced by [this answer](https://math.stackexchange.com/a/4694817/444923) which says, "such a point is usually called a _dense point_", and which also says, "The related term generic point is used in algebraic geometry [sic] even when there is not an actual point that is in every open set, so to be unambiguous I would stick to dense point." I can't actually confirm if they're correct, since they don't specify where this is called a dense point. I could look around Google scholar.


Maybe, maybe not.  Mathse is not necessarily an authoritative source.  Anybody can write anything there.  Like you said, we should look at google scholar, as well as zbmath and maybe Encyclopedia of general topology.

I also don't understand what that guy says.  A generic point $p$ is a point such that the closure of the singleton $\\{p\\}$ is the whole space.  In other words, $\\{p\\}$ is dense in $X$.  That exactly means that $p$ is in every nonempty open set.
Why does he say there may not be an actual point that is in every open set?

**Comment by GeoffreySangston** [comment]
@prabau 
> * NEED TO GOOD TERMINOLOGY HERE

Currently working on this problem. Barmak and Peter Mays' books on finite topology define a [preorder](https://en.wikipedia.org/wiki/Preorder) (reflexive + transitive relation, possibly not anti-symmetric) associated to a finite (more generally [Alexandrov](https://topology.pi-base.org/properties/P000090)) space by $x \le y$ if and only if $x$ is contained in every open neighborhood of $y$.

The [Wikipedia page on specialization preorder](https://en.wikipedia.org/wiki/Specialization_(pre)order) defines the same concept (look down the page at the second definition after "_For the sake of consistency_") for arbitrary topological spaces. This page says there is disagreement on which direction the order goes in, and this page's convention differs from the two books mentioned. This page happens also to have a part about generic points, where it gives an explanation for the the etymology of 'specialization' here.

Using the convention from Barmak, a maximum point under this preorder would be a point $y$ such that every $x \in X$ is contained in every open neighborhood of $y$. I.e., $X$ is the only open neighborhood of $y$. And a minimum point $z$ would be a point such that $z$ is contained in every non-empty open set (the first equivalent version of generic point you give above).

So I believe names / additional aliases for these properties could be "Has maximum point under the specialization preorder", "Has minimum point under the specialization preorder". We would need to decide which direction the preorder should go in, however.

**Comment by prabau** [comment]
Given a preorder, there is a corresponding Alexndrov topology where the open sets are the [upper sets](https://en.wikipedia.org/wiki/Upper_set), or are the lower sets, depending on your conventions.  I think in pi-base we have been using more the convention that the open sets are the upper sets, which is also used in https://en.wikipedia.org/wiki/Alexandrov_topology and https://en.wikipedia.org/wiki/Specialization_(pre)order.  But as you mentioned, I think people in algebraic geometry are more used to the opposite convention.

In any case, the notion " $x$ is a specialization of $y$" (notation: $y\rightsquigarrow x$) is independent of this choice for the Alexandrov topology (and makes sense in any space, even non-Alexandrov spaces).  So instead of max or min for the specialization preorder, we can say something like " $x$ is a specialization of every other point".

Possible names for the property of the space:

"Has a point more specialized than every other point"
"Has a point that is a specialization of every other point"
"Has a point with $X$ as only neighborhood"
"Has a point belonging to all nonempty closed sets"
"Has a point belonging to all closed sets"  (ignoring "nonempty", which only needs to be in the text)
etc, etc.

These are all paraphrases for what we are trying to say.

Is there an article somewhere that makes use of that notion, so we can see what they did?

**Pull request closed without merging**
