### PR TITLE
fix meager property on double-pointed reals

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
It's actually an error in the General Reference Chart in the appendix of Steen & Seebach.

**Comment by prabau** [comment]
In that case, can we add this kind of verbiage "Erroneously asserted as false in the General Reference Chart for space ... "
similar to what was done in https://topology.pi-base.org/spaces/S000014/properties/P000054 and various other places?  It makes it easy to search for the errors in S&S.

**Comment by prabau** [comment]
Actually, even better, we can just remove the trait file for meager for that space.  Once we have the new version of T136 (weakly locally compact + regular ==> Baire), we'll have Baire and hence not meager for free.

**Review by prabau — APPROVED** [review]

**Comment by StevenClontz** [comment]
> Actually, even better, we can just remove the trait file for meager for that space.

Done. Though we do lose the note that Counterexamples had an error. I don't think cataloging these errors is an essential service, and the less of pi-Base that's just "asserted in Counterexamples reference chart" the better anyway.

**Pull request merged**
