### PR TITLE
Modified T522

### PR DESCRIPTION
**Pull request by Jianing-Song**
I found that I had made many mistakes:

(i) Munkres proves that a linear continnum is a LOTS, but the equivalence between a connected LOTS and a linear continnum is only stated later in Exercise 4 of Section 24 (although easy to prove);

(ii) Theorem 24.1 of Munkres only **states** that the intervals of a linear continnum are connected, even though the proof deals with the general case of order-convex subsets. By the way, not all order-convex subsets are intervals, like $\mathbb{R}\times\\{0\\}$ in $\mathbb{R}\times\mathbb{R}$ with lexicographical order. Fortunately, this is enough to prove that the basis defining the order topology consist of connected sets.

I've changed the wording but I found it still a bit tedious. Any suggestions?

### CODE REVIEW

**Comment by prabau** [comment]
The new formulation is better.  But if the LOTS has a minimum element $a$, half-open intervals $[a,b)$ are nbhds of $a$ without being open intervals.  How about just tweaking the second part of the sentence to something lilke this:

"..., and every order-convex subset of $X$ has the same property, so is {connected} (by Theorem 24.1 in {{Munres}}).  Thus $X$ has a basis consisting of connected sets."

**Comment by prabau** [comment]
Aside: in $\mathbb{R}\times\mathbb{R}$ ordered lexicographically the subset $\mathbb{R}\times\\{0\\}$ in not order-convex.  Did you mean $\\{0\\}\times\mathbb R$ ?

**Comment by Jianing-Song** [comment]
> The new formulation is better. But if the LOTS has a minimum element a , half-open intervals [ a , b ) are nbhds of a without being open intervals. How about just tweaking the second part of the sentence to something lilke this:
> 
> "..., and every order-convex subset of X has the same property, so is {connected} (by Theorem 24.1 in {{Munres}}). Thus X has a basis consisting of connected sets."

Done, but the compiling has automatically failed. I was wondering if there was a problem in the modified file?

**Comment by Jianing-Song** [comment]
> Aside: in R × R ordered lexicographically the subset R × 0 in not order-convex. Did you mean 0 × R ?

Yes, of course. Thanks!

**Comment by prabau** [comment]
@StevenClontz The last two commits here are failing in the "Set up job" phase:

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1.0.0`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Something needs to change on the web side?  (see link)

**Comment by Jianing-Song** [comment]
Thanks for fixing the problem :)

**Review by prabau — APPROVED** [review]

**Pull request merged**
