### PR TITLE
Sorgenfrey plane is not hereditarily separable.

### PR DESCRIPTION
**Pull request by Almanzoris**
Would it be interesting to have a property like "every discrete subspace is countable"?

Some time ago I read about such property being called countable spread.

### CODE REVIEW

**Comment by StevenClontz** [comment]
https://encyclopediaofmath.org/wiki/Spread

**Comment by Almanzoris** [comment]
Yeah, I think so too. There are several theorems that we can add with its release.

**Comment by prabau** [comment]
When you introduce "countable spread", you can introduce "countable extent" at the same time.  They are closely related.

**Comment by Almanzoris** [comment]
Alright.

**Comment by prabau** [comment]
Do we even need to mention "the standard proof that the space is not normal"?  That seems irrelevant.

**Comment by Almanzoris** [comment]
You're right.

**Comment by prabau** [comment]
Approving.  Later on, this can be replaced by a trait for countable spread.

**Review by prabau — APPROVED** [review]

**Pull request merged**
