### PR TITLE
Real numbers extended by a point with co-countable open neighborhoods has a countable k-network.

### PR DESCRIPTION
**Pull request by Almanzoris**
Has a countable $k$-network + $T_1$ doesn't imply countable pseudocharacter.

### CODE REVIEW

**Comment by prabau** [comment]
I think the justification could be a little more explicit to make it clearer.  And we should also cite https://math.stackexchange.com/questions/4972337.

Let me do a few changes and then you can comment.

**Comment by Almanzoris** [comment]
> I think the justification could be a little more explicit to make it clearer. And we should also cite https://math.stackexchange.com/questions/4972337.
> 
> Let me do a few changes and then you can comment.

Sure, I had the doubt of if we could cite it.

**Comment by prabau** [comment]
The $k$-network in the proof is $\mathcal N\cup\\{\\{\infty\\}\\}$, but the double braces look funny.  That's why I described it in words. Approving.

**Review by prabau — APPROVED** [review]

**Comment by Almanzoris** [comment]
Jajaja. I have also realized now that I didn't add the other braces.

**Pull request merged**
