### PR TITLE
Add seq. discrete+seq. compact=>finite

### PR DESCRIPTION
**Pull request by Jianing-Song**
I numbered the theorem as T203, which is the first unused number after T188 (discrete+compact=>finite). I hope this would work :)

### CODE REVIEW

**Comment by prabau** [comment]
Using previously unused theorem numbers is usually fine.

**Comment by prabau** [comment]
Good change.  This allows to derive that 5 more spaces are not sequentially discrete.

How about changing the order of the properties in the hypotheses: [seq compact + seq discrete ==> finite], as Seq compact seems the more important property of the two?

Also, we can now remove the redundant trait files for Seq discrete for S141.

**Comment by Jianing-Song** [comment]
> Good change. This allows to derive that 5 more spaces are not sequentially discrete.
> 
> How about changing the order of the properties in the hypotheses: [seq compact + seq discrete ==> finite], as Seq compact seems the more important property of the two?
> 
> Also, we can now remove the redundant trait files for Seq discrete for S141.

OK, will remove the redundant file later.
My only question is that T188 is discrete+compact => finite. Would you be OK with keeping the order of this one?

**Comment by prabau** [comment]
That brings up a good point.  It seems that with the new theorem, T188 [discrete + compact ==> finite] would become redundant, i.e., can be derived from the new result.  Should we replace T188?

@StevenClontz opinion?

**Comment by StevenClontz** [comment]
In general I don't have strong opinions on the order of properties in a theorem.

But as for T188 - it's not clear to me how proposed T203 would deprecate it, but I'm probably overlooking something simple.

**Comment by prabau** [comment]
I'll make the change and then we can see it better and discuss.

**Comment by prabau** [comment]
Replaced T188 with the @Jianing-Song 's new result and it turns out the old T188 was already redundant before.  The derivation does not make use of the new result:
https://topology.pi-base.org/spaces?q=Compact%2BDiscrete%2B%7EFinite

**Comment by StevenClontz** [comment]
Ah-ha: https://topology.pi-base.org/theorems/T000397 is a sharper result, gotcha.

**Comment by prabau** [comment]
And on the other hand, the new result cannot be derived from T397.

Is this good to go then?

**Comment by Jianing-Song** [comment]
I've removed P167 for S141.

**Review by prabau — APPROVED** [review]

**Pull request merged**
