### PR TITLE
Shrinking property

### PR DESCRIPTION
**Pull request by ccaruvana**
Edit: This addresses https://github.com/pi-base/data/issues/696.

I have added
* the properties P193 (Shrinking) and P194 (Submetacompact)
* T542 Shrinking implies Normal
* T543 Shrinking implies Countably paracompact
* T544 Metacompact implies Submetacompact
* T545 Submetacompact and Normal implies Shrinking

### CODE REVIEW

**Comment by ccaruvana** [comment]
So an example of a normal space which isn't shrinking, according to https://dantopology.wordpress.com/2017/01/05/spaces-with-shrinking-properties/, is M.E. Rudin's famous construction of a Dowker space. I'll need to look more into things for later additions, but I hope this is a decent first pass at getting the properties represented here.

**Comment by ccaruvana** [comment]
Also, for some reason, even after a few minutes after my last commit, the web viewer isn't loading a few things. I wanted to verify that I did the linking correctly.

**Comment by StevenClontz** [comment]
There's a sync button on https://topology.pi-base.org/dev that might work for you

**Comment by ccaruvana** [comment]
> There's a sync button on https://topology.pi-base.org/dev that might work for you

Yeah, I've been using that, but the newly added theorems (nor edits to the properties) haven't shown up in over 10 minutes since the commit. I'll keep trying.

**Comment by ccaruvana** [comment]
Odd. I think it must be something with my chrome browser. I pulled it up in Firefox and was able to get the new additions to load.

**Comment by prabau** [comment]
I have seen the same refresh problem on Firefox.  What seems to work though is to click on Reset (to go back to the main branch).  And then reenter the other branch.  Usually that picks up the changes.

**Comment by StevenClontz** [comment]
Just to document it somewhere, I got to a point where pi-Base was well and truly hosed on my work computer's Chrome signed into my personal account (not incognito or my work account), where even the Reset button was broken. The fix was to open the Javascript console, run `localStorage.clear()`, then refresh.

**Comment by ccaruvana** [comment]
Oh, I forgot to add in that shrinking implies countably paracompact. I'll add that in to T541 when I get a chance.

**Comment by ccaruvana** [comment]
Nice! With the updates, Rudi's Dowker Space (S138) is added to the list of spaces which are normal but not shrinking.

**Comment by ccaruvana** [comment]
Also, for future reference, do we avoid theorems of the form P implies (Q and R)? I took a glance through and didn't see any conjunctions as conclusions to any of our theorems (unless I missed them).

**Comment by prabau** [comment]
> Also, for future reference, do we avoid theorems of the form P implies (Q and R)? I took a glance through and didn't see any conjunctions as conclusions to any of our theorems (unless I missed them).

Yes, there used to be some, but we replaced them all with individual implications (P implies Q) and (P implies R).  Having the individual implications makes it easier to combine with other theorems when doing automated deductions for traits.

**Comment by prabau** [comment]
> Just to document it somewhere, I got to a point where pi-Base was well and truly hosed on my work computer's Chrome signed into my personal account (not incognito or my work account), where even the Reset button was broken. The fix was to open the Javascript console, run `localStorage.clear()`, then refresh.

@StevenClontz Does `localStorage.clear()` affect only the browser tab where the javascript is run, or does it affects all the tabs on the browser?

**Comment by StevenClontz** [comment]
> Yes, there used to be some, but we replaced them all with individual implications (P implies Q) and (P implies R). Having the individual implications makes it easier to combine with other theorems when doing automated deductions for traits.

And avoids cluttering deductions with unrelated properties (e.g. deducing P->S from P->R+T and R->S).

**Comment by StevenClontz** [comment]
> > Just to document it somewhere, I got to a point where pi-Base was well and truly hosed on my work computer's Chrome signed into my personal account (not incognito or my work account), where even the Reset button was broken. The fix was to open the Javascript console, run `localStorage.clear()`, then refresh.
> 
> @StevenClontz Does `localStorage.clear()` affect only the browser tab where the javascript is run, or does it affect all the tabs on the browser?

All tabs in the browser (unless you count using two different Google accounts in Chrome, in which case each account has its own local storage).

**Comment by prabau** [comment]
Just starting to look at this.

For P193 (shrinking), the restriction that for each $U$ in a open cover $\mathcal U$, the open set $s(U)\subseteq U$ cannot be empty seems very restrictive and annoying.

First a trivial observation:, a cover is just a collection of open sets that covers the whole space.  But nothing excludes the trivial case of having the empty set itself as a member of the cover.  Then it would be impossible to find a nonempty subset of it.

Then, by Willard 21.3 (c), every countable open cover of a normal countably paracompact space $X$ has an shrinking (is shrinkable).  In particular, any finite topological space should have the shrinking property.

But take the Sierpinski space $X=\\{0,1\\}$ with $0$ as closed point and $1$ as open point, which is normal and paracompact.  Consider the open cover $\mathcal U=\\{X,\\{1\\}\\}$. There is no nonempty closed set contained in $\\{1\\}$.  So the only way to find a shrinking would be to allow an empty subset.

So what's the advantage in forcing the subsets to be nonempty?

**Comment by ccaruvana** [comment]
@prabau I completely agree. I'm not sure why I added the non-empty condition in when I drafted this up. Adding in that restriction doesn't even align with existing definitions of _shrinking_. I must have had my brain elsewhere when I was writing that. Thanks for the catch.

**Comment by prabau** [comment]
Still taking the time to look at it.  Will have some comments soon.

**Comment by prabau** [comment]
P194: Strictly speaking, it is not said what a $\theta$-sequence of open refinements is; one has to infer it.  But one could tighten the paragraph slightly and make it clearer at the same time.  Something like this:
"Every open cover $\mathscr U$ of $X$ has a $\theta$-sequence of open refinements; that is, a sequence $\langle \mathscr V_n : n \in \omega\rangle$ of open covers where ..."

`Every open cover $\mathscr U$ of $X$ has a $\theta$-sequence of open refinements; that is, a sequence $\langle \mathscr V_n : n \in \omega\rangle$ of open covers where ...`

Would it be worth to indicate that the notion was introduced by Worrell and Wicke under the name $\theta$-_refinable_, and was later changed to _submetacompact_ by Junnila?  At the same time, we could add in the text a direct link to Junnila's article (http://topology.nipissingu.ca/tp/reprints/v03/tp03207s.pdf) since it is not directly accessible from the zbmath review.

P193: We should add "Has the shrinking property" as an alias, as it seems a common way to denote the property.  See for example pages 199 and 327 of Encyclopedia of General Topology.  Should there be a shorter description as used in Encycl. of Gen. Top.? (see also Willard 15.9)

**Comment by prabau** [comment]
T542: since the shrinking property is stronger than the normal property, wouldn't it be a strengthening instead of a generalization of it?  The argument seems pretty standard, same as one half of Willard 15.10.  I think using $\overline U$ (`$\overline U$`) instead of $\mathrm{cl}_X(U)$ would be easier to read in this case.

T543: As another complete reference we could mention if follows from Willard Theorem 21.3 (specifically the equivalence between (a) and (c)), together with the fact that shrinking spaces are normal.

**Comment by ccaruvana** [comment]
> T542: since the shrinking property is stronger than the normal property, wouldn't it be a strengthening instead of a generalization of it? The argument seems pretty standard, same as one half of Willard 15.10. I think using U ― (`$\overline U$`) instead of cl X ( U ) would be easier to read in this case.

Yes, that's right. I think I wrote "generalization" following the phrase "One of the purposes of this section is to generalize the above properties" in Yasui's article referencing the shrinking properties, though now that I look back, maybe that phrase is referring to another property that isn't the shrinking property.

> T543: As another complete reference we could mention if follows from Willard Theorem 21.3 (specifically the equivalence between (a) and (c)), together with the fact that shrinking spaces are normal.

I will make this modifications as soon as I can.

**Comment by prabau** [comment]
The `<i>` tags for italics don't seem to work in the browser, but a pair of `*` works.  Committed a change.

**Review by prabau — APPROVED** [review]

**Pull request merged**
