### PR TITLE
 Fort space on real numbers is not cozero complemented

### PR DESCRIPTION
**Pull request by Moniker1998**
#1049 @prabau

### CODE REVIEW

**Comment by prabau** [comment]
I think we should add a separate paragraph like the following at the beginning:

"Note that in any normal space the cozero sets are exactly the open $F_\sigma$-sets (Corollary 1.5.13 of {{Engelking ...}}). This is the case in $X$ since {S154|P13}."

Then the second sentence of the next paragraph can be simplified slightly:

"Then $U$ is an open $F_\sigma$-set and hence a cozero set."

And need to replace the existing ref with Engelking.

**Comment by Moniker1998** [comment]
@prabau what do you mean by {{Engelking ...}} ?

**Comment by GeoffreySangston** [comment]
@Moniker1998 I believe change {{Engelking : ...}} to {{zb:0684.54001}}. 

In github dot dev, you can use the search feature to find other examples of this usage to confirm the style is correct. I.e., type in: {{zb

**Comment by Moniker1998** [comment]
@prabau ready for review

**Review by prabau — APPROVED** [review]

**Pull request merged**
