### PR TITLE
Minor cleanup for various LOTS spaces

### PR DESCRIPTION
**Pull request by prabau**
A few cleanup items:
- add missing refs for the LOTS traits of some of the spaces; replaced Munkres with S&S for some
- remove T5 traits file for https://topology.pi-base.org/spaces/S000033
- fix definition in https://topology.pi-base.org/spaces/S000035

### CODE REVIEW

**Comment by prabau** [comment]
@StevenClontz  Since property T5 can now be deduced from LOTS, I have removed the T5 traits file for "Second limit ordinal": https://topology.pi-base.org/spaces/S000033/properties/P000008
(uncontroversial since the only justification was quoting the General Ref Chart)

I'd like to do the same with a few others like
https://topology.pi-base.org/spaces/S000033/properties/P000008
https://topology.pi-base.org/spaces/S000035/properties/P000008
etc
These do refer to something in S&S, but in each case the text in S&S only mentions that "ordered spaces are T5", and does not provide additional insight.  So would be nice to remove these files to trim down pi-base a little.

OK with you?

@keithpenrod

**Comment by keithpenrod** [comment]
Makes sense to me

**Comment by StevenClontz** [comment]
Oh yeah, with https://topology.pi-base.org/theorems/T000273 it's definitely preferable to assert LOTS vs T5.

**Review by StevenClontz — APPROVED** [review]

**Comment by prabau** [comment]
Hmm, since you already merged this, do I have to open another PR for the other files I was suggesting to remove?

**Pull request merged**
