### PR TITLE
Countable spread and countable extent

### PR DESCRIPTION
**Pull request by Almanzoris**

### CODE REVIEW

**Comment by Almanzoris** [comment]
I have just found an interesting paper that has theorems that aren't in $\pi$-Base, specially in the last 2 pages.

https://www.sciencedirect.com/science/article/pii/S0166864117300810

**Comment by StevenClontz** [comment]
I like bite-sized PRs as much as possible, so finding a logical scope for this PR and planning for a separate follow-up PR sounds great.

**Comment by Almanzoris** [comment]
The theorems involving W-spaces can be done in a different PR.

**Comment by Almanzoris** [comment]
I wasn't at the PC, but thinking about the last theorem I did, I noticed that I had misunderstood the definition of countable extent and I had defined countable spread twice. I'm sorry about that.

**Comment by prabau** [comment]
Just FYI, and sorry if it's obvious.  When the PR is in the state of Draft, that means you are planning to make more changes.  Once you are satisfied, clicking on "Ready for review" will move it to the Open state, and we'll take that as an indication to review.

**Comment by Almanzoris** [comment]
> Hi @Almanzoris. Is there anything else you want to add to this PR?

Hey @prabau. I wanted to add some theorems about cardinality bounding that I saw in that paper. But I haven't read the proofs of such in the citations.

My work is accumulating here (irl), so I have decided to add the properties to a few classic spaces to enrich them and to have counterexamples of spaces with countable extent but with uncountable spread, which I was planning to, and to limit the PR to these. Despite not being a bigger launch, this way, the workflow won't be interrupted more.

**Comment by prabau** [comment]
This is a good size PR.  More results can be added later.  We'll start reviewing.

**Comment by prabau** [comment]
For the two properties, I would rename them "Has countable spread", "Has countable extent" to match other properties like "Has multiple points", "Has a countable network", etc.  (unless @StevenClontz has other ideas?)

I think that in addition to your definitions, P196/P197 should also say what "spread" and "extent" mean in general, with references.
(maybe see https://topology.pi-base.org/properties/P000183 for comparison)

**Comment by Almanzoris** [comment]
Alright. What would the right references be?

**Comment by prabau** [comment]
Some standard references would be for example:
Hodel's chapter of Handbook of set-theoretic topology, already used for example for T405
or
Encyclopedia of General Topology, section a-3.

**Comment by Almanzoris** [comment]
After the last theorems, some of the properties had become redundant, so I have removed them.

**Comment by prabau** [comment]
Thanks to the new theorems we have two squares of implications, one from hereditarily Lindelof to countable extent and one from hereditarily separable to CCC. Nicely organized.

Minor stuff:

T276 [Hereditarily Lindelof ==> ccc] is a consequence of T560 and T564.  So one of these two theorems can instead replace T276.

T563: It's fine to start the sentence directly as "Closed sets in a Lindelöf space ..." without "Follows as".

**Comment by prabau** [comment]
- S9: can also remove P18, which is redundant
- S13: no need for P198, as we already know Lindelof = true
- S22: no need for P198, as we already know Lindelof = true
- S76: can also remove P18, which is redundant
- S154: no need for P198, as we already know Lindelof = true. Also, can remove P26=F, implied by P29=F

**Comment by Almanzoris** [comment]
I had forgotten/missed cleaning spaces after T563 [Lindelöf => Has countable extent]... It's good that you've caught those.

Should I overwrite T276 with T560?

**Comment by prabau** [comment]
Yeah, overwriting T276 with T560 sounds good.

**Review by prabau — APPROVED** [review]

**Pull request merged**
