### PR TITLE
Add diamond space

### PR DESCRIPTION
**Pull request by StevenClontz**
Answers https://topology.pi-base.org/spaces?q=Hyperconnected%2BUltraconnected%2B%7EHereditarily+connected

### CODE REVIEW

**Comment by prabau** [comment]
Hmm, you beat me to it.  The reason I added the mathse question about hyperconnected ultraconnected and not hereditarily connected was to add a theorem about biconnected and then add this space afterwards.

**Comment by prabau** [comment]
I had started a draft of the README file for the space as well.  Let me share it shortly.

**Comment by prabau** [comment]
I added an easier proof for https://math.stackexchange.com/questions/4987074

**Comment by prabau** [comment]
Here what I had for the README file for the diamond space.  (There are multiple posets called "diamond poset" in the literature, so I specified this one a little more).

`---
uid: S000144
name: Diamond poset $2\times 2$ with Alexandrov topology
aliases:
  - Four-element Boolean algebra with Alexandrov topology
refs:
  - wikipedia: Alexandrov_topology
    name: Alexandrov topology on Wikipedia
  - doi: 10.1016/j.jcta.2015.03.010
    name: Diamond-free families (Griggs, Li & Lu)
---

Let $P=(\{0,a,b,1\},\le)$ be the four-element poset with $0$ as minimum element, $1$ as maximum element, and the remaining elements $a$ and $b$ incomparable.  This poset is order-isomorphic to the Boolean algebra with four elements.  The space $X$ is $P$ with the corresponding Alexandrov topology, whose open sets are the upper sets for $\le$.

The name "diamond poset" is used for example in {{doi:10.1016/j.jcta.2015.03.010}}.
`

**Comment by prabau** [comment]
My description in the README is maybe a little easier to work with than this "upper segment diamond". I also had various properties ready to go, but was waiting to approve the theorem first.  What do you suggest to do?

**Comment by StevenClontz** [comment]
It's more your thing than mine, I won't have my feelings hurt if you make your own PR and we run with that. Feel free to use my work here or not as you see fit.

**Comment by prabau** [comment]
#815 to start with

**Pull request closed without merging**
