### PR TITLE
Add P185 Partition topology and establishing theorems

### LINKED ISSUE #574: Proposed property: partition topology
I think "partition topology" would be worth adding as a property (Steen & Seebach example 5).

Not a very important property, but it has some visual appeal and has some relationships with other properties.  See for example:
- https://math.stackexchange.com/questions/4871848/is-every-regular-alexandrov-topology-a-partition-topology
- https://math.stackexchange.com/questions/4097094/what-is-the-name-for-a-topological-space-whose-kolmogorov-quotient-is-discrete

This would also allow to deduce traits for some existing spaces like [S5](https://topology.pi-base.org/spaces/S000005), [S6](https://topology.pi-base.org/spaces/S000006), and consolidate theorems for discrete and indiscrete.

@StevenClontz, @danflapjax and others, what do you think?

### PR DESCRIPTION
**Pull request by danflapjax**
Resolves #574

This adds a new property P185 Partition topology. The alias Almost discrete is used in [Topospaces](https://math.stackexchange.com/search?q=%22almost+discrete%22) and [several MathSE questions](https://math.stackexchange.com/search?q=%22almost+discrete%22). Not included in this PR are modifications to spaces' traits, which I plan to add in another PR, or theorems involving countability axioms, of which there are many obvious ones, but I need time to untangle implication chains and determine optimal antecedents and consequents.

### CODE REVIEW

**Comment by prabau** [comment]
Topospaces cannot be considered an authoritative source, especially since it has no citations.  Note that in many papers in the literature an "almost discrete" space is one where all points except one are isolated.  Many of our spaces are actually of that kind, and one can deduce some nice easy properties out of that.  Anyway, I don't think "almost discrete" is appropriate here.  But let's see what other reviewers say.

**Comment by prabau** [comment]
T470: I like this proof.  From this, we should be able to remove T348 and T349 as redundant.

**Comment by StevenClontz** [comment]
I'd prefer to see at least one peer reviewed manuscript that uses a term before introducing it to the pi-Base.

**Comment by prabau** [comment]
What do you guys think the better name is: "partition topology" or "has a partition topology"?

**Comment by prabau** [comment]
T466: I am confused.  What do you mean by "a set of topologically indistinguishable points"?  You mean pairwise indistinguishable?  And such a set is not even closed in general (e.g. in an indiscrete space).

Since we already have the equivalent definition for P185 in terms of the Kolmogorov quotient, we could say something along these lines: (replacing some properties with appropriate links)

> Let $Y$ be the Kolmogorov quotient of $X$.  Since $X$ is R0, $Y$ is T1.  And the Kolmogorov quotient of an Alexandrov space is Alexandrov.  So $Y$ is discrete by {T267}, which is equivalent to $X$ having a partition topology.

**Comment by danflapjax** [comment]
Topological indistinguishability is an equivalence relation, and really what I meant was each of its equivalence classes.

**Comment by prabau** [comment]
T44: I think you meant to say "every closed set is open".  Also, remove the second line "Assert on Figure 9".

**Comment by danflapjax** [comment]
> T44: I think you meant to say "every closed set is open".

Either way works, actually, since open sets being closed means their closures are open.

**Comment by prabau** [comment]
> > T44: I think you meant to say "every closed set is open".
> 
> Either way works, actually, since open sets being closed means their closures are open.

Yeah, that's fine.

**Comment by prabau** [comment]
T66 [discrete ==> zero dimensional] is now redundant, since P185 implies ultraparacompact and also R0.  And then applying T464 [ultraparacompact + R0 ==> zero dim].

As an aside (irrelevant for this PR), I don't remember if we talked about that when introducing T464, but do you know any example of ultraparacompact and not zero dim (and of course without R0)?  Would be interesting to add at some point.

**Comment by prabau** [comment]
Some interesting stuff already.  Will resume tomorrow.

**Comment by danflapjax** [comment]
> As an aside (irrelevant for this PR), I don't remember if we talked about that when introducing T464, but do you know any example of ultraparacompact and not zero dim (and of course without R0)?  Would be interesting to add at some point.

The only spaces I know about are those where any open cover must include the full space $X$ as an element and sums of these. This includes the excluded point spaces.

**Comment by prabau** [comment]
@danflapjax Did you want to comment on any of the pending items above?

In particular, about the alias.  Here are a few literature references that use "almost discrete" in the sense of having exactly one nonisolated point:
- https://arxiv.org/abs/2312.10724
- https://www.sciencedirect.com/science/article/abs/pii/S0166864122001596?via%3Dihub
- https://www.sciencedirect.com/science/article/abs/pii/S0166864122001596?via%3Dihub

**Comment by danflapjax** [comment]
I don't have any strong feelings about the alias, so I'm alright with removing it.

**Comment by prabau** [comment]
> I don't have any strong feelings about the alias, so I'm alright with removing it.

Okay, I'll remove it and wrap this up.

**Review by prabau — APPROVED** [review]

**Pull request merged**
