### PR TITLE
add sufficient conditions for metacompact

### LINKED ISSUE #551: Clean up metacompact traits made redundant by T442
Observed at https://math.stackexchange.com/questions/4856141/sigma-compact-and-hausdorff-implies-paracompact

Shows https://topology.pi-base.org/spaces/?q=%24%5Csigma%24-compact%2B%24T_2%24%2B%7EMetacompact cannot have results, adds traits for e.g. https://topology.pi-base.org/spaces/S000053/

(Traits should be cleaned up)

### PR DESCRIPTION
**Pull request by StevenClontz**
Addresses #551

### CODE REVIEW

**Comment by prabau** [comment]
What is your definition of refinement?

**Comment by prabau** [comment]
What I meant is that _refinement_ is usually defined as being a covering of the space (with extra properties).  So maybe saying 

Let $\mathcal U_n$ be obtained by taking a finite subcollection of $\mathcal U$ that covers $K_n$ and intersecting with the complement of the closed set $\bigcup_{m\le n}K_m$.

**Comment by StevenClontz** [comment]
I think it's less common, but I personally prefer a refinement to not necessarily have the same union as the original. In any case I prefer to be explicit.

I agree that it's good to be explicit where KC is used.

**Comment by prabau** [comment]
Looks good.  There are some corresponding trait files that could be cleaned up.  Separate PR?

**Comment by StevenClontz** [comment]
Edited #551

**Comment by prabau** [comment]
> I think it's less common, but I personally prefer a refinement to not necessarily have the same union as the original.

I think I see now: When using the language "a refinement of $\mathcal U$ _covering a set $A$_", that implies a refinement that need not be a cover of the full space, but at least it covers a certain set $A$. That's clear.

**Review by prabau — APPROVED** [review]

**Pull request merged**
