### PR TITLE
add sequential property to arens space

### PR DESCRIPTION
**Pull request by StevenClontz**
Gives counterexample to converse of https://topology.pi-base.org/theorems/T000184

### CODE REVIEW

**Review by prabau — APPROVED** [review]
Did you mean the other answer to the mathse question, namely id 269072 instead of 269141 ?

**Comment by StevenClontz** [comment]
> Did you mean the other answer to the mathse question, namely id 269072 instead of 269141 ?

I didn't - a quick glance makes me suspect the other answer is just using a needlessly complicated characterization of the Arens space, but the answer I used cites it by name (though leaves the proof to Dan's blog post).

**Comment by prabau** [comment]
As far as I can tell, the Arens space is also hemicompact and not weakly locally compact.  Trying to find a reference for this somewhere (or we'll have to add something to mathse).

That would be a good example of https://topology.pi-base.org/spaces?q=hemicompact%2Bsequential%2B~weaklyloc, also illustrating that https://topology.pi-base.org/theorems/T000279 cannot be generalized by replacing first countable with sequential.

**Comment by prabau** [comment]
See https://math.stackexchange.com/questions/4672783/hemicompact-property-and-the-arens-space

**Pull request merged**
