### PR TITLE
add Exhaustible by Compacts + KC => Paracompact

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Refactoring PR to provide my updated answer to this in math.SE: https://topology.pi-base.org/spaces?q=Exhaustible%20by%20compacts%2BKC%2B~Paracompact

**Comment by StevenClontz** [comment]
I didn't like my direct proof for T26, and I cannot find it proven anywhere (just asserted), but with the new T427 it can be deduced from easily-found proofs.

**Comment by prabau** [comment]
The result itself looks good.

What will happen to T26?

**Comment by StevenClontz** [comment]
I'm inclined to keep T26. When I removed it, it could be deduced, but it took about ten other theorems. Given that I've recently submitted a paper for publication that links directly to pi-Base in several places, I'm also quite nervous about breaking URLs in a way I wasn't a few weeks ago. :-)

**Review by prabau — APPROVED** [review]

**Pull request merged**
