### PR TITLE
Completing S48, the cofinite topology on $\omega$ extended by a non-open generic point

### PR DESCRIPTION
**Pull request by david20000813**
As promised in https://github.com/pi-base/data/pull/1106#issuecomment-2552525690.

After lots of trials and tribulations, S48 (the space now named "cofinite topology on $\omega$ extended by a non-open generic point") finally has all its traits completed, including it now finally being known that it is a spectral space (despite being the archetypical example of a spectral space). Hooray!

On a serious note, this is a slightly large PR because I've rewritten all the traits which referenced _Counterexamples_ and the early incarnation of this space as the prime ideal topology. But all the proofs are more or less obvious, so I think it should be fine. I've also deleted all the redundant traits.

### CODE REVIEW

**Review by GeoffreySangston — APPROVED** [review]

**Comment by GeoffreySangston** [comment]
I feel pretty ashamed of myself for messing this one up so badly. I apologize for any confusion I caused. I'm grateful to David for catching my error sooner rather than later, and also for doing the task I promised I would do of switching over the language from algebra to point-set topology. I'll try to be more careful.

**Comment by GeoffreySangston** [comment]
The PR was perfectly written by the way.

**Comment by david20000813** [comment]
> The PR was perfectly written by the way.

@GeoffreySangston Thanks for the compliment!

> I feel pretty ashamed of myself for messing this one up so badly. I apologize for any confusion I caused. I'm grateful to David for catching my error sooner rather than later, and also for doing the task I promised I would do of switching over the language from algebra to point-set topology. I'll try to be more careful.

Ah, no need to apologize. And my comments about "trials and tribulations" were not meant as a criticism in any way. It was merely a joke. The entire thing about S48 has been quite confusing for everyone involved, with all the name changes and the discussion on how best to add certain traits. (I remember Noetherian being introduced partly for this.)

**Comment by prabau** [comment]
@GeoffreySangston The whole discussion was really instructive and valuable for everyone, so thanks for this.  And it allowed us converge to a good name!

**Pull request merged**
