### PR TITLE
Add Countable + T_3 => Cosmic and Cosmic => sigma-space as well as {Cosmic, sigma-space, aleph-space, aleph_0-space} => T_3

### PR DESCRIPTION
**Pull request by creator1creeper1**
We would like to deduce the properties Cosmic and $\sigma$-space in some trivial cases, so this adds the theorems Countable + T_3 => Cosmic and Cosmic => $\sigma$-space. Additionally, $T_3$ is now part of the definition of the properties Cosmic, $\sigma$-space, $\aleph$-space and $\aleph_0$-space, so this adds the corresponding theorems.

### CODE REVIEW

**Comment by prabau** [comment]
See #514, which may impact what you are doing here.

**Comment by prabau** [comment]
@creator1creeper1 Thanks for your patience.  Now that #514 has been merged, here are a few more comments.

There is a square of implications between the four properties being introduced:

- $\aleph_0$-space ==> $\aleph$-space ==> $\sigma$-space
- $\aleph_0$-space ==> cosmic ==> $\sigma$-space

These all follow directly from the definitions and should be added in this PR.

Also, as a general guideline for pi-base, we try to have a minimal set of theorems, from which other combinations can be deduced.  In this particular case, all four properties imply T3.  But we only need to have [$\sigma$-space ==> T3] and it will be automatic for the other ones as well, if this gets combined with the implications above.

Also, see Steven's comments and mine in #514, where we think it would be useful to introduce the property "Has a countable network" without T3.  We think that would allow some simpler deductions in some case.  And need to add suitable properties relating that to cosmic.

You can give it a first shot and then we can discuss further as needed.

The references now added for the four properties are where the properties were introduced and they usually contain various basic results that could be worth adding to pi-base at some point.  Let's limit the scope of this first batch, but if you have the time and inclination later on, it would be awesome if you could add a few more down the road.

**Comment by prabau** [comment]
If you want to have the change for #514 as a base for your change, I am not sure how to do that exactly.  I usually start a new branch in my local repository based on the latest main branch.  But they may be a better way.  Does that involve a "rebase"?  @jamesdabbs and @StevenClontz do you know?

The important thing is not make a mess with the commits.  The list of files to review should be just the changes needed and nothing else.  (And it does not actually matter if your branch is based on an earlier version of main.  It just could be convenient in this particular case.)

**Comment by StevenClontz** [comment]
My suggestion is to do either of the following:

1. Renumber T434 here to something new since that ID was used in another contribution. Then `git merge main` into this branch to catch it back up.
2. Make a new branch/PR from the updated `main` branch, and reimplement these changes there. I haven't read @prabau's feedback carefully, but if he's suggesting significant changes to structuring the theorems to avoid redundancy, this might be for the best anyway.

**Comment by prabau** [comment]
converted to draft for now, but I'll do a separate PR to take care of this

**Comment by StevenClontz** [comment]
Now that #571 is merged, what's the status here?

**Comment by prabau** [comment]
As explained in the description for #571, my next step was going to add traits for countable network for various spaces (so we have some good examples) and add a few more theorems involving that property (so we can deduce more cases).  Then clean up this particular PR in a separate PR after that.  That way, we'll immediately have more good examples of cosmic, etc.

But if guess, I could also clean up this particular PR first since we now have the countable network property.  That may be even better so we don't leave things hanging here. I am leaning towards this second approach after writing this.  Any preference?

**Comment by StevenClontz** [comment]
No preference on the review side, so go ahead with whatever you prefer to implement I think.

**Comment by prabau** [comment]
Closing this as it has been handled in #586.

**Pull request closed without merging**
