### PR TITLE
direct proof for t280

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
I don't follow the first part of the proof.  "there is a finite subcover": how, subcover of what?  All we know is there is some point $x$ with a nbhd that maps to a finite set.

**Comment by StevenClontz** [comment]
Oh, I see the mistake now. Will ponder this...

**Comment by StevenClontz** [comment]
This may just be broken and I'm moving on to other things, so closing.

**Comment by StevenClontz** [comment]
Thanks @prabau for the critical eye.

**Pull request closed without merging**
