### PR TITLE
Products of contractible spaces are contractible

### PR DESCRIPTION
**Pull request by GeoffreySangston**
It's unfortunate that the mathse page [The cartesian product of contractible spaces is contractible](https://math.stackexchange.com/questions/4463999/the-cartesian-product-of-contractible-spaces-is-contractible) is marked as a duplicate, because it doesn't appear to be a strict duplicate. The page it's suppose to duplicate it about a product of two spaces, and this page is about arbitrary products.

[This page at topospaces](https://topospaces.subwiki.org/wiki/Contractibility_is_product-closed) would be good, but "Fill this in later" appears at the bottom of the page.

Going to add some similar traits.

### CODE REVIEW

**Comment by prabau** [comment]
I changed the title of the mathse post to avoid the duplicate.  Hopefully enough people will vote to reopen the question.

**Comment by JoeF131** [comment]
I just wanted to add that the converse also holds. If $f: [0,1]\times \prod X_i \to \prod X_i$ is a contraction map of $\prod X_i$ and $p_n: \prod X_i \to X_n$ are the projection maps, then $p_n\circ f\restriction_{[0,1]\times X_n}$ is a contraction map of $X_n$.

I could find a stackexchange post about this though.

**Comment by JoeF131** [comment]
I just wanted to add that the converse also holds. If $f: [0,1]\times\prod X_i\to \prod X_i$ is a contraction map, $p_n: \prod X_i\to X_n$ is the projection and $i_n: X_n \to\prod X_i$ is an inclusion with $p_n\circ i_n = \text{id}$, then $p_n\circ f \circ (\text{id} \times i_n)$ is a contraction map of $X_n$.

**Comment by StevenClontz** [comment]
@JoeF131 if you like, you could add this observation as a supplementary answer to https://math.stackexchange.com/questions/4463999/an-arbitrary-product-of-contractible-spaces-is-contractible or ask/answer the question there. Your proof would be more discoverable on the Stack Exchange network than a pi-Base PR that will be closed in a few days.

**Comment by prabau** [comment]
This looks good.  As a consequence of these, one could remove a few redundant traits.

Just as an example, now that we know the Hilbert cube is contractible, it is path connected.  And since it's also Hausdorff (via metrizable), it is necessarily arc connected.  Also we can probably remove the trait for indiscrete.

Not sure if we want to do this associated cleanup here or not.  In the mean time, I'll approve and leave the rest to you, including the squash and merge.

**Review by prabau — APPROVED** [review]

**Pull request merged**
