### PR TITLE
Loc compact T2 with countable network are 2nd countable

### PR DESCRIPTION
**Pull request by prabau**
New theorem: Countable network + weakly locally compact + T2 ==> second countable.

### CODE REVIEW

**Comment by prabau** [comment]
> I have read (theorem 2 in [this post](https://dantopology.wordpress.com/2009/11/16/network-weight-of-topological-spaces-i)) that if a space X is locally compact, then n w ( X ) = w ( X ) . Maybe we could add it too.
> 
> [Locally compact+Has a countable network+~Second countable](https://topology.pi-base.org/spaces?q=Locally+compact%2BHas+a+countable+network%2B%7ESecond+countable)
> 
> [Weakly locally compact+Has a countable network+~Second countable](https://topology.pi-base.org/spaces?q=Weakly+locally+compact%2BHas+a+countable+network%2B%7ESecond+countable)

Engelking assume Hausdorff.  Dan Ma often assumes Hausdorff as well.  Are you saying that Theorem 2 in Dan Ma's blog is proved with locally compact without Hausdorff?  (That would indeed be a strengthening of the result.)

**Comment by Almanzoris** [comment]
> > I have read (theorem 2 in [this post](https://dantopology.wordpress.com/2009/11/16/network-weight-of-topological-spaces-i)) that if a space X is locally compact, then n w ( X ) = w ( X ) . Maybe we could add it too.
> > [Locally compact+Has a countable network+~Second countable](https://topology.pi-base.org/spaces?q=Locally+compact%2BHas+a+countable+network%2B%7ESecond+countable)
> > [Weakly locally compact+Has a countable network+~Second countable](https://topology.pi-base.org/spaces?q=Weakly+locally+compact%2BHas+a+countable+network%2B%7ESecond+countable)
> 
> Engelking assume Hausdorff. Dan Ma often assumes Hausdorff as well. Are you saying that Theorem 2 in Dan Ma's blog is proved with locally compact without Hausdorff? (That would indeed be a strengthening of the result.)

Hmm... Now, I am unsure.

**Comment by prabau** [comment]
The proofs in the two references make essential use of the Hausdorff condition.  So we should check in detail what the proof from Dan Ma's blog assumes.

**Comment by Almanzoris** [comment]
> The proofs in the two references make essential use of the Hausdorff condition. So we should check in detail what the proof from Dan Ma's blog assumes.

The proof of claim 3 cites a result from the previous post, where he mentions that the spaces are $T_2$. Also, reading how he was using locally compactness, it seems that he was using it as weakly locally compactness instead (anyways weakly locally compact + $T_2$ implies locally compact), which would be this PR already.

**Comment by Almanzoris** [comment]
Coincidently, in that previous post, he also mentions a result (Compact + $T_2$ + Has a countable network $\Rightarrow$ metrizable) that wasn't in $\pi$-Base before, but it is deduced with the theorem T534 now.

**Comment by prabau** [comment]
> > The proofs in the two references make essential use of the Hausdorff condition. So we should check in detail what the proof from Dan Ma's blog assumes.
> 
> I think that he assumes the Hausdorff condition. The proof of claim 3 cites a result from the previous post, where **he mentions that the spaces are T 2 ** (he actually mentions T 3 , but T 2 compact spaces are T 3 ). Also, reading how he was using locally compactness, it seems that he was using it as weakly locally compactness instead (anyways weakly locally compact + T 2 implies locally compact), which would be this PR already.

Actually he uses the Hausdorff condition in an essential way in the proof of Lemma 1 of the previous post, to show item 5 (compact Hausdorff spaces have the same network weight and weight).  That's basically the same proof as in the refs from this PR.

**Comment by Almanzoris** [comment]
Yeah. By the way, I apologize for my previous misinformation.

**Comment by prabau** [comment]
Please, no need to apologize for anything.  We are all learning here and these discussions are very useful to explore variations and improvements, and to clear misunderstandings and reinforce concepts, for all of us!

**Comment by Almanzoris** [comment]
Thank you so much. Wise words, Patrick.

**Comment by StevenClontz** [comment]
Noting examples at https://topology.pi-base.org/spaces?q=weakly+Locally+compact%2BHas+a+countable+network%2B%7ESecond+countable and (currently) empty search at https://topology.pi-base.org/spaces?q=T_2%2Bweakly+Locally+compact%2BHas+a+countable+network%2B%7ESecond+countable

**Review by StevenClontz — APPROVED** [review]

**Pull request merged**
