### PR TITLE
S131 removal

### PR DESCRIPTION
**Pull request by prabau**
pi-base is meant to model topological properties and not metric properties.  Space S101 (Sierpinski's metric space) is homeomorphic to S2 (discrete countable space), so we can eliminate it and merge it into S2.  At the same time, S2 was missing a few things (like the property of being discrete, which was causing it to miss a bunch of other deduced properties), so took the opportunity to add it and clean up a few things, and also cleaned up the other discrete spaces S1 (finite) and S3 (uncountable) to make them all more similar to each other.

Some more details:
- S1: removed the compact property (P16), since it can be deduced from "finite" (P72) via T198, and moved the explanatory text to T198 (it's obvious, but just in case someone wanted to see it).
- all/P24 (locally relatively compact): rephrased the text and removed the old terminology of "strongly relatively compact".
- all/P42 (locally path connected): removed.  It's already deducible from "discrete" via "locally arc connected" (T84 already has full explanation quoting Steen & Seebach).
- S2/P17 (sigma-compact): removed, as it is a trivial consequence of "countable".
- S2/P52 (discrete): added.

### CODE REVIEW

**Comment by ccaruvana** [comment]
Would we not need to add the "Sierpinski's metric space" as an alias to the countable discrete space and perhaps a note regarding the metric there along with the Steen/Seebach reference? I suggest this mainly thinking about anyone who might visit and search specifically for Sierpinski's metric space (general encyclopedic record keeping). Merging the spaces is clearly in line with the "spaces separate up to homeomorphism" philosophy but I'm unsure as to the desired level of specificity.

**Comment by StevenClontz** [comment]
Haven't look at this closely, but yes, I previously merged BaireSpace/Irrationals, and added Baire Space as an alias (or vice versa). This is my understanding of what @jamesdabbs had in mind for the database (to track things up to homeomorphsim) but it's good to get his input here. (Deleting a space breaks URLs, so I probably should have been less cavalier in doing so previously. But I don't like having unnecessary redundancy in having to manually sync two homeomorphic copies of the same space.)

**Comment by prabau** [comment]
Steen & Seebach space 135 (p. 152) is specifically written in terms of a metric space and not in terms of a topological space.  It mentions in item 1 that the space has the discrete topology, and the other two items focus on some specific properties of the metric.  So anyone who reads it will realize it's the same as a discrete space, and that was my thinking for not adding it as an alias.  (It's really not a topological space.)  But if you want to add a note in the text of the README file for space S2 mentioning the relation with S&S space 135, that should be fine.

**Comment by StevenClontz** [comment]
I think the use case of "hey I see Sierpinski's metric space is in *Counterexamples*, let me search to find it on pi-Base" is sufficient to include it as an alias. We want to make those words searchable. And we certainly should make sure both references to Counterexamples 2 and 135 are maintained.

**Comment by StevenClontz** [comment]
Re-pinging @jamesdabbs on the issue of breaking URLs. I can't imagine https://topology.pi-base.org/spaces/S000131 is well-cited (me breaking the old Baire space URL was probably a worse sin).

**Comment by prabau** [comment]
@StevenClontz Okay about the alias.  Can you add it directly in a commit to this PR?

**Comment by prabau** [comment]
I have added to my branch Sierpinski's metric space as an alias with some verbiage.  It seems that shows up immediately in the diff here.  Please check if that looks ok.

As for breaking links, I don't think that's a very big deal.  Like you said, probably few places ever referenced the Sierpinski metric in pi-base.  And if something breaks, people can change their links.  But that's just my opinion.

**Review by StevenClontz — APPROVED** [review]
I don't want this to get too stale so I'm approving. We can always add S131 (and the Baire space) back later for legacy purposes if we think it's necessary, or add redirects somehow.

**Pull request merged**
