### PR TITLE
Extremally disconnected: remove T2 assumption

### PR DESCRIPTION
**Pull request by prabau**
Remove T2 assumption from P49.

As discussed in https://github.com/pi-base/data/pull/357#issuecomment-1646738969.

### CODE REVIEW

**Comment by StevenClontz** [comment]
The proof of https://topology.pi-base.org/theorems/T000045 uses the assumption that these spaces are T2. I thought about it a bit and it seems to be pretty necessary: https://math.stackexchange.com/questions/4742443

In particular, without $T_2$ this isn't really a "disconnected" property. So I'm of the opinion that a better move would be to add a separate property "Closures are open" that when paired with $T_2$ is equivalent to "extremally disconnected".

**Comment by prabau** [comment]
Yeah, I had not checked the theorems.  You are absolutely right that T45 would need the Hausdorff assumption.  And it's hard to argue that something like an indiscrete space or other connected space examples that you mention in mathse are some form of "disconnected".

On the other hand, at least three respectable sources don't make the Hausdorff assumption in the definition: Willard, Gillman & Jerison, Anhangelskii & Ponomarev.  

Engelking includes Hausdorff, but he includes Hausdorff in all kinds of other things as well (regular, normal, compact, zero-dim, etc, etc), just for convenience, so that does not say much.

Encyclopedia of General Topology (Hart, Nagata, Vaughan):
https://books.google.com/books?id=JWyoCRkLFAkC&printsec=frontcover&dq=Encyclopedia+of+general+topology&hl=en&newbks=1&newbks_redir=0&sa=X&ved=2ahUKEwjb3vPL46qAAxXRF1kFHZaKA1wQuwV6BAgGEAk#v=onepage&q=extremally%20disconnected&f=false
has some mentions without extra condition (e.g., p. 225 in the "Connectedness" section), and some mentions with extra conditions. For example the main section about "Extremally disconnected spaces" (p. 345) assumes regular (but not T2) (unless regular = T3, not sure).

It seems a little redundant to have to introduce "Closure of open is open" as a property nearly synonymous with "extremally disconnected" in most cases of interest.  I agree it may sound weird that a space can at the same time be extremally disconnected and connected for example. But what about compact and anticompact at the same time?  One can get used to it.

What's the most commonly used definition in papers?
I'd be curious to know others' opinion (@ccaruvana, @lyengulalp, ...).

**Comment by StevenClontz** [comment]
I haven't studied P49 myself. Though with a bit of further thought, as long as I parse its name correctly ("extrem**ally** disconnected", not "exterm**ely** disconected"), I think I can handle a P49 space that's also connected.

So instead, I think I'd approve this PR once we update T45 to add the Hausdorff requirement.

> For example the main section about "Extremally disconnected spaces" (p. 345) assumes regular (but not T2) (unless regular = T3, not sure).

My guess is they mean $T_3$ (they say "mainly Tychonoff spaces are discussed here").

**Comment by prabau** [comment]
See https://mathoverflow.net/questions/431616/extremely-disconnected-or-extremally-disconnected in this respect.

Without Hausdorff, [hyperconnected  ==> extremally disconnected], which again sounds weird (see https://math.stackexchange.com/questions/4742443).  But maybe ok.

Before you approve, can we get Chris or Lynne's opinion also?

**Comment by StevenClontz** [comment]
Sure. You could add those theorems from https://mathoverflow.net/questions/431616/extremely-disconnected-or-extremally-disconnected which will help complete the non-Hausdorff examples as well.

**Comment by ccaruvana** [comment]
As far as I recall, I've seen the notion "extremally disconnected" exactly once. In that source, the detail they used was that the collection of semi-open subsets of an extremally disconnected space forms a topology. The authors did not assume any separation axioms in their discussion (see the first sentence of Preliminaries and Lemma 4.22 of http://bims.iranjournals.ir/article_1078_9fad6d520d7acfc75e636817ab29dff9.pdf) - though they use "extremely disconnected" without defining the term, I'm quite sure they mean "extremally disconnected."

This is only one example, however, and the paper they cite where it is shown that SO(X) is a topology iff X is extremally disconnected does not seem to be easily accessible online. So I'm not sure I can comment on what is most standard, but it may suggest that at least some circle of mathematicians working with the notion don't require separation axiom assumptions (along with the important examples pointed out by @prabau already).

**Comment by prabau** [comment]
Thanks for the reference.  So it seems it's more general and not a bad idea to not have Hausdorff as part of the definition.  Feel free to approve if you don't have other objections.

**Review by StevenClontz — APPROVED** [review]
@prabau If you're fine with [4fe4261](https://github.com/pi-base/data/pull/362/commits/4fe4261cda4e56a1b0801ecec4988ee91935db13) then this is ready to merge.

**Comment by prabau** [comment]
> @prabau If you're fine with [4fe4261](https://github.com/pi-base/data/pull/362/commits/4fe4261cda4e56a1b0801ecec4988ee91935db13) then this is ready to merge.

Looks good.  Please approve.

**Pull request merged**
