### PR TITLE
T_6: T_0 and Perfectly normal.

### PR DESCRIPTION
**Pull request by Almanzoris**
A space is T_1 if, and only if, it is T_0 and R_0. And every Perfectly normal space is R_0.

Therefore, it is sufficient to define a T_6 space as a space that is both T_0 and Perfectly normal instead of as T_1 and Perfectly normal.

### CODE REVIEW

**Comment by StevenClontz** [comment]
Related: #677

**Comment by StevenClontz** [comment]
My understanding of @prabau's suggestion is not to change the theorems in pi-Base (which I'm always hesitant to tweak unless the change somehow improves our search results), but to note in the description of https://topology.pi-base.org/properties/P000067 that $T_0$ and $T_1$ are both equivalent requirements for a perfectly normal space to be $T_6$.

But it's reasonable to take this moment to consider how to align all our separation properites. For example, we define $T_3$ to be [regular plus *Hausdorff*](https://topology.pi-base.org/properties/P000005), not even $T_1$! Since the "obvious" connection that makes normal imply regular is to let points be closed ($T_1$), should we be consistent with our $T_n$ separation axioms and define them all as property + $T_1$, noting where we can when this can be reduced to $T_0$? Or we could define them all as property + $T_2$, then note when $T_2$ can be weakened to $T_1$ or $T_0$?

**Comment by prabau** [comment]
I agree with Steven.  This is the wrong approach.

As discussed in #677, defining T6 as the combination of T1 and perfectly normal is a "perfectly good" definition.  It is a better definition than the combination of T0 + perfectly normal, as it is a more common one used in various source, and easy to check a well.  Equally good would be the combination of T2 + perfectly normal.  T0 + perfectly normal is equivalent to that, but not as commonly used.  We can mention is in P000067.md as an equivalent condition, but *not* as the primary definition.

And as already discussed, pi-base already knows the equivalence of T0 + perf normal with the current definition.  No need to mess around with any theorems.

**Comment by prabau** [comment]
General comment: In mathematics in general, the purpose of a definition is to introduce new terminology (here $T_6$) for a concept, in an unambiguous way and as simply as possible.  The current definition does this already.  Sometimes there are several equivalent characterizations, but some of them are better viewed as theorems rather than definitions.  In this case [T0 + perfectly normal = T6] feel a little bit like a theorem, but I think it's ok to mention both in P000067.md.  It's all pretty simple anyway.

**Comment by prabau** [comment]
> But it's reasonable to take this moment to consider how to align all our separation properites. ...

I think that merits a broader discussion better left out of this particular PR.  But agree that we should discuss this.

**Comment by Almanzoris** [comment]
You are right. I am sorry about my misunderstanding.

I have reverted the changes and I have added the equivalence in the property file.

**Review by StevenClontz — APPROVED** [review]

**Comment by StevenClontz** [comment]
Thanks for your contribution @Almanzoris!

I'm inviting you to have write permissions so you can make branches directly on this repo in the future. This will trigger our automatic process of compiling the contribution and checking it for contradictions. Then once those pass, you can enter the branch name at https://topology.pi-base.org/dev to preview your changes on the live website.

**Comment by Almanzoris** [comment]
You're welcome. And, alright! Thank you very much for your kindness.

**Comment by prabau** [comment]
@StevenClontz Below is now the result of `git log` on the command line.  Notice how the text for the first commit is pretty ridiculous, compared with the later commits.  That's why I really think it's usually a good idea to wipe out the useless list of intermediate commits when doing the "squash and merge" step.  My 2c.

----
commit 71ac429dcb8aa70d5784ba1305cb1047034b96fb
Author: Alman <149833592+Almanzoris@users.noreply.github.com>
Date:   Sat Jun 29 20:26:08 2024 +0200

    T_6: T_0 and Perfectly normal. (#678)

    * T_6: T_0 and Perfectly normal.

    A space is T_1 if, and only if, it is T_0 and R_0. And every Perfectly normal space is R_0.

    Therefore, it is sufficient to define a T_6 space as a space that is both T_0 and Perfectly normal instead of as T_1 and Perfectly normal.

    * T_6: T_0 and Perfectly normal.

    * T_6: T_0 and Perfectly normal.

    * Reverting Change.

    * Reverting Change.

    * Revert + Equivalence addition.

commit d605409468a821f8a2eeca4d08a876e0492ccf3c
Author: Patrick Rabau <70125716+prabau@users.noreply.github.com>
Date:   Sat Jun 22 18:08:55 2024 -0400

    Aleph spaces and Lindelof property (#674)

commit f4f9d05cf3060b97306e269f02479921c1549bbd
Author: Steven Clontz <steven.clontz@gmail.com>
...

**Pull request merged**
