### PR TITLE
Two more generic point theorems

### PR DESCRIPTION
**Pull request by danflapjax**
I replaced the existing T592, as it was redundant.

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
How about 'Has a generic point + Has closed retracts (P101) + ~empty => ~has multiple points'?

**Comment by danflapjax** [comment]
That's already known to hold, as 'has closed retracts' implies R0:
> [π-Base, Search for `Has a generic point + Has closed retracts + Has multiple points`](https://topology.pi-base.org/spaces?q=Has+a+generic+point+%2B+Has+closed+retracts+%2B+Has+multiple+points)

**Comment by GeoffreySangston** [comment]
> That's already known to hold, as 'has closed retracts' implies T1: [π-Base, Search for `Has a generic point + Has closed retracts + Has multiple points`](https://topology.pi-base.org/spaces?q=Has+a+generic+point+%2B+Has+closed+retracts+%2B+Has+multiple+points)

Ah. My mistake.

**Comment by prabau** [comment]
Nice consequence: From T597 we can derive that S199 (Left ray topology on $\omega$) has a generic point.

**Comment by prabau** [comment]
I am wondering about the relationship between T594 and T597.  Is one somehow stronger than the other?

T597 does not imply T594.  One can have a space that is hyperconnected with an isolated point, but is not quasi-sober.  For example, some appropriate variant of right ray topology on $\omega+1$ to make $\omega$ an isolated point (so that the space is also Alexandrov, taking the intervals $[x,\to)$ as a base for the topology).  Would be good to add this space to pi-base in a separate PR.

On the other hand, T594 does not imply T597 without assuming T0 (because we can always replace an isolated point with two topologically indistinguishable points and keep the same properties).  But even if we assume T0, it's not completely clear?

Check me on the following observations:
- Has a generic point + T0 ==> the generic point is unique.
- Has a generic point + T0 + Alexandrov ==> the generic point is an isolated point

Without Alexandrov, this may not be true, I think.
Example: Right ray topology on the reals with an extra maximum point added.  Same as $X=[0,1]$ with the intervals $(x,\to)$ forming a base for the topology.

Note that the last example is not sober (and not quasi-sober), as the subspace $Y=[0,1)$ is irreducible without generic point.

Given a nonempty hyperconnected sober space, it has a unique generic point.  Is that point isolated in general?

Comments?

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/4994238/is-the-generic-point-of-an-irreducible-sober-topological-space-an-isolated-point

**Comment by StevenClontz** [comment]
> That's already known to hold, as 'has closed retracts' implies T1: [π-Base, Search for `Has a generic point + Has closed retracts + Has multiple points`](https://topology.pi-base.org/spaces?q=Has+a+generic+point+%2B+Has+closed+retracts+%2B+Has+multiple+points)

If this was in response to someone's now-deleted comment, I'd say to them: don't feel like you need to delete things based on an oversight. I say enough dumb things on the internet to outweigh any of us; better to keep the discussion history alive. ♥

**Comment by StevenClontz** [comment]
> https://math.stackexchange.com/questions/4994238/is-the-generic-point-of-an-irreducible-sober-topological-space-an-isolated-point

@Almanzoris has a nice answer!

**Comment by prabau** [comment]
Yeah, nice answer @Almanzoris.  So there are two variants of right ray topology on $\omega+1$, one taking as a base all intervals $[x,\to)$ (giving an Alexandrov topology with an isolated generic point) and one taking as a base all intervals $(x,\to)$, which has a non-isolated generic point.  Both topologies are sober.
I'll try to add a community wiki answer to the mathse post giving some details for the general construction.

**Comment by prabau** [comment]
So for the purpose of this PR, we could add the following result, which seems to be independent of the other theorems:
[Has generic point + T0 + Alexandrov ==> Has isolated point]

@danflapjax Is that something you can add to the PR, or should it be done separately?

**Comment by Almanzoris** [comment]
Thanks!

I was unaware about the on-going discussion here. But, I saw the question in mathse and I came up with something to "attack" it with.

**Comment by Almanzoris** [comment]
> I am wondering about the relationship between T594 and T597. Is one somehow stronger than the other?
> 
> T597 does not imply T594. One can have a space that is hyperconnected with an isolated point, but is not quasi-sober. For example, some appropriate variant of right ray topology on ω + 1 to make ω an isolated point (so that the space is also Alexandrov, taking the intervals [ x , → ) as a base for the topology). Would be good to add this space to pi-base in a separate PR.
> 
> On the other hand, T594 does not imply T597 without assuming T0 (because we can always replace an isolated point with two topologically indistinguishable points and keep the same properties). But even if we assume T0, it's not completely clear?
> 
> Check me on the following observations:
> 
> * Has a generic point + T0 ==> the generic point is unique.
> * Has a generic point + T0 + Alexandrov ==> the generic point is an isolated point
> 
> Without Alexandrov, this may not be true, I think. Example: Right ray topology on the reals with an extra maximum point added. Same as X = [ 0 , 1 ] with the intervals ( x , → ) forming a base for the topology.
> 
> Note that the last example is not sober (and not quasi-sober), as the subspace Y = [ 0 , 1 ) is irreducible without generic point.
> 
> Given a nonempty hyperconnected sober space, it has a unique generic point. Is that point isolated in general? Maybe a good question for mathse.
> 
> Comments?

If I have understood the notation correctly, in the last example, $Y$ is irreducible and doesn't have a generic point, but $1$ is not isolated in $X$, i.e., $Y$ is not closed. And, the sober property is related to the irreducible closed sets.

The non-empty proper closed subsets of $X$ are of the form $[0, x]$, with $0 \leq x < 1$. Which are hyperconnected and have a generic point, the right extreme $x$.

Right?

**Comment by prabau** [comment]
Yeah, I think I messed this up.  Like you said, the set $Y$ is irreducible but not closed in $X$.  So it's irrelevant to check if $X$ is sober or not.  I agree that $X$ is sober.

**Comment by Almanzoris** [comment]
> Yeah, I think I messed this up. Like you said, the set Y is irreducible but not closed in X . So it's irrelevant to check if X is sober or not. I agree that X is sober.

It happened to me too when making the answer jajaja. I had thought of the example that I posted and of [0, 1] with the topology generated by $(\leftarrow, x)$, analogous to this one. The missconception was messing me up, but I rechecked the definition and, fortunately, I noticed it.

**Comment by prabau** [comment]
@danflapjax I'll approve this PR and add the extra theorem separately.

**Review by prabau — APPROVED** [review]

**Comment by prabau** [comment]
@Almanzoris Good last observation.

Regarding resources for ordinal spaces, there are lots of them on the internet.  One of them I looked at is Monk's "Notes on set theory" at https://math.colorado.edu/~monkd/.  I don't know anything specific for ordinal spaces.

**Comment by Almanzoris** [comment]
> @Almanzoris Good last observation.

@prabau Thanks!

> Regarding resources for ordinal spaces, there are lots of them on the internet. One of them I looked at is Monk's "Notes on set theory" at https://math.colorado.edu/~monkd/. I don't know anything specific for ordinal spaces.

Alright! Thanks again, I have downloaded the pdf.

**Pull request merged**
