### PR TITLE
S17: anticompact and cleanup

### PR DESCRIPTION
**Pull request by prabau**

### CODE REVIEW

**Comment by prabau** [comment]
Hmm, I am trying to follow the example of creating a branch in the pi-base/data repo itself (not the branch prabau:S17-anticompact above, which did not do anything).  So I created branch S17-anticompact in the official repo itself.  And then I guess I have to edit directly from the github web interface, right?

So I added a trait saying that S17 is anticompact, and now I want to remove redundant traits.  But it seems every single little change, every file delete or file add needs to be a separate commit. That's really annoying, ends up getting zillions of little commits.  Is that your experience too, or is there a better way?

And separately, if I already have a branch in my own repo as part of a PR (e.g. prabau:S17-anticompact), is there a way to somehow copy the contents into a test branch in the official repo without having to manually redo all the changes?

**Comment by prabau** [comment]
Found out I can do the changes in a local test branch on my computer and push that test branch directly to the repo.  That way I can commit changes to multiple files at the same time.  Not that bad.

Still would be curious to know how you do it.

**Comment by prabau** [comment]
Closing this, and redoing in #206.

**Comment by StevenClontz** [comment]
> Still would be curious to know how you do it.

Press `.` when not using a textbook, or change `.com` to `.dev` in the URL, and you'll pull us a VS Code that lets you create new branches on GitHub and commit to them directly.

Alternately, open a [Codespace](https://github.com/features/codespaces) and you'll get a VS Code with a full VM in your browser, but you'll need to push/pull to the repo just like you're using your own computer.

TBH finding these workflows is part of why I'm more active in the past few weeks. I need to write up a tutorial.

**Pull request closed without merging**
