### PR TITLE
Finishing up P107 (has a closed point), S46, S47

### PR DESCRIPTION
**Pull request by yhx-12243**
Continuing #991.

### CODE REVIEW

**Comment by prabau** [comment]
Thank you! Sorry for the trouble, but that helps.

**Comment by david20000813** [comment]
S45, S47, and S48 having closed points would all be automatically deduced from the proposed generalization of T641 in #1002. We also need to add in the citation for the arc connected stuff. Other than those two points, I think everything looks fine.

**Comment by prabau** [comment]
@yhx-12243 The circular argument is still there.  Please fix it as suggested in #991.

**Comment by prabau** [comment]
invalid metadata: `- name:`

**Comment by prabau** [comment]
I rearranged the proofs slightly.  Please take a look.

**Review by prabau — APPROVED** [review]

**Pull request merged**
