### PR TITLE
add metrizability of S121

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
This will be easier to deduce once we have the property "embeddable in Euclidean space".

@danflapjax Can you tell us your plans regarding #565?

**Comment by danflapjax** [comment]
Here's a link to my work in progress on the property: https://github.com/danflapjax/pibase-data/tree/euclidean-subspace

I just need to finish a couple explanations, then I'll submit a PR. I expect to do so tomorrow.

**Comment by StevenClontz** [comment]
Also I just added @danflapjax as a collaborator on this repo, so in the future feel free to hack on a branch here directly and make a draft PR for discussion as soon as you like. Working on a branch on the repo itself means we can all preview it on topology.pi-base.org

**Comment by prabau** [comment]
With the release of #603, S121 now has second countable and metrizable deduced automatically.

**Comment by StevenClontz** [comment]
So now just the update to the space's readme is relevant. Easier to make a clean PR for that, so closing.

**Pull request closed without merging**
