### PR TITLE
Improve S44 description, add utility spaces S199 and S200

### PR DESCRIPTION
**Pull request by StevenClontz**
Addresses #787

### CODE REVIEW

**Comment by prabau** [comment]
S44: $U_n = (0,1-\frac{1}{n})$ seemed easier to grasp than $U_n = (0,\frac{n-1}{n})$, easier to see that the right endpoints converge to $1$.  Also, why talk about basic sets for a topology, which would make the reader pause to figure out what the topology actually is?  We can give the full topology directly, namely, all the sets $U_n$, together with $X$.

Actually, same comment for the two other spaces.  We can give the topology directly.

We can also add Alexandrov to all three spaces, which is pretty obvious and implies a bunch of other properties.

**Comment by prabau** [comment]
S199 (left ray topology) - P40: Is that true that $0$ is contained in the closure of every nonempty set?
Maybe a better reason is that all the closed sets form a chain under inclusion. (same as for the open sets)

**Comment by StevenClontz** [comment]
> S44: $U_n = (0,1-\frac{1}{n})$ seemed easier to grasp than $U_n = (0,\frac{n-1}{n})$, easier to see that the right endpoints converge to $1$.  Also, why talk about basic sets for a topology, which would make the reader pause to figure out what the topology actually is?  We can give the full topology directly, namely, all the sets $U_n$, together with $X$.

I actually parse $\frac{n-1}{n}$ better (I kept misreading the original description as sets $(0,\frac{1}{n})$). I'll take another look and think about it.

**Comment by StevenClontz** [comment]
Thanks @prabau - I think I've addressed your feedback.

**Comment by prabau** [comment]
The description for S44 is now completely clear, but on the web page the display of the topology was jarringly big and seemed disconnected from the sentence.  I tweaked it, but if you don't like it, we can revert.

**Comment by StevenClontz** [comment]
Fine with me. Ready for approval and merge unless there's any concerns you have.

**Comment by prabau** [comment]
S099, S200: I like the justification for completely normal in terms of the topology/closed sets forming a chain.

The topology for S200 (right ray topology) is presented in terms of "closed" rays $[n,\rightarrow)$, which makes the justification for T0 and Alexandrov very clear.  Similarly, I think it would be clearer to present the open sets of S199 in terms of left rays of the form $(\leftarrow,n]$ and then tweak the traits for T0 and Alexandrov.

The T0 trait for S200 is not quite right ($m$ and $n$ mixed up).  Should be:
> Given $m<n$, $[n,\rightarrow)$ is a neighborhood of $n$ missing $m$.

Should there be traits for homogeneous, or better left for another PR?

**Comment by StevenClontz** [comment]
Inspiration was #787 so I should add homogeneous traits. Update incoming.

**Comment by StevenClontz** [comment]
Updates completed.

**Comment by StevenClontz** [comment]
Note: I think the "canonical" definition for a ray topology should be "open" rays to match with https://topology.pi-base.org/spaces/S000042, though in this case this coincides with the closed rays. Could also definite topologies of "rightward" or "leftward" sets, which is distinct in general.

**Comment by prabau** [comment]
S199/S200: Nitpicking here. If you want to have the topologies both in terms of open rays and closed rays, it's fine.  But is some of the duplication here really necessary?  For S199, the empty set is already the same as $(\leftarrow, 0)$. And for S200, the whole set is already the same as $[0,\rightarrow)$.

S199|P86 (homogeneous): I watched the video of your interesting colloquium talk.  Like you said multiple times, Lean would not let us get away with things.  In this case, it would complain about this:
> $0$ belongs to every open set.

**Review by prabau — APPROVED** [review]

**Pull request merged**
