### PR TITLE
The property "Has no nontrivial countable partition by closed sets"

### LINKED ISSUE #593: The property "cannot be written as a countable disjoint union of closed subsets with at least two being nonempty"
The property "if $X=\displaystyle\bigcup_{n\in\mathbb{N}} C_n$ with $(C_n)$ being a countable disjoint family of closed subsets, then one of $C_n$ is $X$ and the others are empty" is quite interesting. Equivalently, this property can be stated as "every continuous map from $X$ to $\mathbb{N}$ equipped with the cofinite topology is constant". The property is stronger than connectedness.

We then have the theorems:
(i) compact + connected + Hausdorff $\Rightarrow$ this property (see https://math.stackexchange.com/q/6314);
(ii) locally compact + connected + locally connected + Hausdorff $\Rightarrow$ this property (see https://doi.org/10.4153/CMB-1973-069-1).

### PR DESCRIPTION
**Pull request by Jianing-Song**
Closes #593

### CODE REVIEW

**Comment by StevenClontz** [comment]
I've copied https://github.com/pi-base/data/pull/610/commits/70d680f5df10a74e43d5f8ea342eca0933b79a66 to branch `PR610`, so you can preview it by going to https://topology.pi-base.org/dev and replacing `main` with `PR610`.

**Comment by prabau** [comment]
Just curious.  What editor did you use for this?  Did you use github.dev (= vscode) or something else?

(not sure if you used git before, but in github.dev at least, there is no need to have a separate commit for every little change to every file.  You can accumulate multiple changes in multiple files and then do a single commit for that.  Makes it more manageable, I think.)

**Comment by StevenClontz** [comment]
There's a way to edit files directly in GitHub.com that results in these single file commits. I also agree that GitHub.dev is a nicer workflow. https://github.com/pi-base/data/wiki/Contributing#make-a-pull-request

**Comment by prabau** [comment]
Here is another result that you could add in the same PR, as it's pretty simple:

[countable + T1 + multiple points ==> ~ has no nontrivial countable partition ...]

As you can see from the pi-base Explore page when looking at the PR610 branch, this will allow to automatically deduce that the property P186 is not true for 12 more spaces.  (if that's not clear, we'll give you more tips on how to see that)

**Comment by prabau** [comment]
T473: I can see that the referenced paper claims this in its first paragraph, but without justification.

If $X$ is connected locally compact Hausdorff, its one point compactification will be a continuum, hence have the property.  But as the example in Fig 1 of the paper shows, it's not enough to conclude the property for $X$ itself.  Apparently, adding locally connected would be enough.  That's not obvious to me.  Is it clear from something else in the paper? (I did not read the rest of the paper yet.)

In general, obvious theorems in pi-base can have a one or two line justification in pi-base itself.  But any non-trivial result should have a good justification somewhere else that we can just reference, from a paper or a book, or from mathse (i.e., something peer-reviewed or at least that has received scrutiny from a wider audience).

Can you ask a mathse question about this?

(And (not for this PR as adding a new space is more involved, but for a later one maybe) the example in Fig 1 would be interesting to have, as it illustrates that in general without an extra condition like locally connected the result is not true.)

**Comment by Jianing-Song** [comment]
> Just curious. What editor did you use for this? Did you use github.dev (= vscode) or something else?
> 
> (not sure if you used git before, but in github.dev at least, there is no need to have a separate commit for every little change to every file. You can accumulate multiple changes in multiple files and then do a single commit for that. Makes it more manageable, I think.)

I just used the web page (not sure how to call that...). Thanks for your suggestions.

**Comment by Jianing-Song** [comment]
> T473: I can see that the referenced paper claims this in its first paragraph, but without justification.
> 
> If X is connected locally compact Hausdorff, its one point compactification will be a continuum, hence have the property. But as the example in Fig 1 of the paper shows, it's not enough to conclude the property for X itself. Apparently, adding locally connected would be enough. That's not obvious to me. Is it clear from something else in the paper? (I did not read the rest of the paper yet.)
> 
> In general, obvious theorems in pi-base can have a one or two line justification in pi-base itself. But any non-trivial result should have a good justification somewhere else that we can just reference, from a paper or a book, or from mathse (i.e., something peer-reviewed or at least that has received scrutiny from a wider audience).
> 
> Can you ask a mathse question about this?
> 
> (And (not for this PR as adding a new space is more involved, but for a later one maybe) the example in Fig 1 would be interesting to have, as it illustrates that in general without an extra condition like locally connected the result is not true.)

OK I will do that, but perhaps I would need some time before that. Sorry!

**Comment by Jianing-Song** [comment]
> (And (not for this PR as adding a new space is more involved, but for a later one maybe) the example in Fig 1 would be interesting to have, as it illustrates that in general without an extra condition like locally connected the result is not true.)

Just one more remark: I would certainly be willing to learn adding new spaces in the future :)

**Comment by prabau** [comment]
> I just used the web page (not sure how to call that...).

Hmm, if you are editing one file at a time, that's not the way to go.

Maybe you used github.dev when doing the hello world tutorial.  But if you have not done it, you should follow @StevenClontz notes.  Specifically, from the page for the PR, click on the "Files changed" tab.  Then type a single dot (`.`) while on that page and that will open the github.dev editor.  From there, you can edit files, commit, etc.

**Comment by prabau** [comment]
I'll have more comments on the other parts of this PR, but feel free to commit things in the mean time.

**Comment by prabau** [comment]
Hi @Jianing-Song. Can you comment on the pending issues above?

**Comment by Moniker1998** [comment]
This property is called $\sigma$-connected as I commented in #593

**Comment by Jianing-Song** [comment]
> I'll have more comments on the other parts of this PR, but feel free to commit things in the mean time.

Sorry for being absent for nearly three weeks! I was working on another project and I'm finally being able to come back.

Seeing that many changes has taken place to the pi-base and that many changes need to be done with this pull request, could you please kindly give me some hint on the things to do next? Should I do some thing like withdrawing this PR and create a new one?

**Comment by Jianing-Song** [comment]
> This property is called σ-connected as I commented in #593

Thanks! Could you please help me to cite this book in this new property? I could not find a doi number

**Comment by Moniker1998** [comment]
@Jianing-Song DOI number for Nadler's Continuum theory: 10.1201/9781315274089

**Comment by Jianing-Song** [comment]
> @Jianing-Song DOI number for Nadler's Continuum theory: 10.1201/9781315274089

I see, thanks! (And forgive me for not having seen this DOI number already presented in P188 :) )

**Comment by prabau** [comment]
Hi @Jianing-Song. Good to have you back.  At this point, I think the best would be to close this particular PR and start a brand new one.  As I see it, there are two types of problems here that can be more easily fixed with a new PR.  One is about the mechanics of creating a PR, and the other is about the contents.

For the PR mechanics, first of all I see that you are doing this work on the [main](https://github.com/Jianing-Song/data) branch on [Jianing-Song/data](https://github.com/Jianing-Song/data).  Maybe that's ok for a first time, but in general you should do you work on a so-called **topic branch**, i.e., a branch forked from main and dedicated to your change, that later get merged into main when accepted..  That allows to have multiple topic branches in parallel and kind of independent of each other, with each able to be released independently of the others.  I am pretty sure that was covered in the Help for github. If that's too complicated for a first time, don't worry about it for now.  But later on, we'll insist on it.

Also, the editor you use is important.  Right now you have 16 commits for this PR, with each commit only covering a single file.  This is ridiculously ineffective.  As mentioned before, we recommend vscode in github.dev.  (But other choices are possible.)   One should be able to bundle changes to multiple files in a single commit.  Each commit kind of represents a logical grouping of changes to one or more files. What editor did you use?  How exactly are you editing things?

I really recommend playing with your hello-world repository.  Add multiple files, do commits involving multiple files, play with branching maybe, ...

Starting with a brand new PR will give the opportunity to master the proper way to do things.  It does not matter if it takes a few more days.  Once you master this properly, you'll be able to contribute more effectively.

As for the contents, I'll comment later.  But let's get the mechanics down first.

We are here to help you get up to speed so that you can become an effective contributor.  Please ask!

**Comment by Jianing-Song** [comment]
> Hi @Jianing-Song. Good to have you back. At this point, I think the best would be to close this particular PR and start a brand new one. As I see it, there are two types of problems here that can be more easily fixed with a new PR. One is about the mechanics of creating a PR, and the other is about the contents.
> 
> For the PR mechanics, first of all I see that you are doing this work on the [main](https://github.com/Jianing-Song/data) branch on [Jianing-Song/data](https://github.com/Jianing-Song/data). Maybe that's ok for a first time, but in general you should do your work on a so-called **topic branch**, i.e., a branch forked from main and dedicated to your change, that later gets merged into main when accepted.. That allows to have multiple topic branches in parallel and kind of independent of each other, with each able to be released independently of the others. I am pretty sure that was covered in the Help for github. If that's too complicated for a first time, don't worry about it for now. But later on, we'll insist on it.
> 
> Also, the editor you use is important. Right now you have 16 commits for this PR, with each commit only covering a single file. This is ridiculously ineffective. As mentioned before, we recommend vscode in github.dev. (But other choices are possible.) One should be able to bundle changes to multiple files in a single commit. Each commit kind of represents a logical grouping of changes to one or more files. What editor did you use? How exactly are you editing things?
> 
> I really recommend playing with your hello-world repository. Add multiple files, do commits involving multiple files, play with branching maybe, ...
> 
> Starting with a brand new PR will give the opportunity to master the proper way to do things. It does not matter if it takes a few more days. Once you master this properly, you'll be able to contribute more effectively.
> 
> As for the contents, I'll comment later. But let's get the mechanics down first.
> 
> We are here to help you get up to speed so that you can become an effective contributor. Please ask!

Thank you for you reply! I think I've got to understand the points.

**Comment by Jianing-Song** [comment]
> T473: I can see that the referenced paper claims this in its first paragraph, but without justification.
> 
> If X is connected locally compact Hausdorff, its one point compactification will be a continuum, hence have the property. But as the example in Fig 1 of the paper shows, it's not enough to conclude the property for X itself. Apparently, adding locally connected would be enough. That's not obvious to me. Is it clear from something else in the paper? (I did not read the rest of the paper yet.)
> 
> In general, obvious theorems in pi-base can have a one or two line justification in pi-base itself. But any non-trivial result should have a good justification somewhere else that we can just reference, from a paper or a book, or from mathse (i.e., something peer-reviewed or at least that has received scrutiny from a wider audience).
> 
> Can you ask a mathse question about this?
> 
> (And (not for this PR as adding a new space is more involved, but for a later one maybe) the example in Fig 1 would be interesting to have, as it illustrates that in general without an extra condition like locally connected the result is not true.)

As adding the counterexample would certainly be interesting (especially since that the example is presented also as Chapter 5, Section 4, Example 5.14 in the Nadler book _Continuum theory_, with the definition explicitly given), I'd be glad to know what is more involved to adding a new space :)

**Comment by prabau** [comment]
fyi, your new PR is much better regarding the commits.  Can you tell me which editor you are using for that?

**Comment by Jianing-Song** [comment]
> fyi, your new PR is much better regarding the commits. Just curious, can you tell me which editor you are using for that?

github.dev

**Pull request closed without merging**
