### PR TITLE
Add infinite indiscrete spaces with theorems for them

### PR DESCRIPTION
**Pull request by danflapjax**
This PR adds two spaces: S193 and S194, which are indiscrete spaces with cardinalities $\aleph_0$ and $\mathfrak c$, respectively. I also made theorems to deduce properties for them: T448 "Indiscrete => Alexandrov" and T449 "Indiscrete + Cardinality ≥ 3 => ~Has a Dispersion Point" were added, and T252 was edited to the strictly stronger "Indiscrete => Pseudometrizable", from which the previous implicand Perfectly Normal can be deduced using [T268](https://topology.pi-base.org/theorems/T000268).

### CODE REVIEW

**Comment by prabau** [comment]
As you can see in the error log for the build, it complains about having the same name for the two spaces.

**Comment by prabau** [comment]
- S193: instead of P58 (card < c), we should assert it's countable.
(If we had a convenience property for (card = $\aleph_0$) we could assert that directly, and then not even need (finite = false).  But there is not such property for now.  I'll add this to the list for Steven's attention.)

- I don't see the result (second countable = true).  It seems it would be worth introducing a theorem for it.  Could you do it in the same PR?

- T449: The proof seems a little complicated.  Can we do something simpler, like this for example:
> Removing a point from an indiscrete space with at least 3 points gives a connected space with at least two points, which cannot be {P47}.

(no need to elaborate more than that, I would say)

**Comment by danflapjax** [comment]
Thanks, that statement of T449 is way better, and I added theorems that indiscrete implies second countable along with indiscrete and cardinality $\ge \mathfrak c$ implies arc connected. (Shoutouts to the demo at #555 for helping me spot the latter.) Adding P58 instead of P57 honestly might have been a typo, but who knows. Either way, good catch. I think the PR should be good now.

**Comment by prabau** [comment]
There is a uid mismatch for T450 and T451.

**Comment by prabau** [comment]
T451 seems to have a syntax error in the `if:` clause.  Compare with T449 for example.

**Review by prabau — APPROVED** [review]
Looks good

**Pull request merged**
