### PR TITLE
Add theorem suggested in #152

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
Nice.  Would it be possible to also change the page that defines "hemicompact" to spell out the definition?  Arens (1946) is the original one that introduced the terminology, but Willard (17I) is the same and is more accessible.  Maybe worth changing too.

**Comment by StevenClontz** [comment]
@prabau how's that?

**Comment by StevenClontz** [comment]
@prabau I just sent an invite that should (I believe) give you the ability to approve PRs if you're interested. (I actually can't merge this until someone else submits an approving review without using my admin privileges haha.)

**Review by prabau — APPROVED** [review]
Looks good.

**Pull request merged**
