### PR TITLE
Some theorems about hereditarily Lindelof and G_delta spaces

### PR DESCRIPTION
**Pull request by prabau**
Adding a few simple theorems to increase the coverage of these properties.

- T259: countable implies hereditarily Lindelof
- T260: second countable implies hereditarily Lindelof
- T261: countable + T1 implies G_delta space

### CODE REVIEW

**Comment by prabau** [comment]
I just realized that the new T260 combined with https://topology.pi-base.org/theorems/T000258 (regular + hereditarily Lindelof implies perfectly normal) will allow to deduce "perfectly normal" for all regular second countable spaces.  There are lots of them:
https://topology.pi-base.org/spaces?q=Regular%2BSecond%20Countable
but currently only four of them are declared perfectly normal:
https://topology.pi-base.org/spaces?q=Regular%2BSecond%20Countable%2BPerfectly%20normal
That should be really good.

**Review by lyengulalp — APPROVED** [review]

**Comment by prabau** [comment]
Hi @lyengulalp  Was there a problem with the merging?

**Comment by StevenClontz** [comment]
I took care of it.

**Comment by lyengulalp** [comment]
Sorry, I missed that step! I'll look more carefully next time.

**Pull request merged**
