### PR TITLE
Homogeneous spaces with a cut point are T_1.

### PR DESCRIPTION
**Pull request by Almanzoris**
T209 could be referenced.

I'm going to reword the second either ... or ...; if the cut point is open, it would be reached that it is closed aswell.

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
Depending on what everyone decides to do with Issue https://github.com/pi-base/data/issues/940, a theorem involving that property (currently number 3 on the list) could be referenced.

**Comment by Almanzoris** [comment]
Good point! I hadn't read this... I could close it or change it to Homogeneous + Has a closed point ==> $T_1$, which would be the number 6 in the list.

**Comment by GeoffreySangston** [comment]
Maybe don't close it until that issue gets resolved. If you have the time, maybe you could weigh in any thoughts you have on that issue?

**Comment by Almanzoris** [comment]
Alright! I will read it better tomorrow. Although, I already agree with adding the property "Has a closed point".

**Comment by GeoffreySangston** [comment]
> I already agree with adding the property "Has a closed point".

Oh sorry I didn't notice you did!

**Comment by Almanzoris** [comment]
Yeah, I just missed reading the issue.

**Comment by StevenClontz** [comment]
Marking as draft as I think it will be closed by #965.

**Pull request closed without merging**
