### PR TITLE
Remove unused properties

### PR DESCRIPTION
**Pull request by StevenClontz**
Compare with #626 - either we should prune these as is done here, or at the very least add theorems connecting them to other properties.

### CODE REVIEW

**Comment by prabau** [comment]
Hmm, why do you want to remove those?
Two of us wanted to have the properties, but have not found the time to get to it.

**Comment by prabau** [comment]
I just took a look at Ascoli, which is the one I was sponsoring, and there is indeed next to nothing here.  So I am ok with removing that one and introducing it properly later.

@danflapjax You were sponsoring Semimetrizable.  Opinion?

**Comment by StevenClontz** [comment]
(To be clear, this PR proposal is only to delete them for today, as they are not being used anywhere, and not a decision that they should never be included in the database.)

**Comment by StevenClontz** [comment]
> @danflapjax You were sponsoring Semimetrizable. Opinion?

bumping this - I think either we should wire this up in the next week or so (at least theorems for 1metrizable => semimetrizable` (I'd assume) and `semimetrizble => something`.

**Comment by danflapjax** [comment]
There are some obvious theorems to add, but I'll check some reference books in a bit to make sure I'm not missing anything major. @Moniker1998 had a good suggestion at the unused properties issue plus some good comments on the definition at #775.

**Comment by StevenClontz** [comment]
I've added back semimetrizable here and this can be merged I think. @danflapjax can close #626 when semimetrizable theorems are added.

**Comment by prabau** [comment]
More than the theorems, we should also give a complete definition of semimetrizable, instead of sending the reader to check some reference.

**Comment by Moniker1998** [comment]
I was interested once to see if semimetric with open balls implies that the space is metrizable. Turns out it doesn't.

The example is given by McAuley, its example 1.7 here https://ttu-ir.tdl.org/server/api/core/bitstreams/87ef5d43-c479-4cd7-b67f-f5e4336876c9/content

The article is _Some results in semi-metric spaces_ by Stubblefield

**Review by danflapjax — APPROVED** [review]

**Pull request merged**
