### PR TITLE
Hereditarily Lindelof and G_delta space properties

### PR DESCRIPTION
**Pull request by prabau**
Two new properties:
- P131: Hereditarily Lindelof
- P132: G_delta space

Associated theorems:
- T254: hereditarily Lindelof implies Lindelof
- T255: Lindelof + G_delta space implies hereditarily Lindelof
- T256: perfectly normal implies G_delta space
- T257: normal + G_delta space implies perfectly normal
- T258: regular + hereditarily Lindelof implies perfectly normal

This will allow to automatically deduce the Sorgenfrey line is perfectly normal by showing it is hereditarily Lindelof.

### CODE REVIEW

**Comment by ccaruvana** [comment]
Hopefully I'm not being overly pedantic here but, in P15, the cited Theorem 1.5.19 in Engelking's book doesn't have the "every closed set is a G_delta" explicitly in the list of the equivalences. However, it is easily seen as part of the equivalence via Corollary 1.5.12. I agree with what is written but I was thinking about students visiting the entry as a reference and only slightly concerned they might not see it as easily (if they even have access to a copy of Engelking's book).

**Comment by ccaruvana** [comment]
Also, for P131, should we add in a comment about the equivalent definitions? Wikipedia has it listed and cites an exercise in Engelking. Would that be a useful addition or is it acceptable to just leave the general wikipedia reference in?

**Comment by prabau** [comment]
> 
> 
> Also, for P131, should we add in a comment about the equivalent definitions? Wikipedia has it listed and cites an exercise in Engelking. Would that be a useful addition or is it acceptable to just leave the general wikipedia reference in?

I have added a reference to a post on mathse.

**Comment by prabau** [comment]
> 
> 
> Hopefully I'm not being overly pedantic here but, in P15, the cited Theorem 1.5.19 in Engelking's book doesn't have the "every closed set is a G_delta" explicitly in the list of the equivalences. However, it is easily seen as part of the equivalence via Corollary 1.5.12. I agree with what is written but I was thinking about students visiting the entry as a reference and only slightly concerned they might not see it as easily (if they even have access to a copy of Engelking's book).

Hmm, I am a little confused.  Did you mean a "normal space for which every closed set is a G_delta" ?  That is part of 1.5.19.  We also have "arbitrary space for which every closed set is a zero-set".  But without normal, I don't think just "every closed set is a G_delta" is equivalent?

**Comment by prabau** [comment]
@ccaruvana I have added one mathse reference to a proof of the equivalence between two of the definitions of perfectly normal.  That should be accessible to all interested students.

**Comment by ccaruvana** [comment]
Ah, I didn't read carefully enough regarding the every closed set is a G_delta condition (went in assuming perfectly normal in Engelking meant the same thing as the first condition). Sorry for my carelessness here.

**Review by ccaruvana — APPROVED** [review]

**Comment by ccaruvana** [comment]
The merge was unsuccessful because the uid for T257 is T253. I presume the file can get updated and we can reattempt the merge?

**Comment by ccaruvana** [comment]
I created a new PR with the uid fix. Hopefully that'll take care of it.

**Comment by prabau** [comment]
> 
> 
> I created a new PR with the uid fix. Hopefully that'll take care of it.

Thanks for taking care of this.  I am not entirely sure, but you guys may have the ability to fix things with a commit in the same PR for a case like this. (At least when I create a PR, there is a button that I don't uncheck and that says so.)  @StevenClontz , do you know?

**Comment by StevenClontz** [comment]
Theoretically yes (which I've used for internal PRs), but I haven't taken advantage of it for a PR coming from outside the pi-base organization. Keep checking the option and I'll certainly attempt to try out the option on a future review that needs only a small tweak.

**Pull request merged**
