### PR TITLE
better first lines for properties with multiple characterizations

### LINKED ISSUE #1086: first line of descriptions
> I guess this might be a good place to mention this.
> 
> On [the properties page](https://topology.pi-base.org/properties), cmd + F shows are 6 properties which just give "Any of the following equivalent properties holds:", followed by a block of equivalent definitions. I think we should move the top line of each block to the top.

_Originally posted by @GeoffreySangston in https://github.com/pi-base/web/issues/177#issuecomment-2453839804_

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #1086

### CODE REVIEW

**Comment by prabau** [comment]
The suggestions seem ambiguous.

It used to be: Any of the following equivalent conditions: A, B, C, D.

Now: A, or any of the following equivalent conditions: B, C, D.
The meaning is: one of A, B, C, D.  And B, C, D are equivalent.  But A need not be equivalent to the other ones.

**Comment by prabau** [comment]
Compare with https://topology.pi-base.org/properties/P000135, which is more carefully worded.

**Comment by prabau** [comment]
I'll reiterate my comment from https://github.com/pi-base/web/pull/177#issuecomment-2453844417:
> I think the most important thing is to have a clear and coherent text on each property page. What is displayed in the Properties list is not very important.

But I'll go along with this PR.

**Comment by GeoffreySangston** [comment]
Excluding the 'Any of the following equivalent properties holds:' examples, I think the following are all of properties with three or more definitions, sorted by the way they're currently stylized.

1. ("Equivalently:")
- [Simply connected P200](https://topology.pi-base.org/properties/P000200)
- [Contractible P199](https://topology.pi-base.org/properties/P000199)
- [Semimetrizable P102](https://topology.pi-base.org/properties/P000102)
- [Has a point with a unique neighborhood P202](https://topology.pi-base.org/properties/P000202)
- [Noetherian P208](https://topology.pi-base.org/properties/P000208)
2. ("Equivalently, any of the following equivalent properties holds:")
- [T1 P2](https://topology.pi-base.org/properties/P000002)
- [R0 P135](https://topology.pi-base.org/properties/P000135)
3. (Separate paragraphs per "Equivalently")
- [Completely normal P14](https://topology.pi-base.org/properties/P000014)
- [Countably compact P19](https://topology.pi-base.org/properties/P000019)
- [Exhaustible by compacts P25](https://topology.pi-base.org/properties/P000025)
- [Hereditarily collectionwise normal P108](https://topology.pi-base.org/properties/P000108)
- [P-space P147](https://topology.pi-base.org/properties/P000147)
- [GO-space P154](https://topology.pi-base.org/properties/P000154)
- [k1-Hausdorff P170](https://topology.pi-base.org/properties/P000170)
- [sigma-connected P189](https://topology.pi-base.org/properties/P000189)
4. (In-paragraph equivalents)
- [Perfectly normal P15](https://topology.pi-base.org/properties/P000015)
5. ("And alternatively")
- [k2-Hausdorff P171](https://topology.pi-base.org/properties/P000171)

**Comment by prabau** [comment]
> I think we could change "Equivalently, any of the following equivalent properties holds:" to "This is equivalent to each of the following:".

Yeah, that reads much better, and is also correct.

**Comment by GeoffreySangston** [comment]
I don't mind doing the tedious work of switching these all to one style. Probably not for a few days.

**Comment by prabau** [comment]
Hmm, what do you have in mind exactly?  I think it's fine to change the introductory sentence when there is a list of bullet points.  But in my opinion, we may not want to convert everything to bullet points.

I agree with splitting the paragraph for P15 (your category 4).

**Comment by GeoffreySangston** [comment]
1. Definitely merging styles 1 and 2 into a single agreed upon version.
2. Superseded possibly by switching everything to the style we thought was the best, yet to be determined. I guessed that would be bullet points, but I'm also happy not switching everything to one style if it's deemed too unimportant.

Maybe going forward we could agree on a favored style for new properties? I don't see why to prefer the separate paragraph style, because then following paragraphs aren't as easily distinguishable from equivalent definitions.

**Comment by prabau** [comment]
> I don't see why to prefer the separate paragraph style, because then following paragraphs aren't as easily distinguishable from equivalent definitions.

We'll have to play it by ear.  I vaguely remember there were some cases of definitions involving multiple paragraphs, followed by some equivalent other characterizations in still other paragraphs.  Forcing all the first paragraphs to be scrunched together in a single bullet does not seem optimal.

But overall, to me it does not seem very important if we don't have a uniform style for this.  The main thing is to have something clear and unambiguous.  And I am ok with having the first line more descriptive of the property, if some people care about that.

**Review by GeoffreySangston — APPROVED** [review]
Sorry Steven. Afterwards I realized this would have been the ideal place to test out the 'suggestion' feature. I'll do it next time!

**Pull request merged**
