### PR TITLE
remove deprecated t29

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Per discussion at the last community meeting, we are okay with deleting deprecated theorems that don't have a particular benefit. I think the result that such spaces are pseudometrizable is more interesting to reveal to users.

**Comment by prabau** [comment]
Yes, I think it's fine to remove T29 [regular + second countable ==> completely normal].

It's redundant due to T23 (Nagata-Smirnov) [regular + sigma-locally-finite base ==> pseudometrizable].

But also due to T258 [regular + hereditarily Lindelof ==> perfectly normal].

**Comment by prabau** [comment]
Was wondering why [T23](https://topology.pi-base.org/theorems/T000023) (Nagata-Smirnov) was not showing the converse, as it's an iff.

It seems that https://topology.pi-base.org/theorems/T000020 [metrizable ==> sigma-locally finite base] can be upgraded to [pseudometrizable ==> sigma-locally finite base] by adding to it the same ref that was added for T23, namely
https://math.stackexchange.com/questions/3777706/nagata-smirnov-metrization-theorem-for-pseudometric-spaces

But apart from that, I can see why we would not want to spell out the full list of theorems showing that pseudometrizable implies regular.  It's just too long:
https://topology.pi-base.org/spaces?q=pseudometrizable%2B~regular

(actually, that could be a topic for discussion: when the list of theorems needed to fully show a converse is too long, maybe showing a partial list with the most salient results, enough to infer the full chain, would be sufficient.  It's an idea.)

**Comment by prabau** [comment]
Hey, what a coincidence.  I had written the above before looking at #410, and it seems we had the exact same idea :-)

**Review by prabau — APPROVED** [review]

**Pull request merged**
