### PR TITLE
Review unaudited content

### PR DESCRIPTION
**Pull request by jamesdabbs**
@StevenClontz - there's now a commit on `master` removing any space, property or theorem that doesn't have a `ref`, and any trait that doesn't have a `ref` or `description`. The removed files have been written out to `user/<email>` branches.

Couple things:
* I think that the spaces and theorems in this branch should probably be in master in some capacity. Should we try to track down references for them?
* Should I remove _all_ traits from `master` that don't have a `ref`, or just the manually asserted ones that don't have a "proof"
* You might want to review the other user branches, and the commit on `master` removing the unreferenced content and see if anything jumps out at you / you want to make any other changes.

### CODE REVIEW

**Comment by jamesdabbs** [comment]
@StevenClontz - the previous had a problem where I moved some spaces / properties to user branches, but left in some traits referencing those spaces / properties. I'm working on correcting that now, but the references are going to be off from this PR. In any case, could you please review:

* The latest commit on master removing unreferenced data
* The latest commit on at least my, yours, and @cdm1322's users branches for any content that we do want included in master

Thanks!

**Comment by StevenClontz** [comment]
Cody's 30e7ec9a seems to have references, so these should be in master.

As for my 92cb7141:
- I can't find a reference for a topological manifold that matches the one given in P000083. I don't study these so I'm not sure how it ended up in my branch. Anyway, I don't trust the results related to it given that it has a non-standard definition with no citations, so it should be scrubbed.
- I know P000092 and P000097 are my contributions, but I cannot find/remember references for them, so they can be safely scrubbed and re-entered once someone comes across them in the literature again.
- Trait `spaces/S000104/properties/P000006.md` has a reference and should be in master.
- I added a ref to `spaces/S000156/properties/P000080.md`
- These changes are in b0ce428

As for your 15f2819, this is a lot to go through by hand using the repo by itself. I think this stuff can wait until we have better tools in the pi-base viewer to sift through it and merge them back in. Is that alright? 

The master branch's head 5b43da7 points out that we lacked a reference for T_{3.5}, so it's been removed. It should reference Willard `mr: MR2048350, name: General Topology (Willard)` page 94. I don't know the best way to fix this.

**Comment by StevenClontz** [comment]
I think that the files with references that were removed got removed because of a lack of indentation for the refs array.

**Comment by StevenClontz** [comment]
I'm seeing a few files that got pruned in master for missing a reference in their metadata, but they do have Counterexamples referenced in their text: `{{doi:10.1007/978-1-4612-6290-9_6}}`. What's the best way for me to fix this?

**Comment by StevenClontz** [comment]
@jamesdabbs can we close this?

**Pull request closed without merging**
