### PR TITLE
Another positive homogeneous property S102|P86

### PR DESCRIPTION
**Pull request by GeoffreySangston**

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
https://math.stackexchange.com/questions/4053083/the-baire-space-is-homogeneous

This post has two relevant constructions, but they're not exactly the same thing since the cardinality of the product factors is different, so I wasn't sure if I should reference it or not.

**Comment by StevenClontz** [comment]
I think this could be strengthened to say S102 has a group topology, as it is the product of spaces with group topologies.

**Review by StevenClontz — CHANGES_REQUESTED** [review]
I think we should take this opportunity to assert P87 instead, unless I'm overlooking something.

**Comment by prabau** [comment]
Simplify by using `{S3|P87}` and any product of topological groups is a topological group.

**Review by StevenClontz — APPROVED** [review]
Thanks @GeoffreySangston!

**Pull request merged**
