### PR TITLE
Edit theorem 107

### PR DESCRIPTION
**Pull request by lyengulalp**
Edit theorem 107. #325

### CODE REVIEW

**Comment by prabau** [comment]
There may be problem with the branches.  It seems you created your branch off of "master".  But as Steven explained, we are now supposed to create branches off of "main".  Before six months ago we used to base topic branches off of master, but I don't use my prabau:master branch anymore.

As a general rule, it's better to do all the work in separate "topic branches" and not in a "master" or "main" branch itself.  That also allows to work on multiple things in parallel, and commit/push one without impacting the other.  Taking https://github.com/pi-base/data/pull/309 to illustrate the concepts: you see at the top that the work was done in a topic branch called "arens-modified", which was in the official repo itself (i.e. the branch was "arens-modified" and not "prabau:arens-modified").  When the PR gets approved and merged, that topic branch in the official repo gets automatically deleted, as you can see at the bottom of the conversation).

There are at least two general ways to do the work.  The first one is to have a local copy of the repo on your computer, with your own "main" branch that you can keep in sync with the upstream repo via "git pull".  And then whenever you need a create a pull request, you create a branch locally off of your main, using "git checkout -b T107-fix" for example.  Then you work locally on your computer using vscode and then commit and push that "T107-fix" branch to upstream (= the official repo).  That moves a copy of your local "T107-fix" branch to the official repo.  Now comes something very handy: Once there is a "T107-fix" branch in the official, you and the reviewers can inspect what the final result would look like by going to https://topology.pi-base.org/dev, entering "T107-fix" in the Branch box and clicking Refresh.  You will then be able to navigate the pi-base web site with your change incorporated, before things are finalized.  It then allows you to do more commits and see more changes until things look good.  Very handy!

The other way is to not work on a local copy of the repo, but do everything in the browser itself, using the github.dev web based editor. (navigate to https://github.com/pi-base/data/blob/main/theorems/T000107.md (in the official repo), in the editing drop down menu on the right, choose "github.dev" (or press dot ".") and start editing.  But be careful: at that point you will be in the official "main" branch and we should never directly make changes to the official main branch.  So the first thing to do is to create a new topic branch ("T107-fix" for example) based on main and then work in the topic branch.  (there is a menu at the top to create a branch, etc.)  The advantage is this second approach is that the topic branch you create will automatically be part of the official repo, so able to see the changes in the browser after commit without extra step.  etc ...

What method did you use for the branches?  What method of the two above would you like to use going forward?  Can I clarify anything?

And then I think the best would be to create a new PR based on a proper branch as described above.

**Comment by lyengulalp** [comment]
I think the issue was that I was following old steps from the last time Steven helped me (months ago). I followed the steps [here](https://github.com/pi-base/data/wiki/Contributing#discussions) and ended up using an old fork after syncing (that was created from master long ago). 

What you say about topic branches makes sense and I will try the first approach...again, slowly. 

Thanks for the help! I'll submit a new pull request.

**Comment by prabau** [comment]
> I think the issue was that I was following old steps from the last time Steven helped me (months ago). I followed the steps [here](https://github.com/pi-base/data/wiki/Contributing#discussions) and ended up using an old fork after syncing (that was created from master long ago).

Yeah, maybe the instructions in https://github.com/pi-base/data/wiki/Contributing#discussions would need to be updated.

@StevenClontz  fyi

**Comment by prabau** [comment]
Superseded by #330.

**Pull request closed without merging**
