### PR TITLE
Improve topological group property

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
Can we add the basic theorem that topological groups are completely regular (even without T2)?  I don't have a reference offhand, but it's a standard result.

**Comment by StevenClontz** [comment]
Oh wow I didn't even realize we lacked any theorems. We should definitely identify a sufficient condition as well if we can.

**Comment by prabau** [comment]
Just a thought.  What about "group topology" for the primary name, instead of "topological group" (which we would keep as an alias)?  It's along the lines of "topological group topology" that you mentioned, in the sense that it implies the existence of a group structure compatible with the topology without having to pin down what that group operation is.

**Comment by StevenClontz** [comment]
> Just a thought. What about "group topology" for the primary name, instead of "topological group" (which we would keep as an alias)? It's along the lines of "topological group topology" that you mentioned, in the sense that it implies the existence of a group structure compatible with the topology without having to pin down what that group operation is.

snuck this into https://github.com/pi-base/data/pull/304/commits/832df88f3991291eacd9a402347148b31c343706 when resolving  a merge conflict.

**Comment by prabau** [comment]
I added a few things:
- slight change to the name for P87 to better match the adjective form.  Can we remove "groupable"?
- Cantor space: assert topological group instead of homogeneous
- T346: needed the nonempty condition
- add T347, T348, T349

**Comment by StevenClontz** [comment]
Re S54: good call. I was going to see if we had $X\times Y$ where $X$ is two-point discrete and $Y$ is two-point indiscrete....

**Comment by StevenClontz** [comment]
This PR is getting large though - I'm going to check your changes and if nothing's wrong I vote you mark as approved and do further work in a future PR.

**Comment by prabau** [comment]
Added a few things which may not be obvious to a beginner, like the Odd-Even topology has a group topology.  Ditto for the irrationals.

**Comment by prabau** [comment]
> Re S54: good call. I was going to see if we had X×Y where X is two-point discrete and Y is two-point indiscrete....

Yes, it's S5.

**Comment by StevenClontz** [comment]
S5 is $\omega\times 2$ with $\omega$ discrete and $2$ indiscrete - I think we're actually missing $\{\emptyset,\{0,1\},\{2,3\},X\}$. Something for the future.

**Comment by prabau** [comment]
> This PR is getting large though - I'm going to check your changes and if nothing's wrong I vote you mark as approved and do further work in a future PR.

Agree.  One thing I feel uneasy about is T346.  It's just quoting someone's comment to a mathse question, but without justification or reference.  Admittedly that person is reputable, but still I don't think that passes the bar for inclusion in pi-base without a real reference.

**Comment by StevenClontz** [comment]
Yeah I think that's the last thing to check. A proof is unclear to me so I asked the question here: https://math.stackexchange.com/questions/4685141/

**Comment by StevenClontz** [comment]
Yeah. I've been thinking that rather than adding it as theorem, it's better to just add "has a group topology" manually to the finite discrete spaces and Cantor space.

**Comment by StevenClontz** [comment]
Oh and it's really just adding it manually to one place: the Cantor space, since nonempty discrete gets you the property anyway.

**Comment by StevenClontz** [comment]
> All the theorems are of the form a bunch of properties imply another property. That new thing for characterizing specific spaces would be extending the theorem syntax to be a bunch of properties implying a space.

Yeah I've been thinking that we should consider allowing the "then" part of a theorem to be a property OR space.

**Comment by prabau** [comment]
> Oh and it's really just adding it manually to one place: the Cantor space, since nonempty discrete gets you the property anyway.

I added it already (S26)

**Comment by StevenClontz** [comment]
Then the theorem is doing basically nothing, other than explaining why https://topology.pi-base.org/spaces?q=Homogeneous%2B~Empty%2BTotally%20Disconnected%2BCompact%2Bsecond%20countable%2B~Has%20a%20group%20topology cannot be satisfied, which I think is fine for today. Maybe this is ready?

**Comment by StevenClontz** [comment]
okay maybe now (renumbered a theorem to fill the gap left by removing the sufficient condition)

**Comment by prabau** [comment]
Yeah, checking how it looks and approving.

**Comment by prabau** [comment]
@lyengulalp  @ccaruvana  One github question.  Just curious, are Chris and Lynne automatically notified when we add comments in these conversations?  (in case they want to interject something)

**Comment by StevenClontz** [comment]
I think not unless they are tagged in. It'd be good to explore how to set up notifications so folks can chime in on things even if they aren't directly involved in proposing or reviewing a PR

**Comment by prabau** [comment]
I receive email notifications for all new PR and issues and added comments because I added myself as a watcher: https://github.com/pi-base/data/watchers. That would be one way to do it.

**Comment by ccaruvana** [comment]
I should probably add myself to the watcher list. Sorry I haven't been able to keep up lately anyway. Semester has really been getting to me, but I wanted to chime in on this discussion to say something basic at the risk of being redundant since I haven't checked the theorems that were already passed through. Based on an earlier comment, I wanted to point out that all T_0 topological groups are completely regular, but I think this is generally true based on the uniform structure. Every topological group is uniform via the entourages fg^(-1) or so. If this isn't reflected already in what has been done, it may streamline some things. I seem to remember that all uniform spaces are completely regular by giving values to decreasing sequences of entourages, but I may be misremembering and I'm also not sure if T_0 is necessary in that construction.

Actually, just doing a quick gander, it doesn't seem like we have "uniformizable" as a property in the pi-base. So the theorems for topological groups can be made more general for uniform spaces. As a side note, I think at one point I was interested in knowing whether every uniform space is homogeneous, but I don't remember looking that hard into it.

Finals week is next week, so hopefully I get a chance to get a closer look at what has been going on and participate more after that.

**Comment by ccaruvana** [comment]
Regarding my previous post, I guess I didn't think about it too hard because [0,1] is uniform but not homogeneous, for example.

**Comment by ccaruvana** [comment]
If I remember correctly, these results should be in Kelley's Topology. I don't remember reading about it in Willard. Engelking's Topology should also have all of this. Once the semester winds down, if no one gets to it before I do, I can flesh some of that out with references.

**Comment by prabau** [comment]
Steven added the equivalence between completely regular and uniformizable to https://topology.pi-base.org/properties/P000012.  It's Theorem 38.2 in Willard.  So topological groups are completely regular even without T_0.

**Comment by StevenClontz** [comment]
> So topological groups are completely regular even without T_0.

Assuming (as we do) that T_0 isn't required for topological groups by definition: I believe some authors add it as an additional requirement.

**Comment by ccaruvana** [comment]
Thanks for reminding me of that equivalence, @prabau .

**Pull request merged**
