### PR TITLE
Removed redundant traits of S7

### PR DESCRIPTION
**Pull request by JoeF131**
[T_0](https://topology.pi-base.org/properties/P000001) follows from [Door](https://topology.pi-base.org/properties/P000126) using [T143](https://topology.pi-base.org/theorems/T000143).
[Finite](https://topology.pi-base.org/properties/P000078) follows from $\lnot$ [Cardinality ≥4](https://topology.pi-base.org/properties/P000176) using [T431](https://topology.pi-base.org/theorems/T000431).
[Hyperconnected](https://topology.pi-base.org/properties/P000039) follows from [Has a generic point](https://topology.pi-base.org/properties/P000201) using [T593](https://topology.pi-base.org/theorems/T000593).

$\lnot$[T_1](https://topology.pi-base.org/properties/P000002) is redundant since:
[Cardinality ≥3](https://topology.pi-base.org/properties/P000175) and [T_0](https://topology.pi-base.org/properties/P000001) imply $\lnot$[Indiscrete](https://topology.pi-base.org/properties/P000129) using [T428](https://topology.pi-base.org/theorems/T000428) + [T253](https://topology.pi-base.org/theorems/T000253).  Combining $\lnot$ Indiscrete with [Has a generic point](https://topology.pi-base.org/properties/P000201)
implies $\lnot$[P2](https://topology.pi-base.org/properties/P000002).

Lastly [Has a generic point](https://topology.pi-base.org/properties/P000201) is redundant since:
[Finite](https://topology.pi-base.org/properties/P000078) and [Fixed point property](https://topology.pi-base.org/properties/P000089) imply [Path connected](https://topology.pi-base.org/properties/P000037) using [T266](https://topology.pi-base.org/theorems/T266) + [T565](https://topology.pi-base.org/theorems/T565) +[T316](https://topology.pi-base.org/theorems/T316) +[T443](https://topology.pi-base.org/theorems/T443) + [T95](https://topology.pi-base.org/theorems/T95). Now assuming Has a generic point we would get with [Has a dispersion point](https://topology.pi-base.org/properties/P000045) and [T602](https://topology.pi-base.org/theorems/T602) + [T598](https://topology.pi-base.org/theorems/T598) that S7 has to be [Ultraconnected](https://topology.pi-base.org/properties/P000040) which is not the case.

For the last paragraph I would suggest that you just put ¬[Has a generic point](https://topology.pi-base.org/properties/P000201) ∧ [Has a dispersion point](https://topology.pi-base.org/properties/P000045) ∧ [Finite](https://topology.pi-base.org/properties/P000078) ∧ [Fixed point property](https://topology.pi-base.org/properties/P000089) ∧ ¬[Ultraconnected](https://topology.pi-base.org/properties/P000040) into the search and see it for yourself.

Taking any 5 properties that are remaining, then they are uncappable to imply the 6th.

### CODE REVIEW

**Comment by prabau** [comment]
Very nice.  Approving.

I have duplicated your branch to the branch `pr898-preview` in the official repository to be able to do a side by side comparison with the `main` branch.  I checked that in the new branch all the removed traits are still properly derived.  (That's pretty easy to do from the web page for the property.)  It's all good.

In the future, once you get access to the official repo, you'll be able to do the same much more easily.  And there will be no need then to justify the change in detail in the description, as it will be easier for the reviewer to check it directly like I did.

Minor: I removed "See description" from the title of the PR.  No need for that, as it's always implied.

@StevenClontz Next step?

**Review by prabau — APPROVED** [review]

**Comment by JoeF131** [comment]
Neat. I think I might continue to remove the redundant traits of the other 11 topological spaces of cardinality $\leq 3$. 
I also realised that we have 12 of the 14 topological spaces of cardinality $\leq 3$ (up to homeomorphism) in pi base, so would it be reasonable to add the missing two for completness sake? (Sould I create an issue asking to add those?)

**Comment by StevenClontz** [comment]
@JoeF131 thank you for your contribution! You now have permissions to make branches directly on this repository, not a fork. This allows you and others to see previews of your work at https://topology.pi-base.org/dev

> I also realised that we have 12 of the 14 topological spaces of cardinality ≤3

I think having all 14 spaces of cardinality ≤3 in pi-Base is reasonable, especially as we're so close. I say this with the caveat that I don't think we need to "catch 'em all" for any higher finite cardinalities just to say we did.

**Comment by prabau** [comment]
> Sould I create an issue asking to add those?

No need to create issues like that.  If you want to add a new space, you can do a PR directly at any time.

**Comment by JoeF131** [comment]
> I think having all 14 spaces of cardinality ≤3 in pi-Base is reasonable, especially as we're so close. I say this with the caveat that I don't think we need to "catch 'em all" for any higher finite cardinalities just to say we did.

That was also my thought process. There are only 2 missing so one might add them add well. For any higher cardinality this becomes unreasonable since for Card=4 there are already 33 topological spaces (31 of which missing) and anything higher, well the number of topological spaces grows exponentially so that just impossible.

**Pull request merged**
