### PR TITLE
Added theorem: countable implies locally countable.

### PR DESCRIPTION
**Pull request by tomaszrz1**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Thanks for the PR! Unfortunately we don't have the quick review turn-around I really want us to have at the moment. I have travel coming up in the next couple of days but will look back at this in early August.

**Comment by tomaszrz1** [comment]
Yes. The code seems correct, though.

wt., 25.08.2020, 06:21 użytkownik Patrick Rabau <notifications@github.com>
napisał:

**Comment by prabau** [comment]
@tomaszrz1 You can edit the title of the commit right in github.
I wish Steven could look at this at some point.

**Comment by tomaszrz1** [comment]
> 
> 
> @tomaszrz1 You can edit the title of the pull request at least right in github (not sure about how to edit the title of a commit itself).
> I wish Steven could look at this at some point.

Done! (The first part, anyway.)

**Comment by StevenClontz** [comment]
I said I'd get to it in August, I just never said which year. (-: Thanks for your patience; I look forward to putting more time into pi-base now that a few things have been sorted on my end.

@jamesdabbs and I chatted a bit this morning and I'm going to work through PR backlog today.

Some enhancements for contributors and reviewers are being planned (e.g. a way to preview your contribution as it would appear on the topology.pi-base.org site).

**Pull request merged**
