### PR TITLE
Add semi-Hausdorff/RC not locally Hausdorff examples

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by prabau** [comment]
Good example of KC + not locally Hausdorff.

The name "Converging sequence of Semi-Hausdorff spaces" seems too general.  Any converging sequence of Hausdorff spaces would fit the bill.  "Converging sequence of spaces with Steen-Seebach maximal compact topology" is too long.  Other suggestions?

T1 (P2) could be deduced from KC (P100).

I made some trivial changes (for P16, the web display had two contiguous links that seems like a single link to "Compact Steen-Seebach maximal compact topology", which looked weird.  So I visually separated the two links.)

**Comment by prabau** [comment]
I added something for P100, as the argument was a little terse I thought.  If too much, we can revert.

**Comment by StevenClontz** [comment]
The point of S186 is to obtain a non-LH space, so I renamed semi-Hausdorff to non-Hausdorff to guarantee LH is broken.

**Comment by prabau** [comment]
The new name is a little better.  Ok, I'll approve.

**Review by prabau — APPROVED** [review]

**Pull request merged**
