### PR TITLE
Weak topology on $\ell^2$ is an $\aleph_0$-space

### PR DESCRIPTION
**Pull request by Moniker1998**
As the title. 

In one of the articles $\aleph_0$-spaces on pi-base reference to https://topology.pi-base.org/properties/P000179/references that is $\aleph_0$-spaces by E. Michael, there's also contained a result that dual of a separable Banach space in its weak* topology is an $\aleph_0$-space, which shows $\ell^2$ in its weak topology is an $\aleph_0$-space.

 https://github.com/pi-base/data/issues/751

### CODE REVIEW

**Comment by Almanzoris** [comment]
Good result. I have just seen these PRs right now, it would have solved a few doubts I had about this space. Funnily enough, I have solved them earlier today, but deducing that it has a weaker property (Has a countable network), which would be your previous PR.

**Comment by Moniker1998** [comment]
Yes. My primary goal was to obtain separation properties for this space, but then I've seen one could just prove it has countable network (which follows from $\ell^2$ having countable network), and here we have an even stronger property that it has countable k-network.

**Comment by StevenClontz** [comment]
As a note, I'd prefer someone with more background than myself in functional analysis reviewing this. I wonder if there's a characterization of this space that would help make this example more accessible to general topologists (to come in a separate PR if so).

**Comment by Moniker1998** [comment]
@StevenClontz what exactly are you alluding to? I'm not exactly sure what is non-topological that needs explaining here.

**Comment by prabau** [comment]
I did some reading about this and got most of it, except I am missing one thing. Let me explain my understanding at a high level, and then a question at the end.

Here, $H$ is a separable (real) Hilbert space with its two topologies, the norm-topology induced by the inner product and the weak topology.

(1) the [Hilbert projection theorem](https://en.wikipedia.org/wiki/Hilbert_projection_theorem) (consequence of the parallelogram identity in inner product spaces)

(2) the [Riesz representation theorem](https://en.wikipedia.org/wiki/Riesz_representation_theorem): Every continuous linear functional on $H$ is of the form inner product $\phi_y=\langle y,.\rangle$ for some fixed vector $y$. (Proof uses (1)) And the operator norm of $\phi_y$ is equal to the norm of $y$.  So $H$ is isometrically isomorphic to its continuous dual $H'$ with the operator norm.  And the weak topology on $H$ is homeomorphic to the weak-* topology on $H'$.

(3) The [Banach-Alaoglu theorem](https://en.wikipedia.org/wiki/Banach%E2%80%93Alaoglu_theorem): For a normed vector space $X$, the closed unit ball $U$ (for the operator norm) in the continuous dual $X'$ is compact in the weak-* topology. (For the proof, weak-* convergence is pointwise convergence of functionals.  One views $X'$ as a subspace of $\mathbb R^X$ with the product topology.  The set $U$ is closed in $\mathbb R^X$ and contained in a compact subset of $\mathbb R^X$, since evaluating $u\in U$ at each fixed $x\in X$ gives a bounded set of reals.  So $U$ is weak-* compact in $X'$.  Combining this with (2) gives that the unit ball (in the norm topology) of the Hilbert space $H$ is weakly compact.

(4) Since $H$ is separable, one shows that $U$ is metrizable for the weak-* topology (an essential ingredient is that a countable product $\mathbb R^\omega$ is metrizable with the product topology).

For (3) and (4): a pretty clear account is https://heil.math.gatech.edu/6338/summer08/section9f.pdf (linked as the first reference from https://math.stackexchange.com/questions/1462269).

So, back to the notation in Michael's Corollary 7.10: $X$ is a Banach space. If $S_n$ is the closed ball of radius $n$ about the origin in the continuous dual $X'$ (with the operator norm), then $S_n$ is compact in the weak-* topology.

Question: Why is every weak-* compact subset of $X'$ contained in some $S_n$?

**Comment by Moniker1998** [comment]
If $C$ is a weak-* compact subset of $X'$, then for $x\in X$ the map $T\mapsto T(x)$ is continuous - this is basically from the definition of weak-* topology. It follows that image of $C$ by this map is bounded. Now [uniform boundedness principle](https://en.wikipedia.org/wiki/Uniform_boundedness_principle) tells us that this implies that $\sup_{T\in C} \|T\| < \infty$, that is $C$ is contained in $S_n$ for some $n$.

**Comment by prabau** [comment]
Thanks for the explanation!  I am satisfied as far as the mathematics goes.

I'd like to make a suggestion in the exposition. Will respond later today.

**Comment by prabau** [comment]
I made a copy of your branch to the `weak-hilbert` branch in the official repository, so we can check the intended result on the web. You can check it by changing the branch name in the Advanced tab.

I'd like to suggest replacing the P179 (aleph_0) trait for S21 with a trait file for P183 (countable $k$-network).  I have added a version for that, with more details to make it easier to understand for people not so familiar with functional analysis.  It still references Michael's Corollary 7.10 for anyone who wants to check that.  Another advantage is that it gives an explicit construction for a countable $k$-network in this case.  And no need to check $T_3$ explicitly here, since that is already known from other traits for this space.  Of course this implies $\aleph_0$-space.

@Moniker1998 @StevenClontz Please take a look at P179 and P183 from the `weak-hilbert` branch.  What do you think?

**Comment by Moniker1998** [comment]
@prabau 

If we are to add that S21 has countable $k$-network then one should also delete that its an $\aleph_0$-space because of redundancy. 

Also we should decide if we want reference to such common results from functional analysis as Banach-Alaoglu theorem or the uniform boundedness principle, and if so then we should be consistent about it, adding all possible references (so far there is just one reference to wikipedia added). 

If we want to be more precise then for example

- Since the weak-topology on $H$ is homeomorphic to the weak-* topology on $H^*$ by reflexivity of Hilbert spaces, the closed unit ball (with respect to the norm) in $H$ is weakly compact.

should mention by what map we have such homeomorphism. 

- If $H$ is a separable Hilbert space, one deduces that the closed unit ball is metrizable in the weak topology;

If we want to be precise this also needs justification. Currently its just a true but unjustified statement.

- So the union of the families $\mathcal N_n$ for $n=1,2,\dots$ is a countable $k$-network for the weak topology on $H$.

This seems to imply that it's straightforward that $\bigcup_n N_n$ is a $k$-network for $H$. Its certainly not straightforward to me, in fact I don't see how that's obvious.

**Comment by Moniker1998** [comment]
I think that this seemingly elementary proof might be more trouble than its worth, and one should just cite the original paper by E. Michael.

**Comment by prabau** [comment]
Yes, if we separately add that S21 has a countable $k$-network (P183), we should remove the trait file for $\aleph_0$-space.  I had both of them for now to easily compare them side by side when discussing this.

And no, it's not meant to be a "seemingly elementary proof".  The suggested P183 explanation does have the reference to Corollary 7.10 from Michael's paper in the last line.  What comes before the last line is not meant to be a full explanation, but a more accessible explanation of some of the more difficult parts to make sense of Corollary 7.10.

Now for some of the details.

You mention that "if we want to be more precise", we should also mention what map gives the homeomorphism between the weak topology on $H$ and the weak-* topology on $H^\ast$.  I could have been slightly more precise and mentioned it's an linear isometry between $H$ with its norm topology and $H^\ast$ with its dual norm topology, and also a linear homeomorphism for the weak and weak-* topologies, all due to the Riesz representation theorem (and give a link to wikipedia).  But again, this was not meant to be a fully detailed account of a possible proof here, just a summary of some of the main points.  Note also that already the description (README file) for S21 and the trait file for P17 mention this homeomorphism without extra justification.  Even what you added for P179 does the same.

Also, it is not the case that there is only one reference to wikipedia.  I did mention the uniform boundedness principle with a link to wikipedia.  I was debating whether to add it also to the `refs:` section and thought maybe it was not needed there.  But if you think we should, we can add it there as well.

> If $H$ is a separable Hilbert space, one deduces that the closed unit ball is metrizable in the weak topology

There is an easy proof of this, using the fact that the unit ball is weakly compact.  But it's true that I did not justify this.  It's mentioned in https://en.wikipedia.org/wiki/Weak_topology with some reference to Narici & Beckenstein.  Maybe we should refer to a theorem in there, or to some mathse post about it.  What do you think?

> every compact subset of $H$ for the weak topology is contained in some ball $B_n$.  So the union of the families $\mathcal N_n$ for $n=1,2,\dots$ is a countable $k$-network for the weak topology on $H$.

That did seem kind of obvious.  Given a weakly compact $K$ and an weakly open $U$ in $H$ with $K\subseteq U$, the subset $K$ is contained in some $B_n$.  So $K$ is contained in $U\cap B_n$, which is open in $B_n$.  Take a finite subcollection $\mathcal M\subseteq\mathcal N_n$ such $K\subseteq\bigcup\mathcal M\subseteq U\cap B_n$ (from the definition of $k$-network for $B_n$).  Then $\mathcal M$ is a finite subcollection of $\mathcal N$ with $K\subseteq\bigcup\mathcal M\subseteq U$.

**Comment by prabau** [comment]
@StevenClontz I'd appreciate if you could take a look as well.

**Comment by Moniker1998** [comment]
I see what you mean now. As for citing all those theorems from functional analysis, rather than citing wikipedia I'd be more content with citing one book about functional analysis where all of them are located. It won't be hard to find such book, those results are in almost every introduction to the subject.

One such book is _Banach space theory: The basis for linear and nonlinear analysis_ by Fabian, Habala, Hajek, Montesinos and Zizler
The book gives a very complete exposition to theory of Banach spaces, so its a good reference for anything that deals with normed spaces.

**Comment by prabau** [comment]
Ok. I'll let @StevenClontz take a closer look and then we can all decide what to do.

**Comment by StevenClontz** [comment]
Haven't had much time for pi-Base reviews past week or so, but I think this is worth discussing at our community meeting tomorrow, so it's on the agenda.

**Comment by prabau** [comment]
@Moniker1998 I would perfectly fine if you want to reference various theorems from the book you mentioned instead of wikipedia.  You can rewrite the explanation in a different way if you want.  But as discussed above, I still think there is value in mentioning some of the details along the line of my proposal instead of just quoting Michael's Corollary 7.10.

How would you like to proceed?  You can either modify your branch, or modify the `weak-hilbert` branch or create a separate branch in the official repo (so we can see the result before merging), or something else?

**Comment by prabau** [comment]
@Moniker1998 If you want to make a change, it would be helpful to do in on a new branch in the official repository.  (I think that would requite to close this PR and open a new one.) That will allow the preview feature from the pi-base web site.

**Review by StevenClontz — APPROVED** [review]
Apparently @Moniker1998 had not yet been given write access to the repo. They now have been invited. So for future contributions, @Moniker1998 can push new branches to this repository directly (as long as it's not named `main`) and previews will be built and sent to the live website via the Advanced tab.

I've copied the merge commit `d6d5993` to a new branch `pr761-2` that lives here, and [everything builds successfully](https://github.com/pi-base/data/actions/runs/11219259882/job/31184812190).

I think that since we're happy with the result's accuracy, I can approve and merge this PR. Then, we should discuss @prabau's suggested improvements in a separate PR, particularly as they already exist in a branch: https://github.com/pi-base/data/compare/main...weak-hilbert Patrick, please open that PR to continue this discussion (so that others can review/approve).

**Pull request merged**
