### PR TITLE
Geoffrey

### PR DESCRIPTION
**Pull request by GeoffreySangston**
I added P000199 (Contractible), T000564 (Contractible => Path Connected), and T000565 (Indiscrete => Contractible).
I also added P000199 (Contractible) as a property to S000025 (Euclidean Real Numbers).

### CODE REVIEW

**Comment by yhx-12243** [comment]
Maybe you can add a slightly weaker condition: Simply connected (which is implied by Contractible).

**Comment by yhx-12243** [comment]
Maybe you can add a slightly weaker condition: Simply connectedness (which is implied by Contractible).

**Comment by GeoffreySangston** [comment]
[> Maybe you can add a slightly weaker condition: Simply connectedness (which is implied by Contractible).

I made a comment discussing this here https://github.com/pi-base/data/issues/818#issuecomment-2439599773

**Comment by prabau** [comment]
@yhx-12243 Simply connected is not yet in pi-base.  Once it gets added, we'll modify the theorems and traits for spaces accordingly.

**Comment by prabau** [comment]
@GeoffreySangston Can you change the PR title to something more specific (e.g., "Contractible property")?  That will make it easier to figure what each PR is about when scanning the list (in particular the list of closed PRs later on).

**Pull request closed without merging**
