### PR TITLE
Discrete implies locally Euclidean

### PR DESCRIPTION
**Pull request by danflapjax**
After noticing that the singleton space was deduced as not locally Euclidean (yet no other discrete space was), I decided to not just alter the culprit [T171](https://topology.pi-base.org/theorems/T000171) but also [be bold](https://en.wikipedia.org/wiki/Wikipedia:Be_bold) and add a theorem that says that discrete spaces are locally Euclidean. While none of my textbooks seem to say this explicitly, I believe it to be standard practice and I was certainly taught that any countable discrete space is a manifold since $\mathbb R^0$ is the singleton. A citation for this would be an improvement, however. Adding this theorem also obsoletes [T84](https://topology.pi-base.org/theorems/T000084), so I deleted it. I also verified that all other properties currently implied by locally Euclidean already hold for discrete spaces, so no other theorems need to be altered.

### CODE REVIEW

**Comment by prabau** [comment]
Thank you very much for your contribution.  We really appreciate it.

One thing is clear, the definition of Locally Euclidean (https://topology.pi-base.org/properties/P000123) in pi-base was a little sloppy as it did not specify the allowed values for $n$.  At first sight, it seems reasonable to allow $n=0$. I'll look at it in more details later today and give some comments.

**Comment by prabau** [comment]
1) We need to clarify the definition of locally Euclidean (https://topology.pi-base.org/properties/P000123).  Can you change the text to "... for some integer $n\ge 0" ?  And also add an explanatory sentence like the following for example:
> In the case $n=0$, the point having a neighborhood homeomorphic to $\mathbb R^0=\\{0\\}$ means it is an isolated point.

IMPORTANT: Note that the way things are phrased, the local dimension $n$ is allowed to vary from point to point.  And hence similarly for what is considered a topological manifold (P124).  There is some discussion of this in https://en.wikipedia.org/wiki/Manifold.  Most sources, but not all, assume a more restrictive definition where $n$ is constant and talk about an "$n$-manifold" for example.  It seems fine to me to keep the more general definition in pi-base, especially for "locally Euclidean" without extra qualifier.  Lee (https://mathscinet.ams.org/mathscinet/relay-station?mr=2766102) uses the terminology "locally Euclidean of dimension $n$", which explicitly specifies the constant dimension.

@StevenClontz Any comments on the above?

2) T171 [locally Euclidean + multiple points ==> not hyperconnected]: your proposed result is fine.  But I would change the justification slightly.  No need to mention P50 here.  How about something along the lines of: If there is a point with an open nbhd homeo to an open subset of ... with $n\ge 1$, ... (same as before). Otherwise, every point is isolated and the space is discrete.  But there are at least two points, so ...

3) T434: typo: "is an open ..." --> "has an open ..."

4) T435: not valid given (1) above

5) T84 [discrete ==> locally arc connected] can be removed as it follows from the new T171 and T82 [locally Euclidean ==> locally arc connected].  But it seems it would be useful to add to T82 part of the justification that used to be in T84.  Something like this for example:
> Note that in the case $n=0$ the point $x$ is isolated and its open neighborhood $\\{x\\}$ is vacuously {P38} by definition.

**Comment by prabau** [comment]
FYI Lee (mentioned above) explicitly allows $n=0$ in various definitions and mentions the connection with discrete spaces, but it also makes the dimension explicitly constant.  If we wanted a reference, one could possibly add https://en.wikipedia.org/wiki/Manifold as a background reference for https://topology.pi-base.org/properties/P000123, which does mention the case $n=0$ in passing and talks about non-constant dimension in general.

**Comment by danflapjax** [comment]
Thanks for the suggestions! I did notice that detail about how, as locally Euclidean was worded, the dimension was permitted to vary, but I suppose I dismissed it as ambiguous in favor of the more common version. Using a more general definition sounds perfectly fine though. Mostly I'm glad to be clarifying the definition given, whatever it ends up being.

**Comment by prabau** [comment]
@StevenClontz So it does not fall through the cracks, when you get the chance, we'd appreciate your input on the above, specifically the definition of Locally Euclidean.

**Comment by StevenClontz** [comment]
> https://en.wikipedia.org/wiki/Wikipedia:Be_bold

😁 love it - thanks for your time making a contribution @danflapjax !

And thanks for the ping @prabau - these are all in the queue but I added some last-minute travel this weekend. Will put some time on this particular PR right now.

**Comment by StevenClontz** [comment]
Okay, right now the biggest blocker for this PR is editing https://topology.pi-base.org/properties/P000123 to clearly state what we're assuming here.

I think it seems clear that we should allow $n\geq 0$, so the proposed fix (replacing non-empty with multiple points) is important.

What's less clear is whether we should be fixing the dimension $n$ at the space level, or point level. I'd like to give preference to a contributor that's more likely to use the definition than myself. (We can always add the other property later if it's needed.) So I think it's your call @danflapjax - the only requirement I'd make is that we want a reasonable citation to the literature that aligns with your call. Can you update the PR to include appropriate edits to P123, adding the citation?

Aside: we should probably add "manifold" as an alias to P123.

**Comment by prabau** [comment]
For both "locally Euclidean" and "topological manifold" there could be two terminologies, one without qualifier:
- "locally Euclidean"
- "manifold"

and one with qualifier specifying the dimension up front:
- "locally Euclidean of dimension $n$" (as used in Lee for example)
- "$n$-manifold" (as in Munkres p. 225 for example)
- "$n$-dimensional topological manifold", "$n$-dimensional manifold", "$n$-manifold" (all in Lee p. 39)

"locally Euclidean" without qualifier would mean no specific dimension specified (and the local dimension can vary from point to point).  But given a space $X$ that is locally Euclidean in this sense, for example a "manifold", each of its subsets $X_n$ of points with local dimension $n$ is open, and $X$ is the topological direct sum of the $X_n$.  So we don't lose anything essential by restricting ourselves to cases where the dimension is fixed up front.

But in that case, we should change the names slightly to make that clear.  For example:
- "topological $n$-manifold"
- "locally $n$-Euclidean"

The $n$ is understood to be fixed up front, so constant over the whole space.

I would be in favor of this change where the dimension is constant everywhere.  But the names also need to be changed accordingly.

In addition:
- not add "Manifold" as an alias for "locally Euclidean"
- for Topological manifold (https://topology.pi-base.org/properties/P000124), change "A locally Euclidean space that is Hausdorff and second-countable" to "A {P123} space that is {P3} and {P27}".  That will make it easier to navigate to the relevant properties from that page.
- P124: also fix the page for Munkres (it's page 225 and not 316).
- Add Lee to the refs for locally $n$-Euclidean
- Add Lee to the refs for topological manifold
- Add https://en.wikipedia.org/wiki/Manifold to the refs for topological manifold

What do you guys think?

**Comment by StevenClontz** [comment]
Thanks @prabau - I missed the second-countable requirement for a manifold due to the wording of that wiki article. (Actually I just made an edit to the first paragraph on Wikipedia to be clear that the local Euclidean property is necessary but not sufficient.)

I'm okay with any of the following (modulo all of @prabau's suggestions e.g. adding citations):

1. Leave P124 as "topological manifold" and P123 as "locally Euclidean", and clarify that the dimension can vary at each point.
2. Rename P124 as "topological $n$-manifold" and P123 as "locally $n$-Euclidean", and clarify that the dimension must be the same across the space.
3. Add "topological $n$-manifold" and "locally $n$-Euclidean" as new properites, and make all the necessary clarifications on all four properties.

Which of the three is up to @danflapjax if they're still interested and can update the PR appropriately in the next week. If not, it can be up to whoever gets around to putting a bow on this first. :-)

**Comment by StevenClontz** [comment]
> Actually I just made an edit to the first paragraph on Wikipedia to be clear that the local Euclidean property is necessary but not sufficient

and of course it was reverted 🙄

**Comment by StevenClontz** [comment]
Implemented as #539, thanks again @danflapjax!

**Comment by prabau** [comment]
Thanks @danflapjax for the improvement to pi-base.  Feel free to share other contributions in the future or mention things that should be fixed.  We appreciate it.

**Pull request closed without merging**
