### PR TITLE
Update T10 about extremally disconnected

### LINKED ISSUE #533: Tighten up theorem T10
*Modify the below template for your theorem suggestion:*

## Modify Theorem [T10](https://topology.pi-base.org/theorems/T000010) 

to say that if a space is:

- [P49](https://topology.pi-base.org/properties/P000049) (extremally disconnected)
- [P84](https://topology.pi-base.org/properties/P000084) (locally Hausdorff)

then it is [P167](https://topology.pi-base.org/properties/P000167) (sequentially discrete).

## Rationale

The current version, which says [P53](https://topology.pi-base.org/properties/P000053) (metrizable) and [P49](https://topology.pi-base.org/properties/P000049) (extremally disconnected) implies [P52](https://topology.pi-base.org/properties/P000052) (discrete), would be recoverable, since we have [T416](https://topology.pi-base.org/theorems/T000416) (sequential and sequentially discrete imply discrete).

In any case, the current proof appears incorrect so some modification needs to be done anyway.  

The new proof will allow discovery of $\neg(\text{extremally disconnected})$ on nonmetrizable spaces such as the recently added [S131](https://topology.pi-base.org/spaces/S000131) (Sequential fan with $\omega$-many splines.)

## Proof/References

The result is given by Ulli's answer to this question [this Math.StackExchange post](https://math.stackexchange.com/q/4751580/1210477).  While stated for Hausdorff spaces, the proof immediately applies to locally Hausdorff spaces by restricting to a Hausdorff neighborhood of the limit point.

### PR DESCRIPTION
**Pull request by marswill**
closes #533

### CODE REVIEW

**Comment by prabau** [comment]
Looks good.

One minor thing.  When a mathse reference refers to a specific mathse answer to a mathse question, we link to that particular answer (which is the case here), and we usually put in the "name" field "Answer to ..." like this: 
> `name: Answer to "What separation is required to ensure extremally disconnected spaces are sequentially discrete?"`

See https://topology.pi-base.org/spaces/S000172/references for comparison.  But it's no big deal.  Let me know either way and I'll approve.

**Comment by prabau** [comment]
I changed the PR title to something more descriptive.  If we later look at the list of PRs that got merged, it's good to have a more informative title to know what that was about without having to open each PR.

**Comment by marswill** [comment]
>Let me know either way and I'll approve.

I'll fix it this time, to help me get in the habit of doing it the right way.

**Comment by marswill** [comment]
Actually, wait, I think the citation was the same as the question...

**Comment by marswill** [comment]
Hmm, I think I was just confused, I guess there must be a convention on stack exchange where the reference to the question is the same number as that of the first answer?  That might explain things.  

In any case, if it still doesn't look right let me know @prabau, I'm pretty sure I did it correctly.

**Review by prabau — APPROVED** [review]

**Comment by StevenClontz** [comment]
For clarity: here's the ID for a question:

image

To get a direct ID to an answer (can also be used to get the ID of a question):

image

**Pull request merged**
