### PR TITLE
add pseudonormal

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
This could use a counterexample to https://topology.pi-base.org/theorems/T000401

According to https://dantopology.wordpress.com/2014/02/17/pseudonormal-spaces/ we could add $\omega_1\times(\omega_1+1)$.

**Comment by prabau** [comment]
I added T404 [pseudonormal + countable ==> normal] as another basic result.

Both T404 and T401 are "immediate from the definitions", so they have no refs.  Is a ref needed in such a case?  If yes, we could add just a ref to the definition.

I have expanded the README for the property itself (https://topology.pi-base.org/properties/P000165).  The reference from Wikipedia did not seem very good in this case, so I added a few.  The book "Pseudocompact topological spaces" seems pretty interesting, but can you fill our the MR field?

See p. 8: https://books.google.com/books?id=fsRlDwAAQBAJ&pg=PA8&dq=pseudonormal+topology&hl=en&newbks=1&newbks_redir=0&sa=X&ved=2ahUKEwj78rLp8rmAAxXEEVkFHVTVD7kQuwV6BAgIEAY#v=onepage&q=pseudonormal%20topology&f=false

That page mentions a few other things like:
- countably compact ==> pseudonormal
- pseudonormal + pseudocompact ==> countably compact

We should check that and add it maybe in another PR.

**Comment by prabau** [comment]
Hmm, pi-base tells me right away that the last two results are not true, even for Hausdorff spaces. Not good.

**Comment by Moniker1998** [comment]
@prabau in that book every space is considered to be Tychonoff. Author mentions that

**Comment by prabau** [comment]
> in that book every space is considered to be Tychonoff. Author mentions that.

That's good.  It was surprising that the results would fail, as the authors are well known topologists.

**Comment by Moniker1998** [comment]
Another name: weakly normal

**Comment by prabau** [comment]
> Another name: weakly normal, see e.g. Dugundji

That would have nothing to do with the notion in https://www.sciencedirect.com/science/article/pii/S0166864196001150, right?

**Comment by Moniker1998** [comment]
it's a different property

**Comment by Moniker1998** [comment]
I found somewhere that regular countably paracompact space is pseudo-normal.
Thus if we were to find a regular countably paracompact pseudocompact but not countably compact space, then this would be an example of the theorem failing in general.
All the corkscrews included in Steen and Seebach seem like good candidates, but their entries on pi-base seem very incomplete...

**Comment by StevenClontz** [comment]
> Both T404 and T401 are "immediate from the definitions", so they have no refs. Is a ref needed in such a case? If yes, we could add just a ref to the definition.

Adding this to the next community call.

**Comment by StevenClontz** [comment]
Good comments here but don't want the PR to get too bloated, so maybe other improvements can be made later. Since @prabau made some tweaks, can @lyengulalp or @ccaruvana approve and merge?

**Comment by StevenClontz** [comment]
Paging Drs. @ccaruvana and @lyengulalp 😆

**Comment by ccaruvana** [comment]
Sorry for the delay. I will check on this and https://github.com/pi-base/data/pull/407 soon.

One thing I'm noticing here right off the bat is that there is a conflicting file: paraphrased S76/prop/P13

**Comment by StevenClontz** [comment]
I've merged in `main` to address the conflict.

**Comment by ccaruvana** [comment]
Thanks @StevenClontz ! Out of curiosity, why did P65 (cardinality continuum) get removed from S76? It isn't deduced from any other properties, it doesn't seem.

**Comment by StevenClontz** [comment]
That's a mistake I made while merging. Will add it back in.

**Review by ccaruvana — APPROVED** [review]

**Comment by ccaruvana** [comment]
Also out of curiosity (but I did agree with it), why was P116 Pseudocomplete deleted (if not just the fact that there are no theorems/spaces referencing it)?

**Pull request merged**
