### PR TITLE
add result on cardinality bound

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
I'm sure there's a textbook reference for this, but don't have the ability to find one at the moment.

**Comment by Moniker1998** [comment]
The inequality $|X|\leq d(X)^{\chi(X)}$ is given by Pospisil (in particular, instead of separable we only need $d(X)\leq\mathfrak{c}$)
See "Handbook of set-theoretic topology", chapter 1, theorem 4.4

**Comment by Moniker1998** [comment]
While you're at it, you should add the same theorem for Lindelof first-countable Hausdorff spaces.
This is given from the famous inequality of Arhangelskii $|X|\leq 2^{L(X)\cdot \chi(X)}$, again for Hausdorff spaces.
See the same book, same chapter, theorem 4.5

**Comment by prabau** [comment]
Also Willard 16F(1) or Engelking 1.5.3.

**Comment by prabau** [comment]
I was wondering if the hypothesis T2 can be relaxed to T1, and it doesn't seem like it can.  Please double check me on this.

One can modify the "telophase topology" (https://topology.pi-base.org/spaces/S000065) or the "line with two origins" (https://en.wikipedia.org/wiki/Non-Hausdorff_manifold#Line_with_two_origins) to have an arbitrary number of copies of the special point.  The result will be T1, separable and first countable and with arbitrarily high cardinality.

In any case, in a separate PR we should add the line with two origins and that variant above, as it gives a good example of locally Euclidean but not T2 (so not a topological manifold).

**Comment by prabau** [comment]
> Would those be separable still?

I think it would be, because the subset $\mathbb Q$ meets every neighborhood of every point.

**Comment by StevenClontz** [comment]
Ha, yes of course, it's the end of a long day at the MAA conference.

**Comment by prabau** [comment]
I'll try to do a PR for that.

**Comment by StevenClontz** [comment]
I think I've plucked the low-hanging fruit if @prabau approves.

BTW those examples showing that $T_1$ is insufficent for T401 are not even US. Looking at https://math.stackexchange.com/questions/2995939/a-first-countable-separable-hausdorff-space-has-at-most-the-continuum-cardinali I'm betting US is suffiicent, rather than T2. But that can be done separately.

**Comment by StevenClontz** [comment]
Well it wasn't necessary: we already have https://topology.pi-base.org/theorems/T000230 so of course anything that assumes T2+first-countable could have US+first-countable instead.

**Review by prabau — APPROVED** [review]

**Pull request merged**
