### PR TITLE
P109: Monotonically normal

### PR DESCRIPTION
**Pull request by prabau**
Two new properties:
- P108: Hereditarily collectionwise normal
- P109: Monotonically normal

together with related theorems.  This covers most theorems proposed in #927.

I have assumed T1 as part of the property, as it is needed for the equivalence of definitions (1) and (2) of monotonic normality, and it seems to be always assumed in papers.

### CODE REVIEW

**Comment by david20000813** [comment]
I've also mentioned this before in #927, where I listed some additional theorems not covered by #1005 and provided references for those theorems.

**Comment by Moniker1998** [comment]
Sorry @david20000813 I didn't see that you have raised the same issue. I've closed mine.

**Comment by prabau** [comment]
For https://topology.pi-base.org/properties/P000109 I have added at the end a section "Meta-properties".
Mainly because I needed to state somewhere that P109 was hereditary, for some of the proofs of the theorems.

But it's an example of something easy that could be done more generally.  (We had discussed possible web development doing something more fancy at some point, with the help of not-Abram?, but that was probably too much.)

Would be curious to see what you think.
@StevenClontz and others

**Comment by prabau** [comment]
> Would "monotonically T 4 " be appropriate as an alias for T109, to emphasize the assumption of T 1 ?

No, please.  _Everybody_ in the literature uses "monotonically normal" with the current meaning, i.e., with the T1 assumption (same as T4 in this case).  This is not a property meant to be appreciated by topology beginners, so no need for this alias.

It's similar to the notion of $\aleph_0$ space or $\aleph$ space, etc, where everybody assume T3.

**Comment by StevenClontz** [comment]
FWIW, I lightly disagree (authors get away with bad names in papers where we should not, since they aren't trying to catalogue everything in the same database), but not enough to push the point further.

**Comment by Moniker1998** [comment]
I don't think "monotonically $T_4$" would be appropriate for the following reason.

When we say "monotonically normal" we mean that the property of normality is monotone. But being $T_4$ is both property of normality and of being $T_1$. Saying that something is monotonically $T_4$ would seem to imply we are trying to encapsulate both of those properties in a monotone way, and not just normality.

**Comment by prabau** [comment]
To expand a little more on this, everybody in the literature that studies "monotonically normal" includes the T1 assumption. If we do the same, that means we will also restrict ourselves to spaces that are T1 (actually T4 and even T5) when studying this concept.  But that's already a rich theory with many beautiful theorems.

It is possible that one could relax this and out of curiosity study what happens without the T1 assumption.  But nobody has bothered to do so in the literature it seems, maybe because some of the important theorems are not true anymore?  I have not thought about it, so I don't know.

In any case, if suddenly the literature has a few papers without the T1 assumption, we can change things/(add an alias) at that time.  In the mean time, I think there is already plenty of interesting things as is.

And it's a little similar to $\aleph_0$ space = T3 + countable $k$-network.  The T3 condition is assumed because it makes things nicer and there are plenty of interesting results already in this case.  So everybody studying these spaces goes along with this assumption.

**Comment by david20000813** [comment]
> Sorry @david20000813 I didn't see that you have raised the same issue. I've closed mine.

@Moniker1998 No worries, it did get buried quite deep in the list of issues. Yours also listed $T_5$ and collectionwise normal as consequences of monotonically normal, which I didn't list in my issue.

**Comment by david20000813** [comment]
I think we can add the final theorem suggested in my issue in this PR, namely, Monotonically normal => not Dowker (or equivalently, Monotonically normal => Countably paracompact, as Dowker is equivalent to $T_4$ + not Countably paracompact). It's just a direct citation: Theorem 2.3 of Chapter 17 of [DOI: 10.1016/C2009-0-12309-7](https://doi.org/10.1016/C2009-0-12309-7).

**Comment by david20000813** [comment]
Otherwise, I just have one concern: For hereditarily collectionwise normal, Problem 5.5.1(a) of Engelking only proves the characterizations are equivalent when the space in question is $T_1$. Is the equivalence clear without the $T_1$ assumption? I can easily see how the corresponding equivalence works for completely normal, but I don't see how this is proved for hereditarily collectionwise normal.

**Comment by prabau** [comment]
> Otherwise, I just have one concern: For hereditarily collectionwise normal, Problem 5.5.1(a) of Engelking only proves the characterizations are equivalent when the space in question is T 1 . Is the equivalence clear without the T 1 assumption? I can easily see how the corresponding equivalence works for completely normal, but I don't see how this is proved for hereditarily collectionwise normal.

The equivalence between the characterizations for hered. coll. normal is not hard to prove directly.  That does not need T1 in any way.  The only reason T1 is assumed is because Engelking assume T1 as part of the definition of collectionwise normal.

(That's one of the annoying things about Engelking.  He makes definitions with overly restrictive separation axioms, like normal spaces are T2, compact spaces are Hausdorff, Lindelof spaces are regular, etc.  And then when he states theorems, he makes these extra assumptions, but it's never clear if it's really needed in the argument or if it's just to satisfy the definitions.)

Anyway, we can add a mention that T1 is not needed for this equivalence.  I can see what the original article of McAuley says.  If needed, we could do a mathse post for the equivalence?

**Comment by prabau** [comment]
@david20000813 Regarding Dowker, we should add the version [monotonically normal => countably paracompact].

I purposefully did not add the theorem as I would like to take the opportunity to understand the theorem myself. I started reading the proof that [LOTS => countably paracompact] but haven't finished it.  The proof for monotonically normal seems even more involved.  Do you have any high level insight about it?

What we can do for now it to release this PR without it, which will already be useful.

**Comment by prabau** [comment]
Hereditarily collectionwise normal: McAuley (https://zbmath.org/0109.15301) only says "It is not difficult to show that ...".

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/4737011/definition-of-hereditarily-collectionwise-normal-spaces-using-separated-families

May need a fleshed out answer there.

**Comment by david20000813** [comment]
> @david20000813 Regarding Dowker, we should add the version [monotonically normal => countably paracompact].
> 
> I purposefully did not add the theorem as I would like to take the opportunity to understand the theorem myself. I started reading the proof that [LOTS => countably paracompact] but haven't finished it. The proof for monotonically normal seems even more involved. Do you have any high level insight about it?
> 
> What we can do for now it to release this PR without it, which will already be useful.

@prabau I haven't fully read the proof myself. I suppose in that case we can wait until we get a better understanding of how the proof works before adding that then.

**Comment by david20000813** [comment]
> Hereditarily collectionwise normal: McAuley (https://zbmath.org/0109.15301) only says
> 
> > "It is not difficult to show that complete collectionwise normality is equivalent to hereditary collectionwise normality in a topological space."
> 
> Basically it's the same type of arguments to show the equivalence between "hereditarily normal" and "completely normal" (= def. via separated sets).

Oh, I see. I chose the wrong open set for the proof. When I was thinking of proving the equivalence between hereditarily normal and completely normal, I was using the open set given by the space minus the intersection of the closures of the two separated sets. This approach cannot generalize to hereditarily collectionwise normal, since then you would need to subtract infinitely many closed sets. But yeah, the general outline in the MSE question works.

**Comment by david20000813** [comment]
> https://math.stackexchange.com/questions/4737011/definition-of-hereditarily-collectionwise-normal-spaces-using-separated-families
> 
> May need a fleshed out answer there.

That would be the best, yeah. Now that I see what the open set is supposed to be, I agree that the proof is relatively easy, but it would be good to have an explicitly written down proof for citation.

**Comment by prabau** [comment]
> > https://math.stackexchange.com/questions/4737011/definition-of-hereditarily-collectionwise-normal-spaces-using-separated-families
> > May need a fleshed out answer there.
> 
> That would be the best, yeah. Now that I see what the open set is supposed to be, I agree that the proof is relatively easy, but it would be good to have an explicitly written down proof for citation.

I'll write up something as an answer to the mathse post later today.

**Comment by prabau** [comment]
I have posted an answer to https://math.stackexchange.com/questions/4737011 and will update the reference for pi-base.

**Comment by prabau** [comment]
@Moniker1998 Definition (2) is equally important as Definition (1).  In fact, many of the later paper only give Def (2) or a variant for monotonically normal.  It also provides a nearly obvious proof that metrizable spaces are monot. normal. (I added one sentence to T669 to make that clear.)  So I think it's important to keep the proof of T669 as is, to show the simplicity of the Def (2) approach.

See also http://at.yorku.ca/b/ask-a-topologist/2003/0383.htm that I did not mention for T669.  I did mention it though as an additional link for T629 (proving that LOTS are monotonically normal).  It uses Def (2) to prove the result. And it's really very close to Heath-Lutzer-Zenor's approach, who also do not use Def (1) for that.

https://topology.pi-base.org/properties/P000109: The section at the end about "Equivalence between the two definitions" gives references and shows why it's equivalent.  If you have any questions about that part, please ask.

**Comment by Moniker1998** [comment]
> Definition (2) is equally important as Definition (1). In fact, many of the later paper only give Def (2) or a variant for monotonically normal. It also provides a nearly obvious proof that metrizable spaces are monot. normal. (I added one sentence to T669 to make that clear.) So I think it's important to keep the proof of T669 as is, to show the simplicity of the Def (2) approach.

I understand that the approach might be simple, but I don't understand why not to mention the alternative.

**Comment by prabau** [comment]
Do you still have a doubt about the equivalence between the two definitions?

**Comment by Moniker1998** [comment]
I don't understand what you mean? I never had doubts about the definition.

**Comment by prabau** [comment]
So there is no problem then in using the simplest and easiest proof available then.

It's similar to #1030.  There was no need to use fancy notions there, as there was a simple direct proof of the result.

**Comment by yhx-12243** [comment]
I discover that there are too few sufficient conditions for Hereditarily CWN and that'll end up lots of spaces (even finite ones)  are `?Hereditarily CWN`, maybe we should do a cleanup or add some sufficient conditions.

**Comment by Moniker1998** [comment]
There are finite spaces which aren't normal: https://topology.pi-base.org/spaces/S000007

**Comment by prabau** [comment]
@yhx-12243 Your observation is correct, but this will not happen in this PR.  Better release what we have now and continue with additional PRs.

**Comment by prabau** [comment]
Suggestion: If people are satisfied with what is here so far, one of you could approve.  And then we can write more PRs involving monotonically normal spaces.

And the first person who manages to read and understand the proof of [monotonically normal => countably paracompact] can write a PR for it.

**Review by david20000813 — APPROVED** [review]

**Comment by david20000813** [comment]
I think I've now more or less understood the proof of "Monotonically normal => Countably paracompact". The proof in the source I cited has some minor typos, as well as some weird over-complications. I'll present a rewrite of the proof and a high-level outline when I write the PR for the theorem.

**Pull request merged**
