### PR TITLE
Semi-Hausdorff

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
This is another example of a property properly between T2 and T1. I'm trying to complete the picture as best I can: we have a nice chain of implications for T2, KC, WT2, US, T1, but, Locally Hausdorff, Semi-Hausdorff, and Retracts are Closed are properties that may or may not fall in line as far as I can tell.

**Comment by prabau** [comment]
Should this PR be reviewed separately from #420?

In any case, I think the terminology "semi Hausdorff" here is not optimal.  "Semi Hausdorff" has been used in other contexts in the literature, specifically for spaces where distinct points can be separated by disjoint semi-open sets.  The use of that terminology in Banakh's paper is possibly made up for the occasion.  So I have asked about it in a comment to this:
https://mathoverflow.net/a/435864

Let's see what he replies.  It's maybe a similar situation as the term "P-space".  Morita had also introduced the term "P-space" with a completely different meaning, and now P-spaces in the sense of Morita are called "Morita P-spaces" (see Encycl. of General Topology, p. 202).  Similarly, one possibility would be to call the property something like "Banakh semi-Hausdorff" or "(Banakh) semi-Hausdorff"?

**Comment by StevenClontz** [comment]
> Should this PR be reviewed separately from #420?

Yeah - I'm actually working on a preprint related to this PR, and I'm using pi-Base to organize my work as I go. But I didn't want to blow this up too big, so I'm leaving the rest of the work as a draft PR until this is resolved and merged back into #420.

**Comment by prabau** [comment]
Taras Banakh replied.  The paper https://www.ams.org/journals/proc/2017-145-03/S0002-9939-2016-13318-2/ he mentioned seems very interesting.  See in particular the diagram after Definition 2 on p. 1376 that summarizes many implications between properties.  We should check how much of this is already in pi-base.  This article also seems a better reference for the notion of "semi-Hausdorff".  What do you think?

**Comment by prabau** [comment]
Alternatively, we just go with "semi-Hausdorff" in the current sense in pi-base for now.  I personally don't care too much about semi-open sets, but if pi-base ever gets to that one, we can revisit and change as necessary.

**Comment by StevenClontz** [comment]
I need to look into the semi-open characterization. I like that semi-Hausdorff aligns with our existing semiregular property, and we can always do "Semi-Hausdorff (Banakh)" vs "Semi-Hausdorff (name)". or maybe "Semi-Hausdorff (regular)" vs "Semi-Hausdorff (semiopen)"?

**Comment by StevenClontz** [comment]
> This article also seems a better reference for the notion of "semi-Hausdorff". What do you think?

I think so. Moving this back to draft until I've had a chance to review things a bit and make appropriate changes.

**Comment by prabau** [comment]
> I need to look into the semi-open characterization. I like that semi-Hausdorff aligns with our existing semiregular property, and we can always do "Semi-Hausdorff (Banakh)" vs "Semi-Hausdorff (name)". or maybe "Semi-Hausdorff (regular)" vs "Semi-Hausdorff (semiopen)"?

Yeah, or for now we could do "Semi-Hausdorff" by itself with "Semi-Hausdorff (Banakh)" as an alias.

**Comment by StevenClontz** [comment]
I added the Proc AMS reference as well as the more recent paper. I don't think folks will be searching for the property using "Banakh", so with these references I don't think an alias is necessary today. (And perhaps the co-author should be included as well when/if we do.)

**Comment by StevenClontz** [comment]
Actually I think `spaces/S000184/properties/P000099.md` is bogus, due to changes made in the paper to *make* the space US.

In general this space has a lot going on beyond the immediate need at hand. I still wonder if a simpler counterexample can be found...

**Comment by StevenClontz** [comment]
For now I've dropped Banakh's space - I could add the existing example that's RC+SemiT2 but not KC, but it's a bit technical and I'm trying to see if I can work out a more elegant (for this purpose) construction that gets RC+SemiT1 but not US.

**Review by prabau — APPROVED** [review]

**Pull request merged**
