### PR TITLE
k2 Hausdorff

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
This completes everything in #428 except RC-not-US.

**Comment by StevenClontz** [comment]
More references for $k_2$-Hausdorff as a concept is requested here: https://mathoverflow.net/questions/453848/reference-for-k-hausdorff-in-terms-of-compact-t2-images

**Comment by prabau** [comment]
trivial comment: should the aliases for P170, P171 be "k-Hausdorff" without the dollar signs around the "k" ?

**Comment by prabau** [comment]
The following reference looks closely related.  It would be very interesting to take a look.  Unfortunately I don't have access, but maybe you can get it from your university.

https://zbmath.org/0463.54016
https://doi.org/10.1007/BF01238530

**Comment by StevenClontz** [comment]
> https://doi.org/10.1007/BF01238530

No dice - our subscription only starts with stuff from the 90s.

**Review by prabau — APPROVED** [review]

**Pull request merged**
