### PR TITLE
Add Strongly Choquet and theorems

### LINKED ISSUE #813: Completely metrizable theorem
>  Whether the metric fan is completely metrizable came up in our call today. Indeed, for any almost-discrete metrizable space we can choose a metric where the distance between any two isolated points is greater than some fixed $\epsilon>0$, so any Cauchy sequence is either eventually constant or converges to the one non-isolated point. (Constructively: given some metric $d(x,y)$, take $d\prime(x,y)$ that equals 1 when $x$ and $y$ are both isolated and $\min(1,d(x,y))$ otherwise.) Since this is a theorem we can add later, I see no need to add a trait now.

_Originally posted by @danflapjax in https://github.com/pi-base/data/issues/804#issuecomment-2423719412_

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #813.

Answers https://topology.pi-base.org/spaces?q=Almost+discrete%2B%24T_1%24%2BFirst+countable%2B%7ECompletely+metrizable and https://topology.pi-base.org/spaces/S000202/properties/P000055

Full disclosure: my copy of Kechris is in the office so I'm trusting wikipedia and my vague memories that all this kind of thing is in there.

### CODE REVIEW

**Comment by david20000813** [comment]
This is nice. Are we not adding almost discrete => strong Choquet, Cech complete => strong Choquet (superseding T641 and T642, and then T643 can supersede T132)? Also, the link http://at.yorku.ca/b/ask-a-topologist/2002/0254.htm you posted in #813 seems to imply strong Choquet => Baire, which can supersede T135 if Cech complete => strong Choquet is also added

**Comment by david20000813** [comment]
Cech complete => strong Choquet follows from compact $T_2$ being strong Choquet and Exercise 8.16 (iii), which says nonempty $G_\delta$ subsets of strong Choquet spaces are strong Choquet.

**Comment by david20000813** [comment]
Also, since strong Choquet is usually defined for nonempty spaces, and the strong Choquet game doesn't make sense for empty space anyway, we might want to add nonempty throughout these theorems.

**Comment by StevenClontz** [comment]
Thanks for your comments @david20000813, let me work on this a bit.

**Comment by david20000813** [comment]
I've renumbered T642 to T646 to avoid conflicts with the just merged #961. Other than that, this looks all good.

**Review by david20000813 — APPROVED** [review]

**Pull request merged**
