### PR TITLE
add S199 quasi-sober, edit sober definition

### PR DESCRIPTION
**Pull request by StevenClontz**
I could have proven S199 sober, but we get it for free as we already know the space is $T_0$.

Suggested by @david20000813 in https://github.com/pi-base/data/pull/934#issuecomment-2497019867

### CODE REVIEW

**Comment by StevenClontz** [comment]
I added a direct proof that S199|P201 in the file for quasi-sober, because the deduction will use quasi-sober itself if this is merged!

**Comment by prabau** [comment]
Sorry, but replacing "nonempty" with "non-{P137}" in the argument is just extreme and not helpful, in my opinion.

**Comment by StevenClontz** [comment]
I used it for the definition of quasi-sober earlier, so either way they should be made consistent.

I don't feel strongly one way or another so I'll remove the cross-reference.

**Review by david20000813 — APPROVED** [review]

**Comment by prabau** [comment]
I did not realize quasi-sober (P192) had been changed.

The previous version for both sober and quasi-sober was very clear, using the terminology of "irreducible subspace", which is common in this context.  And it did have an explanation of "irreducible" and a explicit link to "hyperconnected" for the reader's convenience.  Both properties were also parallel to each other.

> Every nonempty irreducible closed subset of $X$ is the closure of exactly one point of $X$; that is, every nonempty irreducible closed subset has a unique *generic point*.  Here, a subset of $X$ is called *irreducible* if it is {P39} with the subspace topology.

I understand we wanted to link to "generic point" though.

**Comment by prabau** [comment]
@david20000813 comments on the above?

**Comment by prabau** [comment]
You beat me by one second :-)

**Comment by david20000813** [comment]
@prabau Ah, yeah, I already merged. I find the new version is fine as is, but I do agree that using irreducible is more common in this context. Perhaps we can just add the reference to irreducible back in?

**Comment by david20000813** [comment]
Like, say every nonempty irreducible ({P39}) closed subspace is {P201}.

**Comment by prabau** [comment]
I also find the new version for sober:

> Every nonempty [P39: Hyperconnected](https://topology.pi-base.org/properties/P39) closed subspace of $X$ is
[P201: Has a generic point](https://topology.pi-base.org/properties/P201), witnessed by exactly one generic point.

to be not as clear.  The old version said something like:

> Every nonempty irreducible closed subset of $X$ is the closure of exactly one point of $X$; that is, every nonempty irreducible closed subset has a unique *generic point*.

which seems easier to grasp.  The new version is convoluted, with the witnessing business, just to introduce a link to generic point (such a link could be introduced differently).

Would both of you object if I try a PR to change things a bit?

**Comment by StevenClontz** [comment]
I have no problem with improving my prose here, as long as we do keep the cross-reference to "has a generic point" somehow.

**Pull request merged**
