### PR TITLE
Almost discrete (cont'd #821)

### PR DESCRIPTION
**Pull request by yhx-12243**
As discussed in #1058, open the discussion for the remaining part of #821.

### CODE REVIEW

**Comment by prabau** [comment]
@yhx-12243 Can you explain what this PR is about?  @danflapjax had initially written a "monster" PR #821 with too many results to reasonably deploy in one go.  Part of it was then separated and merged.  A few remaining theorems remained and I had made some comments about them.  Then things sat like this for a long time.  Later @danflapjax may have done more work?  But there was never any followup discussing the remaining comments, so I was waiting for him to split up the work into manageable pieces and re-review them one at a time.

And now you come in and do another big PR.  Please tell me what's the plan here?  And did you even discuss this with @danflapjax ?

**Comment by yhx-12243** [comment]
> @yhx-12243 Can you explain what this PR is about? @danflapjax had initially written a "monster" PR #821 with too many results to reasonably deploy in one go. Part of it was then separated and merged. A few theorems remained pending and I had made some comments about them. Then things sat like this for a long time. Later @danflapjax may have done more work? But there was never any followup discussing the remaining comments, so I was waiting for him to split up the work into manageable pieces and re-review them one at a time.
> 
> And now you come in and do another big PR. Please tell me what's the plan here? And did you even discuss this with @danflapjax ?
> 
> And also, why repeat this huge list of commits from before???

(i) Because his original pull request #821 is closed instead of being Draft, so we decided to add a continuation, and we can mark it as a draft.
(ii) Because I reuse the branch and remove the merged theorem, only leave the theorem can't deduced by the pi-base now.

**Comment by prabau** [comment]
When you say "we decided", do you mean "you decided"?  I.e., did you coordinate with @danflapjax ?

Also, the understanding we had from discussion with @danflapjax was that he was going to split this into several smaller PRs to be discussed individually.  Why bypass what he was going to do?

And did you take into account all the pending issues from #821?

**Comment by danflapjax** [comment]
I wouldn't mind at all if you were to work on anything that I have begun to bring it to completion, as this is a collaborative project. However, if you do so I ask that you do it with diligence and care. This pull request instead feels reckless. The previous PR was closed with the intention of splitting up the contributions into smaller chunks which can be more efficiently reviewed and revised, but this PR just has the exact same changes without any of the commented suggestions actually incorporated. Again, please feel free to take one or a few of the theorems and include them in a well-made PR of your own, but keep in mind their context when doing so.

**Comment by StevenClontz** [comment]
Thanks for your intent to get these results added to $\pi$-Base @yhx-12243, but I agree: the discussion in the previous PR was that this needed to be split up into smaller PRs for ease of review. If you'd like to help work on this, please choose a small portion to contribute in a clean PR.

**Pull request closed without merging**
