### PR TITLE
add P84 to S165, add T435, add T436 (#525)

### LINKED ISSUE #523: Theorem Suggestion: Include theorems for deducing and upgrading $k$-space properties when locally Hausdorff
---

## Changes
**New Theorem 1.** ($\text{locally Hausdorff} + \text{locally compact} \implies CG3$.) If a space is:

- [P84](https://topology.pi-base.org/properties/P000084)
- [P130](https://topology.pi-base.org/properties/P000130)

then it is [P142](https://topology.pi-base.org/properties/P000142).

---

**New Theorem 2.** ($\text{locally Hausdorff} +CG2 \implies CG3$.) If a space is:

- [P84](https://topology.pi-base.org/properties/P000084)
- [P141](https://topology.pi-base.org/properties/P000141)

then it is [P142](https://topology.pi-base.org/properties/P000142).

----

**Property Addition.**  (One point compactification of Arens-Fort space is locally Hausdorff).  Space [S165](https://topology.pi-base.org/spaces/S000165) has property [P84](https://topology.pi-base.org/properties/P000084)

-----

## Rationale

Looking at [T309](https://topology.pi-base.org/theorems/T000069), ($CGWH \implies CG3$), I was astonished to see there were no counterexamples to the converse, given the many variations on the telophase topology we have.

It seems none of these have $CG3$ deduced.

We could deduce most of these automatically via the first of the preceding theorems, and pick up the non-locally compact stragglers like [S97](https://topology.pi-base.org/spaces/S97) with the second.  (Technically we could probably get all with just the second theorem, but the first seems important and can't be deduced from the second).

Finally, adding local Hausdorff to the Arens Fort space is worth doing for its own sake, but also beneficial as it shows why we can't simply relax Hausdorff to local Hausdorff in [T60](https://topology.pi-base.org/theorems/T000060).

------

## Proof/References

These are all pretty straightforward.  

For Theorem 1, Local Hausdorff and locally compact gives a base of compact Hausdorff spaces, which therefore generate the topology.  

For Theorem 2, If $X$ is CG2 and locally Hausdorff and $A\subseteq X$ is not closed, then by CG2 we have a map $f\colon Z\to X$ from compact Hausdorff $Z$ with $f^{-1}(A)$ not closed.  Let $z\in \overline{f^{-1}(A)}\backslash f^{-1}(A)$, let $U\ni f(z)$ be a Hausdorff open neighborhood, and choose a neighborhood $V$ of $z$ with $\overline{V}\subseteq f^{-1}(U)$, then $f(\overline{V})$ is compact Hausdorff.  Since $z\in \overline{f^{-1}(A)\cap \overline{V}}\backslash f^{-1}(A)$, $f(z)\in \overline{A\cap f(\overline{V})}\backslash A$, so $f(\overline{V})\subseteq U$ is compact Hausdorff, with $f(\overline{V})\cap A$ not closed in $f(\overline{V})$.

Finally, the one point-compactification $X\^\*$ of the Arens-Fort space $X$ is locally Hausdorff, since $X$ is Hausdorff, and $\infty$ has $X\^\*\backslash\\{(0,0)\\}$ as a Hausdorff neighborhood (note this neighborhood is homeomorphic to $\omega+1$).

------

If it's alright I'm going to assign this one to myself so I can go through all the steps and get a little more familiar with pi-base in general.

### PR DESCRIPTION
**Pull request by marswill**
closes #523

### CODE REVIEW

**Comment by prabau** [comment]
I see you finally got some appropriate branch in the official repo for this.

Wondering about your previous #525 that got merged somewhere?  I am pretty sure you could create a branch off of your previous `marswill:CG3localH` without having to create a fake PR for it.

**Comment by marswill** [comment]
@prabau Sorry, I think you're right, making a branch off of my local branch was almost certainly possible and the right way to do this. The truth is it's been awhile since I used github and I'm a little green in general on development.

In the future in this kind of situation I'll do it that way.  As for right now is it ok to leave things as is you think?

**Comment by prabau** [comment]
It's absolutely fine to leave things as is and move forward with #526.  I just thought it's good to take the opportunity of this simple PR to iron out the easiest way to do things.

FYI here are two ways I use for myself.  (1) I have a local copy of the repo on my computer and I create a branch locally.  Then I commit some changes in that branch (using the vscode editor on Windows).  And from vscode it allows me to push my changes "upstream", which I set up to be the official pi-base repo.  That is what creates this new branch in the official repo itself.  (2) Alternatively, from looking at the changes in github (in the web browser), one can open the so-called github.dev editor for example by typing a dot (`.`) and from there at the bottom left (or somewhere else in the in-browser editor) one can clone the branch to the official repo.

I am sure there are other ways as well which I am not familiar with.  In any case, in our next zoom meeting on Feb 8 (@StevenClontz will contact you and we can change the date/time if it's not convenient for you) we can demo things in person, which may be easier.

**Comment by prabau** [comment]
For the P84 trait file for S165: We usually use $X$ to denote the space under consideration, as indicated in https://topology.pi-base.org/spaces/S000165.  So it would be preferable to rephrase slightly.  Maybe something along the lines of 
"The {S23} is open in $X$ and is Hausdorff.  And $\infty$ admits $X\setminus\\{(0,0)\\}$ as an open Hausdorff neighborhood." Feel free to change the wording as you see fit.

**Review by prabau — APPROVED** [review]

**Pull request merged**
