### PR TITLE
test switch to zbmath

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
@jamesdabbs I believe I've set up zbmath support successfully at https://github.com/pi-base/web/pull/147 but maybe our CI/CD isn't synced up there?

**Comment by prabau** [comment]
Is zbmath accessible now?

**Comment by StevenClontz** [comment]
Figured it out for myself. Let me know what you think @prabau.

**Comment by prabau** [comment]
Not that it matters, but in #95 after discussion on the zoom call you had mentioned it was going to use `zb:`.

Question: is the value of the zb/zbmath field always parsed as being a string and not a number?  If so, are the quotes optional, i.e., are the following both accepted: `zbmath: "1052.54001"` and `zbmath: 1052.54001`?

**Comment by StevenClontz** [comment]
Now's the time to change this - I like the idea of the shorter `zb`, so let's do that. Switching to draft until that's done.

**Comment by StevenClontz** [comment]
I'll see if we can accept the numerical value and cast it to a string like we do for `mr` numbers. I'm worried there might be an issue with floating points, but maybe we're lucky and the `String()` method will return the precise string used to cast to the numerical value, and avoid `0.1+0.2 != 0.3` issues.

**Comment by StevenClontz** [comment]
`zbmath: 1052.54001` cannot be supported, because `zbmath: 1052.54000` would be simplified to `1052.54` and `"1052.54" != "1052.54000"` 😞

**Comment by StevenClontz** [comment]
@prabau I've fixed zbmath to just be zb - let me know if you have other thoughts or feel free to merge

**Comment by prabau** [comment]
Looks good.

**Review by prabau — APPROVED** [review]

**Pull request merged**
