### PR TITLE
whitespace fixes

### PR DESCRIPTION
**Pull request by prabau**
@Jianing-Song FYI, the files introduced in #647 are the ones causing a problem.  I tried to create a brand new branch based on main on my computer and it shows all these with spurious whitespace changes.

To diagnose the problem while in github.dev, before this particular fix gets merged, you can compare for example P000189.md and P000190.md.  On the botton right of the editor pane, there is an indication of the type of line endings used by the file: either LF (good) or CRLF (bad).  If it shows CRLF, you can "fix" it by clicking on it and changing it to LF, I think.

Just curious, how exactly did you create the new files like P000190.md?  Did you do a copy/paste from another good file, or from scratch? (I assume you are on Windows.)

Anyway, would appreciate is someone could approve this fix.

### CODE REVIEW

**Comment by Jianing-Song** [comment]
Ah, thanks for fixing the problem for me! Sorry for not having noticed the error.

I created the files from scratch, perhaps this was the problem.

**Comment by prabau** [comment]
@ccaruvana can you approve this?

**Comment by prabau** [comment]
@Jianing-Song if you are allowed to approve this, can you do it?

**Review by Jianing-Song — APPROVED** [review]
@prabau Yes of course! :)

**Pull request merged**
