### PR TITLE
add continuum and theorems

### LINKED ISSUE #612: New property: Continuum
The pi-base homepage https://topology.pi-base.org/ has "non-metric continua" as an example for searching spaces by properties.  Yet pi-base doesn't know what a continuum is and behind the scenes that search is manually tweaked to make things work.  If we had that property, the sample search could be simplified accordingly.

And since it's a common notion, it also seems worth adding if only to make the terminology available.  Both Willard and Engelking define a **continuum** as a compact connected Hausdorff space.

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #612

### CODE REVIEW

**Comment by prabau** [comment]
I didn't know you could add a comment with `#` for conditionals in the metadata.  That sure makes things easier to follow.  We should mention this more widely in the next community meeting.

**Comment by StevenClontz** [comment]
> I didn't know you could add a comment with `#` for conditionals in the metadata. That sure makes things easier to follow. We should mention this more widely in the next community meeting.

Of course, they could be wrong. We need a VS code plugin that live compiles the data repo and provides this kind of info without needing to seed these kinds of comments. But this seems like a reasonable stopgap in the meantime.

**Comment by prabau** [comment]
P188: The paper from Gruenhage does not seem to have anything to do with continua.  Can we use Encyclopedia of General Topology instead?

Also, we should probably add a sentence or two explaining the two commonly used conventions in the literature and what we chose for pi-base.

**Comment by StevenClontz** [comment]
Thanks, forgot to fix the reference. Agreed on adding context.

**Comment by prabau** [comment]
I just reordered the properties for T480, to put the most important two first.

**Review by prabau — APPROVED** [review]

**Pull request merged**
