### PR TITLE
use k_n for naming compactly generated properties

### PR DESCRIPTION
**Pull request by StevenClontz**
Open to discussion. See also a thread on the mathlib Zulip https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Compactly.20generated.20spaces where there's interest in formalizing these properties, and I kept crossing my eyes at the different names for different CG properties. This change aligns the CGn names with our kn-Hausdorff names.

### CODE REVIEW

**Comment by prabau** [comment]
It's good to see some names that align better with the $k_n$-Hausdorff names.  But as you know from previous discussions and the wikipedia article, authors have been pretty inconsistent in their naming.  Some using _compactly generated_, some using $k$-_space_, with different and incompatible meaning from one author to the next.  Compare May, Strickland, Rezk, as well as earler authors for example.  I came up with the CG1, CG2, CG3 as convenient abbreviations to describe things in a more careful way in the wikipedia article.  And then we introduced $k_1$-Hausdorff and $k_2$-Hausdorff by analogy.

So I am wondering, using $k_1$-space, $k_2$-space, $k_3$-space as the main names would make clearer the relation with $k_n$-Hausdorff.

And for the related P98 (Generated by countably-many compacts), we could make $k_\omega$ the main name (or should that be $k_\omega$-space? Would need to investigate what the literature is using.)  $k_\omega$ as defined in pi-base is related to $k_1$-space.  @marswill once noticed that we do not have a $k_\omega$ variant related to the other $k_n$, but we probably don't need it at the moment.

Thoughts?

**Comment by StevenClontz** [comment]
The existence of $k_\omega$ was the reason I went with CGn rather than $k_n$ - I didn't want it to seem that $k_n\Rightarrow k_\omega$ since $n<\omega$, even though $k_n\Rightarrow k_N$ for $n\leq N$.

Agreed that P98 should be in the mix here. And there's only $k_\omega$ in the literature. So maybe I'm now leaning $k_n$, with the unfortunate caveat that $k_\omega$ is disjoint from $k_n$, or perhaps really, $k_\omega$ is shorthand for $k_{1,\omega}$ or $k_{3,\omega}$ (I forget which offhand).

**Comment by prabau** [comment]
Yeah, the $\omega$ in $k_\omega$ has a mathematical meaning.  The $n$ in $k_n$ is just arbitrary, except that 1,2,3 are in order of progressively more restrictive definition, so $k_3\implies k_2\implies k_1$.

And we have $k_\omega\implies k_1$ for now.  Maybe not a big deal.  If someone really cares about these things at some later time, they could tease out $k_{\omega,n}$.  Note that in the literature there are also incompatible definition of $k_\omega$ spaces.  We picked the one corresponding to the " $k_1$ family".

I still think it's kind of useful to show the relation between properties by choosing names that relate to each other.  As explained in the section "General framework for the definitions" of https://en.wikipedia.org/wiki/Compactly_generated_space
for example, one starts with a suitable family $\mathcal F$ of continuous maps from compact spaces to the topological space $X$ and then define corresponding notions of $k$-closed/open set, $k$-ification (final topology), $k$-space (compactly generated space), $k$-Hausdorff, etc.  It seems useful to know at a glance which properties are based on the same choice for $\mathcal F$.

**Comment by prabau** [comment]
FYI, the older page https://en.wikipedia.org/w/index.php?title=Compactly_generated_space&oldid=1158293522

has a bunch of references to mathse posts giving explanations for various facts.  That was before someone decided to remove them all :-(

**Comment by StevenClontz** [comment]
> Yeah, the ω in kω has a mathematical meaning. The n in kn is just arbitrary, except that 1,2,3 are in order of progressively more restrictive definition, so k3⟹k2⟹k1.

Yeah, it's in line with $T_n$ axioms, $\alpha_i$ convergence (which should be added to pi-Base someday), etc. The indices are arbitrary except at least their implications are compatible with their orderings.

I went with $k_{\omega,n}$ but only used 1,3 for now; could add $k_{\omega,2}$ when needed someday.

**Comment by prabau** [comment]
Need to step away from my desk.  Will look at it in more detail later today.  But one thing is if we introduce multiple variants of $k_\omega$, they should be backed up with relevant literature references.  Similarly to the $k$-space confusing literature usages, different authors use the same terminology with slightly different meaning, and we should at least mention some references that use the concept in each way that we want and mention the names usually used for that.

**Comment by StevenClontz** [comment]
Reasonable to mark as draft.

Unfortunately, our reference for defining $k_{\omega,1}$ (the current $k_\omega$) points to a paper that really defines $k_{\omega,3}$ https://zbmath.org/0416.54027. So the new $k_{\omega,3}$ points to it, and I won't delete $k_{\omega,1}$ since it's already in $\pi$-Base and aligns with the other $k_i$ properties. I'll see if I can find a paper that defines $k_{\omega}$ without requiring all $K_n$ be Hausdorff, but I imagine it's mostly studied in papers that assume all spaces are Hausdorff anyway.

**Comment by StevenClontz** [comment]
(I'll note that navigating $\pi$-Base on this branch while studying k-space properties is much nicer with the new names...)

**Comment by StevenClontz** [comment]
[This hack mathematician (me, my dissertation)](https://etd.auburn.edu/xmlui/bitstream/handle/10415/4502/dissertation.pdf?sequence=2&isAllowed=y) defines $k_\omega$ for just compact subspaces. But I assume all spaces are $T_1$ (?!). Maybe I meant $T_2$? I don't think section 5.3 ever was published beyond my dissertation, so it should all be taken with a grain of salt.

**Comment by StevenClontz** [comment]
Poking around ZBmath and looking at a few papers, yeah, everyone's assuming things are at least Hausdorff, so the subtlety is avoided in the literature.

**Comment by prabau** [comment]
Introducing the two variants $k_{\omega,1}$ and $k_{\omega,3}$ does seem to make sense and clarify things.  There have both been used in the literature and are subtly different.

I just re-read the full discussion at https://github.com/orgs/pi-base/discussions/520, which is pretty informative.

Was wondering about one thing for these two properties.  They are defined in terms of an *ascending* sequence of sets $K_n$ whose union is $X$ and such that the topology on $X$ is [coherent](https://en.wikipedia.org/wiki/Coherent_topology) with the collection of these $K_n$.  One could also omit the ascending condition from the definition: just a sequence of sets $K_n$ whose union is $X$ such that ...

For $k_{\omega,1}$, the $K_n$ are only required to be compact, and the two characterizations are equivalent.  Not completely trivial, but easy to see.  One forms the ascending sequence of sets $L_n=\bigcup\\{K_i:i\le n\\}$, which are also compact and whose union is $X$.  And the topology on $X$ is still coherent wrt the $L_n$ (well-known fact, see for example the first paragraph in the answer to https://math.stackexchange.com/questions/4848174, or the wikipedia page for "coherent topology").

For $k_{\omega,3}$, where the $K_n$ are required to be compact Hausdorff, the two characterizations would *not* be equivalent.  The obstacle is that the union of two compact Hausdorff sets need not be Hausdorff.

See in particular https://github.com/orgs/pi-base/discussions/520#discussioncomment-8164387.  The "telophase topology" (https://topology.pi-base.org/spaces/S000065).  It is compact, but not Hausdorff.  It is the union of two compact Hausdorff subspaces and has topology coherent with these two subspaces, i.e., it is $k_3$.  And it is also the union of an increasing sequence of compact Hausdorff subspaces.  But there is no such sequence of $K_n$ such that the topology on $X$ is coherent with the collection of $K_n$.  That is, the space is not $k_{\omega,3}$.  This is worth adding to pi-base (maybe afterwards in a separate PR), with a proper reference so some mathse post.

Anyway, I think the pages for P92 and P98 should be expanded with some of this information and clarifications. And furthermore:
For P98 ($k_{\omega,1}$):
- remove the ref to Franklin & Smith Thomas, and replace with ref to page 13 of Lawson & Madison (https://zbmath.org/0288.22006).  That last reference is exactly pi-base's definition, without the increasing condition, which is not needed as discussed above.

For P92 ($k_{\omega,3}$):
- add a direct link in the text to https://topology.nipissingu.ca/tp/reprints/v02/tp02105.pdf, as it's not directly available from zbmath.

Side note (probably for future PR): did not follow up on the refs for a proof, but I think Prop 3.5 in Lawson-Madison says [ $k_{\omega,1}$ + $k_1$-Hausdorff ==> Hausdorff].  pi-base does not know about this yet.  It knows T501 [ $k_{\omega,1}$ + $k_1$-Hausdorff ==> $k_{\omega,3}$].  Does $k_{\omega,3}$ imply Hausdorff?

**Comment by prabau** [comment]
Two more things.
- up to you, but for $k_{\omega,3}$, a reference to p. 209 of Ordman (https://doi.org/10.1016/0016-660X(75)90021-5) seems to me would be useful.  To make some basics accessible with just one click.
- T320 seems redundant now.

**Comment by prabau** [comment]
@StevenClontz #695 from @Almanzoris is basically ready to go, except for one small issue where we need your feedback.

Apart from that, he introduced theorems T500-503.  To make it easier for him, could you rename your new theorems accordingly?

**Comment by StevenClontz** [comment]
Thanks @prabau - will address the more expansive comments in the coming days...

**Comment by StevenClontz** [comment]
> Can we remove this alias?

Removing aliases will break links to searches. Until we have search URLs that refer to property IDs and not names/aliases, we shouldn't remove aliases.

**Comment by StevenClontz** [comment]
More could be done but I defer that to a future PR to get this moving along.

**Comment by StevenClontz** [comment]
> Does $k_{\omega,3}$ imply Hausdorff?

It does; this is now T507.

**Comment by prabau** [comment]
Nice find about $k_{\omega,3}$ spaces being Hausdorff.  It took me a while to figure out the proof of the lemma in Ordman.  But in retrospect, after looking at it in the right way, it's easy.

**Comment by StevenClontz** [comment]
I wrote out details at https://math.stackexchange.com/questions/4951365/are-k-omega-spaces-hausdorff and added the reference. I think this might be ready now.

**Review by prabau — APPROVED** [review]

**Pull request merged**
