### PR TITLE
Everywhere doubled line is not hereditarily separable

### PR DESCRIPTION
**Pull request by pzjp**
A simple contribution to the pi-Base.

The [everywhere doubled line](https://topology.pi-base.org/spaces/S000086) is not [hereditarily separable](https://topology.pi-base.org/properties/P000180). Discussed with @prabau [here](https://github.com/pi-base/data/issues/1075#issuecomment-2558227899).

### CODE REVIEW

**Comment by GeoffreySangston** [comment]
For some reason when I try to check the branch out it returns:
> Error SyntaxError: Unexpected token '<', "<?xml vers"... is not valid JSON

**Comment by prabau** [comment]
Great.  So since this is your first PR, we can go through the motions and mention a few procedure things.

One thing one usually does is adding a Label (right hand column) to indicate the state of the PR.  Immediately after creating the PR, one usually changes the state to "seeking-reviewer".  In this case you can change the Reviewer to me and change the state to "review-requested".  So I'll wait until that is done to proceed.

**Comment by prabau** [comment]
Personally I find a title like P180 for S86 not too helpful, because nobody can remembers what all these numbers mean.  When looking at the list of PRs, or scanning the list of previously closed PRs (https://github.com/pi-base/data/pulls?q=is%3Apr+is%3Aclosed), it is helpful to be able to recognize what is what.

This is also important because the title of the PR is what becomes the description of the combined commit ("squash and merge" step) when this branch gets merged into the `main` branch of the repository.

I also agree that sometimes it's too long to spell out everything in words, and these numeric ids (P180, S86) are short and convenient.  But in this case, it would make sense to choose a more descriptive title.
"Everywhere doubled line S36 is hereditarily separable" for example.

**Comment by pzjp** [comment]
It seems like I'm not authorized to select/suggest a reviewer.
According to GitHub docs _Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository._

**Comment by prabau** [comment]
Ok, no problem.  After doing a few more PRs satisfactorily, you'll be upgraded and things will become easier.  I'll change the label for now.

**Comment by prabau** [comment]
Now about the contents itself.
It's always good to check if the result can be extended to something stronger.  Looking at the page for hereditarily connected (https://topology.pi-base.org/properties/P000180), it appears that property implies countable spread, which itself implies countable extent.  It seems a trivial change to your argument shows the space does not have countable extent (P198).

So in vscode/github.dev you can do a corresponding "rename" of the file and change the contents accordingly.

**Comment by pzjp** [comment]
Indeed.
I do not assume that properties I'm not familiar with have so simple statement...

**Comment by prabau** [comment]
Very nice.  With this, three more traits for the space will become "known".  Approving.

**Review by prabau — APPROVED** [review]

**Comment by prabau** [comment]
Your change is now approved and merged.  You can now delete your topic branch from your repository.

Feel free to choose anything else for another PR.  Something bigger is fine if you want to.

**Pull request merged**
