### PR TITLE
More aleph_0 spaces

### PR DESCRIPTION
**Pull request by prabau**
Adding the countable $k$-network property for three more spaces:
- Sequential fan with countably many spines
- Bouquet of countably many circles
- Arens space

Also removed redundant traits.

### CODE REVIEW

**Comment by prabau** [comment]
@Almanzoris would you be able to review this?

**Comment by Almanzoris** [comment]
> @Almanzoris would you be able to review this?

Yeah, I will.

**Review by Almanzoris — APPROVED** [review]

**Comment by Almanzoris** [comment]
I would say that the PR is ready.

**Comment by prabau** [comment]
Thanks a lot for the review.  A few minor things:

For S131, I had "... homeomorphic to a convergent sequence (Fort space on an inifinite set)" to indicate that the convergent sequence was itself the same (homeomorphic) as the Fort space on an infinite set, not just a convergent sequence in that set, so that the rest of the sentence would make more sense.  Adding "in the" seems to change the meaning slightly?

For S139, the reason I had the period inside the dollar signs in `$X.$` is to keep the $X$ and the period always together.  Otherwise, the browser can separate the $X$ and the period at the end of a line and one ends up with a line with just a period by itself, which looks weird.  That's how I noticed it.  But no big deal either way.

S170: If we want to have S1 as a properly formatted alias, it is usually used with $1$ as a superscript: $S^1$.  Do you want to change it?

**Comment by Almanzoris** [comment]
> Thanks a lot for the review. A few minor things:
> 
> For S131, I had "... homeomorphic to a convergent sequence (Fort space on an inifinite set)" to indicate that the convergent sequence was itself the same (homeomorphic) as the Fort space on an infinite set, not just a convergent sequence in that set, so that the rest of the sentence would make more sense. Adding "in the" seems to change the meaning slightly?
> 
> For S139, the reason I had the period inside the dollar signs in `$X.$` is to keep the X and the period always together. Otherwise, the browser can separate the X and the period at the end of a line and one ends up with a line with just a period by itself, which looks weird. That's how I noticed it. But no big deal either way.
> 
> S170: If we want to have S1 as a properly formatted alias, it is usually used with 1 as a superscript: S 1 . Do you want to change it?

I have made the changes. I thought that you had done the $X.$ for a reason. However, as I saw a file keeping $X$. and in another file out of the PR I saw $U$. at the end of a line, I was unsure. But that is a reason why I waited for your recheck before merging. The next time, I will ask and avoid undos. When it comes to S131, I had misunderstood it, but now I have read it again and I have got it. Thanks.

**Comment by prabau** [comment]
> I thought that you had done the `$X.$` for a reason. However, as I saw a file keeping `$X$.` and in another file out of the PR I saw `$U$.` at the end of a line, I was unsure.

Yeah, I have not been consistent here.  I did not pay too much attention.  But it does not matter much, so we can leave it as is.

**Comment by Almanzoris** [comment]
No problem.

**Pull request merged**
