### PR TITLE
T611: Connected subspaces of the reals are contractible

### PR DESCRIPTION
**Pull request by prabau**
Add T611: embeddable in $\mathbb R$ + connected + not empty ==> contractible.

And cleanup two redundant trait files.

### CODE REVIEW

**Review by danflapjax — APPROVED** [review]

**Comment by GeoffreySangston** [comment]
I'm not sure if my comment was noticed, but 611 is a trivial theorem as is.

**Comment by prabau** [comment]
> I'm not sure if my comment was noticed, but T611 is a trivial theorem as is.

No, I did not see your comment. Where?

**Comment by GeoffreySangston** [comment]
I must have done the review wrong. But around noon today I started a review and made the following inline comment
"Change " - P000137: true" to " - P000137: false".

**Comment by prabau** [comment]
Ah, good catch.  I'll do another fix and then maybe you can approve that one.

**Comment by prabau** [comment]
Thanks @danflapjax

**Pull request merged**
