### PR TITLE
New properties: embeds in a topological group and W space

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
This is ready but I'm going to ask Jocelyn Bell to review (not sure if she's on GitHub but hopefully she will be soon).

**Review by jocelynbell — CHANGES_REQUESTED** [review]
A W-space that is not first-countable is the one-point compactification of an uncountable discrete space

**Comment by StevenClontz** [comment]
Thanks for your review Jocelyn. I've addressed the concern you pointed out to me. If you want to try completing this review on your own, here's what you can do:

- Remember you can see the proposed update to pi-Base by going to https://topology.pi-base.org/dev and entering `groupembed` as the branch. You may need to hit the refresh icon to get my most recent updates.
- Double-check the theorems and references we didn't fully look over earlier today: I think these were T473 onward. Note that my recent change added a proof that the converse of T473 fails, as you requested.
- Check that my additions since we met this afternoon are valid. You can see exactly what files were modified by clicking above:
image
Then cross-reference these with the pi-Base website to see if you agree with the modifications.
- Finally, either approve the pull request, or request further changes:
image

image

If you have questions, email me, comment here, or we'll chat during our research meeting next week. Thanks! :-D

**Comment by danflapjax** [comment]
Another possible theorem: [P185](https://topology.pi-base.org/properties/P000185) Partition topology ⇒ [P186](https://topology.pi-base.org/properties/P000186) Embeds in a topological group, since any partition space can be embedded in a larger homogeneous partition space. (See [T470](https://topology.pi-base.org/theorems/T000470))

**Comment by StevenClontz** [comment]
> Another possible theorem: [P185](https://topology.pi-base.org/properties/P000185) Partition topology ⇒ [P186](https://topology.pi-base.org/properties/P000186) Embeds in a topological group, since any partition space can be embedded in a larger homogeneous partition space. (See [T470](https://topology.pi-base.org/theorems/T000470))

Sounds like a good follow up PR!

**Comment by prabau** [comment]
Some comments for you and Jocelyn to discuss.

S154/P187: "non-trivial sequence" is not clear and seemingly not right. You probably meant a sequence of all distinct elements instead.

T473: "Asserted on page 340 ...": It would be more helpful to mention Theorem 3.2 instead (as it not only asserts, but has the proof as well (even if the proof is obvious in this case)).

The paper mentions on p. 340 the result [separable + W-space ==> first countable], which would be good have as it would imply various additional spaces are not W-space by contrapositive.  But where is that shown in the paper?  I couldn't see it.

Various theorems here invoke the notion of proximal space ([P76](https://topology.pi-base.org/properties/P000076)).  The definition of proximal space in pi-base is a little short on information though, and it would be good if you guys could expand it as needed.  In particular, add J. Bell's paper as a reference, clarify whether pi-base assume Hausdorff or not (I think we discussed before that pi-base did not require Haudorff, but Bell's paper assumes that). A "purely topological" characterization is also mentioned from Clontz's paper.  Is that something that can be written down, including the exact place in the paper?

T475: Does Lemma 6 from Bell's paper also work without the Hausdorff assumption?  I assume so, but would be good to mention it explicitly.

T476: (I don't have access to Tkachuk's paper.) The abstract (combined with the zbmath review) mentions: A compact space $X$ is Corson compact if and only if it embeds in a topological group that is a W-space.  However, that is stronger than saying $X$ is a W-space that embeds in a topological group.  (i.e., how do you deduce one can choose the topological group itself to be a W-space?).

**Comment by StevenClontz** [comment]
Good points Patrick - for the sake of helping Jocelyn with this PR review, I'll plan to implement those comments in a follow up PR.

**Comment by prabau** [comment]
@StevenClontz @jocelynbell A follow-up PR should be fine. But can you take a look at my comment for T476?  Does that invalidate the approach of this whole PR?

**Comment by StevenClontz** [comment]
I'm pretty sure it doesn't, but it's worth writing up a proof somewhere for this.

**Comment by StevenClontz** [comment]
Well shucks, I'm less convinced now. I've asked the question at https://mathoverflow.net/questions/468553 but I'll update this PR to fix things for now.

**Comment by StevenClontz** [comment]
It's been pointed out that "embeds in a topological group" is just "completely regular". Thanks for the sharp eye @prabau.

**Review by jocelynbell — APPROVED** [review]

**Pull request merged**
