### PR TITLE
box product of reals is not W but has points Gdelta

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by Almanzoris** [comment]
I would say that I find it ready.

**Comment by StevenClontz** [comment]
> I would say that I find it ready.

Great! Then leave an approving review and click "squash and merge" to accept this contribution. Thanks for your review.

**Review by Almanzoris — APPROVED** [review]

**Comment by prabau** [comment]
@Almanzoris FYI, about the meaning of "squash and merge".  When working on a PR there are usually multiple commits.  The "squash" part then squashes all these commits into a single combined commit, which is the one that gets merged into the `main` branch.  Most of the time, the details of the individual commits do not matter.  That's why when I do the "squash and merge" I usually blank out the list of individual commits in the description field before pressing the button.  That way, one gets a cleaner log when doing `git log` on the command line, a lot easier to scan all the merged PRs.  Something like this:

image

If you don't blank out the description, one ends up with something like this:

image

It's completely irrelevant that there was an intermediate commit that fixed indentation or another one with "small fixes" or ... or for my PR at the bottom another commit that fixed a typo.  All that makes the overall list harder to scan.  Not everybody agrees (@StevenClontz ?), but my recommendation would be to only keep the relevant overall title for the PR.

And note that if anybody cares, the details of the individual commits is still available on the github page for each PR.

**Comment by Almanzoris** [comment]
Yeah, you are right. My bad, and thank you for letting me know. I will keep this in mind for the next times.

**Pull request merged**
