### PR TITLE
clarify deleted vs non-deleted Dieudonne plank

### PR DESCRIPTION
**Pull request by StevenClontz**
possible solution to issue #462

### CODE REVIEW

**Comment by prabau** [comment]
I like the overall approach.

**Comment by prabau** [comment]
If it's ok with you, I could add some traits for S187 in this branch.

**Comment by StevenClontz** [comment]
Go for it, I won't be able to contribute more here today.

**Comment by StevenClontz** [comment]
Let me know if you made any progress on this; I should be able to flesh this out in the next few days if not.

**Comment by prabau** [comment]
> Let me know if you made any progress on this; I should be able to flesh this out in the next few days if not.

Sorry I was tied up.  I am making progress and will push what I have so far tonight.

**Comment by prabau** [comment]
@StevenClontz I have added one general statement in the answer to https://math.stackexchange.com/questions/4785088.  Can you double check it?  I may need to use this.

**Comment by prabau** [comment]
I did some editing of the README for the two spaces (in particular, changed the product $X\times Y$ to $Y\times Z$, so we can refer to $X$ for the space itself as usual).

As a side note, the first component $Y=[0,\omega_1]$ has a "Fortissimo" topology, similar to https://topology.pi-base.org/spaces/S000022 but not quite the same (unless assuming CH).  Somehow it would be nice to have a Fortissimo space on $\omega_1$, as we could assert a few more properties for it than S22 and then Dieudonne = Fortissimo x Fort.

Also added a bunch of traits for S187.
- see in particular if P151 (strategically Rothberger) needs any edits.
- the proof for P172 (radial) is maybe a little long.

Still remaining:
- is S187 pseudoradial?  Have not thought about it yet.
- add traits and some cleanup for S87 itself (later?)

**Comment by StevenClontz** [comment]
> @StevenClontz I have added one general statement in the answer to https://math.stackexchange.com/questions/4785088. Can you double check it? I need this for the proof of the radial property.

Looks ok to me.

**Comment by prabau** [comment]
I'll add a mathse question to start wrapping this up.

**Review by StevenClontz — COMMENTED** [review]
I think the PR is ready to merge as-is, with future enhancements appropriate for a separate PR.

**Comment by prabau** [comment]
This can be reviewed as is, and I'll add more separately.  Since both of us had a hand in this, we can maybe have someone else review.  @lyengulalp would you be interested?

**Review by lyengulalp — APPROVED** [review]

**Pull request merged**
