### PR TITLE
T629: every LOTS is collectionwise normal

### PR DESCRIPTION
**Pull request by StevenClontz**
Answers https://topology.pi-base.org/spaces?q=LOTS%2B%7ECollectionwise+normal

### CODE REVIEW

**Comment by prabau** [comment]
Note: this is also kind of shown in https://math.stackexchange.com/a/322974.  There is also a mention of an article by Carter in another answer.  Did not read it, but could be worth taking a look.

**Comment by david20000813** [comment]
This will follow from #927, if monotonically normal gets added. LOTS are GO-spaces, GO-spaces are monotonically normal, which are in turn even hereditarily collectionwise normal.

**Comment by david20000813** [comment]
I'd suggest just adding monotonically normal, as in #927, then get this automatically deduced. @prabau do you still want to do the addition of monotonically normal? Or I can just do it myself.

**Comment by prabau** [comment]
> This will follow from #927, if monotonically normal gets added. LOTS are GO-spaces, GO-spaces are monotonically normal, which are in turn even hereditarily collectionwise normal.

Right.  I know about that.  We could still mention this current result now, and later replace the theorem as needed.

**Comment by david20000813** [comment]
> > This will follow from #927, if monotonically normal gets added. LOTS are GO-spaces, GO-spaces are monotonically normal, which are in turn even hereditarily collectionwise normal.
> 
> Right. I know about that. We could still mention this current result now, and later replace the theorem as needed.

That also works. Adding monotonically normal and doing reviews will take a day or two.

**Comment by prabau** [comment]
> > > This will follow from #927, if monotonically normal gets added. LOTS are GO-spaces, GO-spaces are monotonically normal, which are in turn even hereditarily collectionwise normal.
> > 
> > 
> > Right. I know about that. We could still mention this current result now, and later replace the theorem as needed.
> 
> That also works. Adding monotonically normal and doing reviews will take a day or two.

I was planning to do it.  Is there a rush to do it now?

**Comment by david20000813** [comment]
> > > > This will follow from #927, if monotonically normal gets added. LOTS are GO-spaces, GO-spaces are monotonically normal, which are in turn even hereditarily collectionwise normal.
> > > 
> > > 
> > > Right. I know about that. We could still mention this current result now, and later replace the theorem as needed.
> > 
> > 
> > That also works. Adding monotonically normal and doing reviews will take a day or two.
> 
> I was planning to do it. Is there a rush to do it now?

No, not really. Just seeing this PR reminds of that, is all.

**Comment by prabau** [comment]
> > 
> > I was planning to do it. Is there a rush to do it now?
> 
> No, not really. Just seeing this PR reminds of that, is all.

OK.  I'll start working on it after I finish reviewing other stuff.

**Comment by StevenClontz** [comment]
> Note: this is also kind of shown in https://math.stackexchange.com/a/322974, or at least we could mention this mathse answer. There is also a mention of an article by Carter in another answer. Did not read it, but could be worth taking a look.

Added mathse reference. I agree with the consensus: add this here, improve with monotonically normal later.

**Comment by prabau** [comment]
As an aside, the quoted sources show that a LOTS is hereditarily collectionwise normal

This last property would be good to add at some point. Does one of you know an example of collectionwise normal space that is not hereditarily so?

**Comment by prabau** [comment]
The theorem number conflicts with #974.  Needs to be changed.

**Comment by StevenClontz** [comment]
I'll change the theorem number when I get a chance, though i think as a policy it's intractable in the long term to check every open pr to avoid id conflicts: once a conflict is merged, pending prs will be able to tell and be updated.

**Comment by StevenClontz** [comment]
> This last property would be good to add at some point. Does one of you know an example of collectionwise normal space that is not hereditarily so?


https://topology.pi-base.org/spaces?q=Collectionwise+normal%2B%7ECompletely+normal

**Comment by prabau** [comment]
> I'll change the theorem number when I get a chance, though i think as a policy it's intractable in the long term to check every open pr to avoid id conflicts: once a conflict is merged, pending prs will be able to tell and be updated.

I understand.  It's just that the other PR has already been approved.  But it is make it easier, I will now merge it to make it clear.

**Comment by prabau** [comment]
#974 now merged.

**Comment by StevenClontz** [comment]
> > I'll change the theorem number when I get a chance, though i think as a policy it's intractable in the long term to check every open pr to avoid id conflicts: once a conflict is merged, pending prs will be able to tell and be updated.
> 
> I understand. It's just that the other PR has already been approved. But if it makes it easier, I will now merge it to make it clear.

Ah, definitely then! Didn't realize it was ready.

**Comment by prabau** [comment]
Before approving, isn't is also the case that GO-spaces are collectionwise normal (cwn)?

Reasoning: The sources mentioned show that LOTS are hereditarily cwn.  Since a GO-space is a subspace of a LOTS, it will also be cwn.

So for now, do you want to update the theorem?  Or leave it like this and I'll do the change to [GO-space ==> hered. cwn] while introducing "hereditarily cwn", which I'll do later today or tomorrow.

**Comment by StevenClontz** [comment]
I didn't remember we had GO-space already!

**Comment by StevenClontz** [comment]
Anyway, this can be merged, or superceded by a PR that introduces hereditarily collection wise normal

**Comment by prabau** [comment]
I made a change to the proof.  Please take a look.

One nice thing is that we can derive that three more spaces are collectionwise normal, and two more are not GO-spaces.

**Comment by StevenClontz** [comment]
Looks good @prabau, and I fixed the numbering conflict.

**Review by prabau — APPROVED** [review]

**Comment by david20000813** [comment]
I'm not sure if this is just a display error on my devices, but I've tried both on my laptop and iPad, for some reason extra curly brackets show up in T629:

Untitled

The code looks correct though, so I'm not sure what went wrong here.

**Comment by prabau** [comment]
It's a typo in the PR.  `{{P133}}` should be `{P133}`, etc.

Fixing this right now, and then you can approve and merge.

**Comment by david20000813** [comment]
@prabau Oh yes, external links need two curly brackets, internal links need only one. Didn't notice that.

**Pull request merged**
