### PR TITLE
Nonempty Čech complete spaces with no isolated points are not Rothberger

### PR DESCRIPTION
**Pull request by david20000813**
The P68 traits on S25 and S176 become redundant with this theorem.

### CODE REVIEW

**Review by StevenClontz — COMMENTED** [review]
This proof is a bit more technical than what I usually approve without some external citation - would it be a useful answer to add to https://math.stackexchange.com/questions/740616 or maybe a new Q&A?

Others can chime in as well.

**Comment by prabau** [comment]
That does seem a little too much to have as a direct proof in pi-base, and also because it uses notions outside of general topology itself.  Like Steven suggested, can this be on mathse somewhere and we can just refer to that?

**Comment by david20000813** [comment]
The linked question is too old and my theorem a bit too off topic for it. I'll add a new Q&A on MSE to address this then.

**Comment by david20000813** [comment]
I realized it might be possible to vastly generalize this - one only need a nonatomic nonzero outer regular measure to make this work. I've therefore converted this into a draft in order to see the most general statement I can prove.

**Comment by david20000813** [comment]
Done - it's a bit funny this ends up being about Cech-completeness again.

**Comment by david20000813** [comment]
Unfortunately, there are still a large amount of spaces which are not Rothberger but not known to be so to pi-Base even after adding this theorem. Mostly, their non-Rothberger-ness can be easily deduced by the following two facts:

1. If $X$ is Rothberger, then so is any closed subspace of $X$;
2. If $X$ is Rothberger, then so is any coarser topology on $X$.

I'm planning to write another PR to deal with this once the content of the current PR gets approved and merged.

**Comment by StevenClontz** [comment]
For reference: https://math.stackexchange.com/questions/5004550/are-%c4%8cech-complete-spaces-with-no-isolated-points-non-rothberger

If no one finds any issues there in a day or so, then I think this will be ready to merge.

**Review by StevenClontz — APPROVED** [review]

**Pull request merged**
