### PR TITLE
add S185|P130 false

### PR DESCRIPTION
**Pull request by StevenClontz**
Answers https://topology.pi-base.org/spaces?q=Second+countable%2BWeakly+locally+compact%2B%7ELocally+compact

### CODE REVIEW

**Comment by prabau** [comment]
Your mathse question now got multiple answers.  So you could change the ref to point to the relevant specific answer only (with `name: Answer to "..."`).  Or remove the ref entirely, since it does not add anything to the text in the PR.

Appoving and leaving it up to you if you want further changes.

**Review by prabau — APPROVED** [review]

**Comment by prabau** [comment]
By the way, we ended up changing the previous name of S97 to a better one: "one-point compactification of the sequential fan".
Would there be a similarly better name for S185?

**Comment by StevenClontz** [comment]
> Your mathse question now got multiple answers. So you could change the ref to point to the relevant specific answer only (with `name: Answer to "..."`). Or remove the ref entirely, since it does not add anything to the text in the PR.

Pointed to the answer. I like leaving links to MathSE as that's a good place to discuss a pi-Base argument that was also made on MathSE. (I like the counter-example provided in the other answer too, though it breaks T_1.)

**Comment by StevenClontz** [comment]
> Would there be a similarly better name for S185?

I'm trying to think if there's a general procedure to obtain the process used to produce S185 from the metric fan (hang on, we don't have the metric fan in pi-Base?!).

**Comment by StevenClontz** [comment]
Lol, no, the metric fan is not locally compact. This is exactly the one-point compactification of the metric fan. I'll write it up in a separate PR.

**Pull request merged**
