### PR TITLE
T509: Functionally Hausdorff + countable network => submetrizable

### PR DESCRIPTION
**Pull request by prabau**
New T509: Functionally Hausdorff + countable network ==> submetrizable.

This allows to automatically deduce that 8 more spaces are submetrizable.

### CODE REVIEW

**Comment by StevenClontz** [comment]
@Almanzoris do you see a button like this? If so, you can "Squash and merge" the changes you approve into main branch (so it becomes available to the public). If not, I should adjust your permissions.

**Comment by Almanzoris** [comment]
@StevenClontz I don't.
image

**Comment by StevenClontz** [comment]
I merged this one so it won't be delayed, but I fixed things so you can merge approved contributions in the future (including when you approve them yourself).

**Comment by Almanzoris** [comment]
> I merged this one so it won't be delayed, but I fixed things so you can merge approved contributions in the future (including when you approve them yourself).

Sure. Thank you for the trust!

**Pull request merged**
