### PR TITLE
add five non-W spaces

### PR DESCRIPTION
**Pull request by StevenClontz**
Inspired by https://math.stackexchange.com/questions/4973260/are-w-spaces-with-countable-pseudocharacter-first-countable/4973385#4973385

### CODE REVIEW

**Comment by prabau** [comment]
(I am leaving the review of this to @Almanzoris, but wanted to comment on something I was wondering from other PRs as well.)

I have seen that in various arguments when one needs to choose numbers that converge to zero (for S29 in this case), you choose $2^{-n}$ instead of $1/n$.  The choice of $2^{-n}$ immediately makes one think that some argument involving the convergence of the geometric series will be used, but it turns out it's not the case.  Any reason for not choosing the simpler $1/n$?

**Comment by prabau** [comment]
(Also not formally part of this review)

Several of the arguments here rely implicitly on the fact that the W-space property is hereditary.  Then one shows a certain space is not W-space by showing it contains a homeomorphic copy of another space that we already know does not have the property.

This illustrates well the benefit of having "meta-properties" for properties.  Even if we don't use that (yet) to automatically derive traits for spaces, we could start by having an additional tab in each property page showing some of this information.  That would be really handy for users (and for us).

We could discuss this at the next zoom meeting, about how the additional data could be organized and then displayed on the web pages.

**Review by Almanzoris — APPROVED** [review]

**Comment by Almanzoris** [comment]
> (I am leaving the review of this to @Almanzoris, but wanted to comment on something I was wondering from other PRs as well.)
> 
> I have seen that in various arguments when one needs to choose numbers that converge to zero (for S29 in this case), you choose `2^{-n}` instead of `1/n`. The choice of `2^{-n}` immediately makes one think that some argument involving the convergence of the geometric series will be used, but it turns out it's not the case. Any reason for not choosing the simpler `1/n`?

Yeah, the choice could be changed to $\frac{1}{n}$.

I wanted to ask, when it comes to the spaces that contain a copy of S131, if we should specify a copy to make it easier for the reader.

**Comment by Almanzoris** [comment]
> (Also not formally part of this review)
> 
> Several of the arguments here rely implicitly on the fact that the W-space property is hereditary. Then one shows a certain space is not W-space by showing it contains a homeomorphic copy of another space that we already know does not have the property.
> 
> This illustrates well the benefit of having "meta-properties" for properties. Even if we don't use that (yet) to automatically derive traits for spaces, we could start by having an additional tab in each property page showing some of this information. That would be really handy for users (and for us).
> 
> We could discuss this at the next zoom meeting, about how the additional data could be organized and then displayed on the web pages.

I agree with that. I have also thought that something like that could be added in a way that spaces could be related with other spaces and some properties would be automatically deduced for such, which would require the properties to have meta-properties for the process (at least in this way). I also agree that it would be a good start to add the meta-properties to properties as information and that it would be really useful.

**Comment by prabau** [comment]
Are there any trait files that are now redundant with this addition?

**Comment by prabau** [comment]
> I wanted to ask, when it comes to the spaces that contain a copy of S131, if we should specify a copy to make it easier for the reader.

I personally think it's pretty clear and does not need further detail.  But you guys can decide.

**Comment by prabau** [comment]
updated previous comment

**Comment by StevenClontz** [comment]
> (I am leaving the review of this to @Almanzoris, but wanted to comment on something I was wondering from other PRs as well.)
> 
> I have seen that in various arguments when one needs to choose numbers that converge to zero (for S29 in this case), you choose `2^{-n}` instead of `1/n`. The choice of `2^{-n}` immediately makes one think that some argument involving the convergence of the geometric series will be used, but it turns out it's not the case. Any reason for not choosing the simpler `1/n`?

`1/n` is undefined for `0\in\omega`, but `2^{-n}` is defined whether or not you consider `0` a natural number.

**Comment by StevenClontz** [comment]
Sorry, I meant to mark this PR as ready to review.

Thanks for the approval @Almanzoris but I've re-requested the review since we have a few good comments I want you to make sure I address before we merge. Responding now...

**Comment by StevenClontz** [comment]
Keeping it as draft until I do two things:

- Make embedding more specific for the spaces that it applies to.
- Double-check for more deducible assertions. (Thanks @Almanzoris for catching a few!)

**Comment by StevenClontz** [comment]
> (Also not formally part of this review)
> 
> Several of the arguments here rely implicitly on the fact that the W-space property is hereditary. Then one shows a certain space is not W-space by showing it contains a homeomorphic copy of another space that we already know does not have the property.
> 
> This illustrates well the benefit of having "meta-properties" for properties. Even if we don't use that (yet) to automatically derive traits for spaces, we could start by having an additional tab in each property page showing some of this information. That would be really handy for users (and for us).
> 
> We could discuss this at the next zoom meeting, about how the additional data could be organized and then displayed on the web pages.

This is now on our agenda for October.

**Comment by prabau** [comment]
For S97 for example (but similarly for the others), the phrasing 
`Follows as this space contains a copy $\omega^2\cup\{x\}$ of {S131} which fails to be {P187}.`
seems a little odd with "a copy (specific subspace here) of S131".  We can mention the specific subspace instead, and say it's a copy of S131.  Maybe something like:

`The {P187} property is hereditary.  The subspace $\omega^2\cup\{x\}$ is homeomorphic to {S131} and {S131|P187}.`

(or use "a copy of").  And this will directly link to the justification for S131, which is convenient.

**Comment by StevenClontz** [comment]
will do

**Comment by prabau** [comment]
Thanks for the update to the description of S97.  It's clearer.

**Comment by prabau** [comment]
Something occurred to me.  Isn't S97 = $\omega^2\cup\\{x,y\\}$ the one-point compactification of $\omega^2\cup\\{x\\}$ with $y$ as the compactifying point?  So the "Steen-Seebach maximal compact topology" would be the "One-point compactification of $S_\omega$" (i.e. of the sequential fan with $\omega$-many spines).  That would be worth mentioning in the description for S97 and would make a better primary name for the space.

**Review by Almanzoris — APPROVED** [review]

**Comment by Almanzoris** [comment]
The suggestions have been incorporated and I find the pull request ready too.

**Comment by Almanzoris** [comment]
> Something occurred to me. Isn't S97 = ω 2 ∪ x , y the one-point compactification of ω 2 ∪ x with y as the compactifying point? So the "Steen-Seebach maximal compact topology" would be the "One-point compactification of the sequential fan S ω ". That would be worth mentioning in the description for S97 and would make a better primary name for the space.



> Something occurred to me. Isn't S97 = ω 2 ∪ x , y the one-point compactification of ω 2 ∪ x with y as the compactifying point? So the "Steen-Seebach maximal compact topology" would be the "One-point compactification of the sequential fan S ω ". That would be worth mentioning in the description for S97 and would make a better primary name for the space.

Good observation.

**Comment by Almanzoris** [comment]
One last thing. This is about your answer from mathse @StevenClontz. The link of S97 is currently wrong (it is the link of S139). I don't have editing perms there.

**Comment by StevenClontz** [comment]
> One last thing. This is about your answer from mathse @StevenClontz. The link of S97 is currently wrong (it is the link of S139). I don't have editing perms there.

Fixed, thank you!

Merging now. I think @Almanzoris has permission to do this as well as approving PRs, so feel free to do so next time after approval. If you cannot, let me know.

**Pull request merged**
