### PR TITLE
Add GO-space + sequentially discrete => anticompact

### PR DESCRIPTION
**Pull request by Jianing-Song**
I admit that this look a bit artificial, especially that this theorem does not add to the proof that some spaces have some properties. Any points of view?

### CODE REVIEW

**Comment by prabau** [comment]
Anticompact (with T1) implies sequentially discrete.  The reverse is not true in general (e.g., the Stone-Cech compactification of the integers, which is sequentially discrete).  But the reverse holds for LOTS and GO-spaces as your proposed result shows.

Actually, under T1, we have these implications:
P-space ==> ${\omega}C$ (countable sets are closed) ==> anticompact ==> sequentially discrete.

It seems that a GO-space that is sequentially discrete would have to be a P-space.  So all four properties would be equivalent for GO-spaces.  Does that sound right to you?

---
Separately, it would be interesting to add to pi-base the "Fortissimo space of size $\aleph_1$".  That's the space in Edit 1 of your post https://math.stackexchange.com/questions/4913523, also treated as $F_{\omega_1,\omega_1}$ in https://math.stackexchange.com/questions/4913523, providing an example of a sequentially discrete LOTS that is not discrete.

It's basically a clone of [S22 (Fortissimo space on the real numbers)](https://topology.pi-base.org/spaces/S000022), except that whether S22 is a LOTS is undecidable (it's a LOTS iff (CH) holds).

**Comment by Jianing-Song** [comment]
> Anticompact (with T1) implies sequentially discrete. The reverse is not true in general (e.g., the Stone-Cech compactification of the integers, which is sequentially discrete). But the reverse holds for LOTS and GO-spaces as your proposed result shows.
> 
> Actually, under T1, we have these implications: P-space ==> ω C (countable sets are closed) ==> anticompact ==> sequentially discrete.
> 
> It seems that a GO-space that is sequentially discrete would have to be a P-space. So all four properties would be equivalent for GO-spaces. Does that sound right to you?
> 
> Separately, it would be interesting to add to pi-base the "Fortissimo space of size ℵ 1 ". That's the space in Edit 1 of your post https://math.stackexchange.com/questions/4913523, also treated as F ω 1 , ω 1 in https://math.stackexchange.com/questions/4913523, providing an example of a sequentially discrete LOTS that is not discrete.
> 
> It's basically a clone of [S22 (Fortissimo space on the real numbers)](https://topology.pi-base.org/spaces/S000022), except that whether S22 is a LOTS is undecidable (it's a LOTS iff (CH) holds).

I like this description as "Fortissimo space on $\aleph_1$". That's great! Thanks a lot!

I will consider modifying this PR later.

**Comment by Jianing-Song** [comment]
> Anticompact (with T1) implies sequentially discrete. The reverse is not true in general (e.g., the Stone-Cech compactification of the integers, which is sequentially discrete). But the reverse holds for LOTS and GO-spaces as your proposed result shows.
> 
> Actually, under T1, we have these implications: P-space ==> ω C (countable sets are closed) ==> anticompact ==> sequentially discrete.
> 
> It seems that a GO-space that is sequentially discrete would have to be a P-space. So all four properties would be equivalent for GO-spaces. Does that sound right to you?
> 
> Separately, it would be interesting to add to pi-base the "Fortissimo space of size ℵ 1 ". That's the space in Edit 1 of your post https://math.stackexchange.com/questions/4913523, also treated as F ω 1 , ω 1 in https://math.stackexchange.com/questions/4913523, providing an example of a sequentially discrete LOTS that is not discrete.
> 
> It's basically a clone of [S22 (Fortissimo space on the real numbers)](https://topology.pi-base.org/spaces/S000022), except that whether S22 is a LOTS is undecidable (it's a LOTS iff (CH) holds).

I think we have radial + seq. discrete => $\omegaC$. Just for sure: can the $\lambda$ in the definition of [radial](https://topology.pi-base.org/properties/P000172) always be chosen to be $\le|A|$, provided that $|A|$ is infinite?

And what's more, do we have radial + seq. discrete => P-space?

**Comment by prabau** [comment]
> I think we have radial + seq. discrete => ω C . Just for sure: can the transfinite sequence ( x λ ) in the definition of [radial](https://topology.pi-base.org/properties/P000172) always be chosen to have distinct terms, provided that | A | is infinite and that p ∉ A ?
> 
> And what's more, do we have radial + seq. discrete => P-space?

I'll give this some thought tomorrow.

**Comment by prabau** [comment]
Even more generally, it seems that [pseudoradial + seq. discrete ==> ${\omega}C$].

I am not sure about what you said about taking a transfinite sequence with distinct terms.  But one proof makes use of the answer for https://math.stackexchange.com/questions/4785088.  In particular:
> If a point $p\in X$ is the limit of a transfinite sequence (repetitions allowed) of points from a countable set $A\subseteq X$, the point is also the limit of an ordinary sequence of points from $A$.

From there, it's easy to check the result by contradiction.

Or for another proof, pseudoradial and sequentially discrete are two hereditary properties (please double check me on this).  So, if a countable set $A\subseteq X$ is not closed and $p\in\overline{A}\setminus A$, the subspace $A\cup\\{p\\}$ would be countable and pseudoradial, hence sequential by T210.  In combination with sequentially discrete, this would imply discrete by T416.  Contradiction with the fact that $p$ is an accumulation point of $A$.

That result is nice, since the contrapositive allows to derive some new traits (e.g., the Tychonoff plank is not sequentially discrete, or the Stone-Cech compactification of the integers is not pseudoradial).

----
What about P-space?  Need to think.

**Comment by Jianing-Song** [comment]
> Even more generally, it seems that [pseudoradial + seq. discrete ==> ω C ].
> 
> I am not sure about what you said about taking a transfinite sequence with distinct terms. But one proof makes use of the answer for https://math.stackexchange.com/questions/4785088. In particular:
> 
> > If a point 
> >   p
> >   ∈
> >   X
> >  is the limit of a transfinite sequence (repetitions allowed) of points from a countable set 
> >   A
> >   ⊆
> >   X
> > , the point is also the limit of an ordinary sequence of points from 
> >   A
> > .
> 
> From there, it's easy to check the result by contradiction.
> 
> Or for another proof, pseudoradial and sequentially discrete are two hereditary properties (please double check me on this). So, if a countable set A ⊆ X is not closed and p ∈ A ― ∖ A , the subspace A ∪ { p } would be countable and pseudoradial, hence sequential by T210. In combination with sequentially discrete, this would imply discrete by T416. Contradiction with the fact that p is an accumulation point of A .
> 
> That result is nice, since the contrapositive allows to derive some new traits (e.g., the Tychonoff plank is not sequentially discrete, or the Stone-Cech compactification of the integers is not pseudoradial).
> 
> What about P-space? Need to think.

That's nice! (I think the heredity of pseudoradial and sequentially discrete is OK.)

For P-space, I currently don't have time to do this, but I would be happy to ask a MSE question later.

**Comment by prabau** [comment]
(FYI, when doing a reply to a previous comment here, there is no need to requote the whole comment in full :-)  One can also select a portion of a comment and click "Quote reply" and only that portion will appear in the reply.)

**Comment by prabau** [comment]
> For P-space, I currently don't have time to do this, but I would be happy to ask a MSE question later.

I can show [GO-space + seq. discrete ==> P-space], but I don't see how to do it with GO-space replaced by radial.
Could  you ask a mathse question about both?

**Comment by Jianing-Song** [comment]
> I can show [GO-space + seq. discrete ==> P-space], but I don't see how to do it with GO-space replaced by radial.
> Could you ask a mathse question about both?

OK, would you mind sharing your proof for GO-space + seq. discrete => P-space?

**Comment by prabau** [comment]
You can ask a question and people will answer.  Or I'll post mine if it's different.

**Comment by StevenClontz** [comment]
Seconding @prabau - non-trivial mathematics should happen on a forum like Math.StackExchange for broader input.

**Comment by Jianing-Song** [comment]
> You can ask a question and people will answer. Or I'll post mine if it's different. You can also give a partial answer.

I have opened the Math SE question https://math.stackexchange.com/questions/4975331.

**Comment by Jianing-Song** [comment]
Very glad that we had an affirmative answer. @prabau Please don't hesitate to post your answer/comment/remark :)

**Comment by prabau** [comment]
Very nice answer from Ulli.  My proof was only for the special case of a GO-space, so no need for me to add anything.

**Comment by Jianing-Song** [comment]
@prabau I guess that the theorem can be add to the system now? :)

**Comment by prabau** [comment]
> @prabau I guess that the theorem can be add to the system now? :)

Yes, of course.  Sorry, I forgot to complete the review.  Will do it later today.

**Comment by Jianing-Song** [comment]
> > @prabau I guess that the theorem can be add to the system now? :)
> 
> Yes, of course. Sorry, I forgot to complete the review. Will do it later today.

OK :) (Didn't help to reply because I see you comment was 1 minute ago. What a coincidence.)

**Review by prabau — APPROVED** [review]

**Pull request merged**
