### PR TITLE
S87 Update.

### PR DESCRIPTION
**Pull request by Almanzoris**

### CODE REVIEW

**Comment by prabau** [comment]
Why do you have so many commits? Is there something wrong in the way you are editing files?  What editor are you using exactly?

**Comment by Almanzoris** [comment]
I have done it here on the website, for each step it would make a commit. I need to learn how to use an editor.

**Comment by prabau** [comment]
Here are a few pointers on how to do things more effectively.

You should use a more convenient editor that allows you to modify multiple files at the same time and then do a commit covering these changes involving multiple files.  The recommend editor is the one from github.dev, which you can also use directly from the web site.  

By the way, remember the recommendations I gave you in https://github.com/pi-base/data/issues/677#issuecomment-2197900369, about how to become familiar with the basics, and specifically to go through the hello world tutorial, get familiar with git and the github help and the github.dev editor?  That would really be useful, instead of jumping ahead and creating more work for everyone unnecessarily.  I really recommend you to experiment with creating branches, deleting branches, commits, edit multiple files, github.dev, etc in your own repository first, where it's completely isolated and you can try everything to your heart's content.

To get to github.dev from the "Files changed" tab of a particular PR, typing a single dot (`.`) will bring up the github.dev editor.  That also works from the "Code" tab from the top level page for a repository, for example your https://github.com/Almanzoris/Alman_pibase repo.

Another useful point: if you work on a branch forked from the main repository (like the branch `S87` for this PR), every time you do a commit, there is automatic compilation of it in the background (which you can see in the Actions menu: https://github.com/pi-base/data/actions) to determine if there are any obvious errors.  The commit is then marked with either a green checkmark (good) or a red cross (not good).  So when you commit something, you should wait for the compilation to finish, and if you see a red cross, you should follow up and see the cause of the mistake and fit it then, instead of piling up more commits on top, all failing.  To check what the problem was, you can directly click on the red cross next to the bad commit and look at "Details".  In this case, it mentions a problem with `refs:`.

Anyway, it does not matter if this PR take more time.  We don't care if pi-base gets updated now or in a week.  But take this as an opportunity to learn the basics.  I suggest you play with github.dev, etc and when you feel comfortable, I'll give you more feedback about minor content changes to complete this PR.  How does that sound?

**Comment by Almanzoris** [comment]
Sounds fair. I am going to follow that.

**Comment by prabau** [comment]
@Almanzoris As you can see in https://github.com/orgs/pi-base/discussions, tomorrow 3pm EST we have our monthly zoom meeting.  If you can join, that would be great.  We could do a demo to show how to use github.dev/vscode.

**Comment by Almanzoris** [comment]
Sure! I will try to join and get to follow the demo. Thanks for your dedication.

**Pull request closed without merging**
