### PR TITLE
Add locally finite property

### PR DESCRIPTION
**Pull request by danflapjax**
Adds a property that there is a basis of finite sets.

Beyond the theorems included, I believe [T513](https://topology.pi-base.org/theorems/T000513) and [T290](https://topology.pi-base.org/theorems/T000290) can probably be generalized to requiring just locally finite in their antecedents, but that can be work for a future PR.

### CODE REVIEW

**Comment by prabau** [comment]
So what would be interesting examples of non-finite spaces that are locally finite?

**Comment by prabau** [comment]
T567: https://math.stackexchange.com/questions/342091 cannot really be used as justification, as it was for chains of countable sets with a different conclusion.  But the fact that the union of a chain of finite sets is countable can be shown directly (as no two sets in the chain can have the same size, ...), or quote one of several mathse posts about this.

**Comment by prabau** [comment]
The theorems look good.  Some comments:

T293: it would be easier to just say that each compact subset of $X$ is covered by finitely many finite sets. (better match with the definition of anticompact in pi-base)

T568: An easier reference would be to mention Theorem 1 in https://zbmath.org/1400.39025, which gives the classification of connected door spaces (really same as McCartan but with an easier proof).  From which it follows that the only hyperconnected Alexandrov door spaces have an included point topology (= "particular point topology" in S&S).  Maybe give an explicit description with point $p$ etc...  And these are locally finite as explained ...  Do you think we should add "Included point topology" as an alias for the "particular point topology" spaces?

Definition P94: Should we say "the space has a basis consisting of finite sets"?
For the reference to the paper, can you append the names of the authors to the title?

**Comment by prabau** [comment]
About the spaces:

S5 README: "Equals" -> "Is homeomorphic to" ?

S47: it looks like P30 can be replaced by P146 with exactly the same proof

S49|P24: "The closure of every nonempty open set"

**Comment by danflapjax** [comment]
> T568: An easier reference would be to mention Theorem 1 in https://zbmath.org/1400.39025, which gives the classification of connected door spaces (really same as McCartan but with an easier proof). From which it follows that the only hyperconnected Alexandrov door spaces have an included point topology (= "particular point topology" in S&S).

Do you think I should elaborate on why the other cases are excluded, or is it obvious enough to omit? I also realized that instead of hyperconnected it would be sufficient to say not almost discrete once that is added, which would be a reason to reference McCartan anyways for the categorization of all door spaces rather than just connected ones.

> Do you think we should add "Included point topology" as an alias for the "particular point topology" spaces?

I do think that would be good, since it is a common name.

**Comment by prabau** [comment]
Let me review this now.

**Comment by prabau** [comment]
> > T568: An easier reference would be to mention Theorem 1 in https://zbmath.org/1400.39025, which gives the classification of connected door spaces (really same as McCartan but with an easier proof). From which it follows that the only hyperconnected Alexandrov door spaces have an included point topology (= "particular point topology" in S&S).
> 
> Do you think I should elaborate on why the other cases are excluded, or is it obvious enough to omit? I also realized that instead of hyperconnected it would be sufficient to say not almost discrete once that is added, which would be a reason to reference McCartan anyways for the categorization of all door spaces rather than just connected ones.

Let's revisit this after #821 and #831 get added.

> 
> > Do you think we should add "Included point topology" as an alias for the "particular point topology" spaces?
> 
> I do think that would be good, since it is a common name.

We can also do this separately, with some sample reference.

**Review by prabau — APPROVED** [review]

**Pull request merged**
