### PR TITLE
added new S196 space

### PR DESCRIPTION
**Pull request by StevenClontz**
Example contribution from STDC 2024

### CODE REVIEW

**Comment by prabau** [comment]
Regarding the name, "Quotient of the closed long ray" is not very specific.  On the other hand, "long circle" has appeared multiple times on mathse and https://mathoverflow.net/a/92228 for mo.  It has even been used in the literature, for example of p. 313 of http://www.numdam.org/item/CTGDC_1981__22_3_301_0.pdf.  It seems to me "Long circle" would be a good name for this space.

**Comment by prabau** [comment]
The description in the README: "The quotient of {S39} identifying the compactifying point with the initial point."  Is that even clear what that would mean to someone who sees this for the first time?  Compactification of what?  Nearly all points here are compactifying points of their complement in $X$.  It seems it would be clearer to follow the mathse post and say that we are identifying the two endpoints $0$ and $\omega_1$ of {S39}.

Not a big deal, but the various references are of the form `Answer to "..."`.

P37 (path connected): Use link to more specific justification: `Follows from the fact that {S39|P37}.`

P16 (compact): One could use a similar justification, using `{S39|P16}.

**Comment by StevenClontz** [comment]
> The description in the README: [...]

Problem is that $0$ and $\omega_1$ aren't exactly points of S39, whose point-set is $\omega_1\times[0,1)\cup\\{\infty\\}$. But I think I like referring to the point that compactifies S38 to get S39 as the "final" point, so here we're identifying the inital and final points, making it clear why this is a "circle". Making a commit now.

**Comment by StevenClontz** [comment]
@prabau I believe I've addressed your comments.

**Review by prabau — APPROVED** [review]

**Pull request merged**
