### PR TITLE
Some theorems involving compactly generated

### PR DESCRIPTION
**Pull request by prabau**
Generalized theorem T59, plus new theorems T60 and T69, related to various notions of compactly generated space.

See #230.

### CODE REVIEW

**Review by StevenClontz — APPROVED** [review]

**Comment by StevenClontz** [comment]
Approved, though maybe https://topology.pi-base.org/theorems/T000070 and https://topology.pi-base.org/theorems/T000292 can be consolidated somehow.

**Comment by StevenClontz** [comment]
Actually maybe https://topology.pi-base.org/theorems/T000070 should just be "generated by compact T2 subspaces" implies "T1": Consider a point: its intersection with every (compact T2 =>) T1 subspace is either empty or a point within a T1 space, and thus closed

**Comment by prabau** [comment]
> Approved, though maybe https://topology.pi-base.org/theorems/T000070 and https://topology.pi-base.org/theorems/T000292 can be consolidated somehow.

Yeah, I was wondering about that too.  For the sake of discussion here, call the compactly generated properties CG1 (gen by compact subspaces), CG2, CG3 (gen by compact T2 subspaces).  We have:
- (T292) CG1 + anticompact + T1 ==> discrete
- (T70) CG3 + anticompact ==> discrete

For example, every finite top space is compact, hence CG1, and also anticompact.  In that case, T292 says: a finite T1 space is discrete.  But this cannot be deduced from T70, the only finite CG3 space would be the discrete ones.

In the other direction, can T70 be deduced from T292?  CG3 implies CG1, but does it imply T1?

**Comment by prabau** [comment]
(our messages crossed each other :-)

**Comment by prabau** [comment]
> Actually maybe https://topology.pi-base.org/theorems/T000070 should just be "generated by compact T2 subspaces" implies "T1": Consider a point: its intersection with every (compact T2 =>) T1 subspace is either empty or a point within a T1 space, and thus closed

That's very good.  Do you want to change T70 or I'll do it?

**Comment by prabau** [comment]
I'll give it a try and then you can review.

BTW, what do you think of the last question I was asking in issue #230?

**Comment by prabau** [comment]
Added your suggestion.  All self-contained, but I used wikipedia as a reference, just because we need one.

**Pull request merged**
