### PR TITLE
P21 equivalent definition

### PR DESCRIPTION
**Pull request by prabau**
Add equivalent formulation for P21 (weakly countably compact = limit point compact).  Also, cleanup one redundant trait.

### CODE REVIEW

**Comment by prabau** [comment]
Aside from this PR, what would you think of making "Limit point compact" the primary name?

Several of the first hits in google scholar for "weakly countably compact" are all for the meaning "countably compact in the weak topology" in functional analysis, which is a somewhat different thing. Whereas "limit point compact" (Munkres invention) does not seem to be used for something else?

**Comment by danflapjax** [comment]
Another option would be "Has finite extent". (The source used for [P198](https://topology.pi-base.org/properties/P000198) opted for a $+\omega$ to keep all of their cardinality function outputs infinite for simplicity, but this preference is not universal.)

**Comment by prabau** [comment]
Most (all?) of the sources that deal seriously with cardinal functions for topological spaces make the simplifying assumption of using $+\omega$ or $+\aleph_0$.

But even so, it is not the same as proposed.  For example, S20 (Fort space on countable set = $\omega+1$ = convergent sequence) is limit point compact since compact.  So all its discrete closed subspaces are finite.  But the sup of the size of these subspaces is still infinite, i.e., it still has extent = $\aleph_0$.

**Comment by danflapjax** [comment]
Ah, of course. The use of suprema makes the choice of limiting to infinite cardinals more sensible to me now. Limit point compact being the primary name sounds sensible to me fwiw.

Out of curiosity, do you know if there's a property in pi-Base that's equivalent to every discrete subspace being finite (thinking about countable spead)?

**Review by danflapjax — APPROVED** [review]

**Comment by prabau** [comment]
> Out of curiosity, do you know if there's a property in pi-Base that's equivalent to every discrete subspace being finite (thinking about countable spead)?

Not sure.  One related observation: In every infinite Hausdorff space one can find an infinite discrete subspace.

**Pull request merged**
