### PR TITLE
Dowker's theorem

### PR DESCRIPTION
**Pull request by Moniker1998**
I'm introducing Dowker's theorem that characterizes Dowker spaces.

The corollary is the following theorem which we can add to pi-base.

$T_4$ + countably metacompact => countably paracompact

I don't know if the assumption of $T_4$ can be dropped to normal.

This adresses #345

### CODE REVIEW

**Comment by ccaruvana** [comment]
This PR brings up an issue: it has a theorem number that conflicts with the yet to be merged https://github.com/pi-base/data/pull/343
@StevenClontz @prabau is there a rule of thumb on how to manage this kind of thing?

**Comment by ccaruvana** [comment]
Also, thanks for the contribution @Moniker1998 !

**Comment by prabau** [comment]
> This PR brings up an issue: it has a theorem number that conflicts with the yet to be merged #343 @StevenClontz @prabau is there a rule of thumb on how to manage this kind of thing?

If one of us realizes it by inspection, like you did, we can tell the author of the PR to change the theorem number.  @Moniker1998 can you change the number?  BTW, curious how you did you changes: did you use an external copy of the repo on your computer, or something else?

**Comment by Moniker1998** [comment]
Oh I'm sorry I didn't realize that, I will change it.

> BTW, curious how you did you changes: did you use an external copy of the repo on your computer, or something else?

I've made a fork, and then edited on my copy of pi-base on github.com directly.

**Comment by prabau** [comment]
FYI: Absolutely no problem here (i.e. no need to change anything), but as a matter of procedure for future work, it's preferable to name the "topic branch" with a more descriptive name instead of "stdc-demo", for example "dowker" or any name of your choosing.  That also allows you to have multiple topic branches in parallel.

**Comment by ccaruvana** [comment]
Another quick comment: looking at Dowker's paper, it seems like P13 could be used instead of P7. Since P13 doesn't assume P2, this is a slight weakening of the hypotheses. I'll take a closer look later to make sure P2 isn't being used.

**Comment by Moniker1998** [comment]
You're right, Dowker doesn't assume the Hausdorff axiom in his paper (he even gives an example of a non-Hausdorff normal space). The equivalence of countably paracompact and countably metacompact for normal spaces is theorem 2. This needs updating.

**Comment by Moniker1998** [comment]
Pi-base didn't notify me that this theorem already exists or can be deduced, so I added one more theorem from Dowker's paper namely
> perfectly normal => countably paracompact

**Review by ccaruvana — APPROVED** [review]

**Pull request merged**
