### PR TITLE
regular extremally disconnected implies zero-dimensional

### PR DESCRIPTION
**Pull request by Moniker1998**
I introduce a new theorem that isn't on pi-base and can't be deduced from theorems that are there already.
It's possible that some other theorems will need to be cleaned up

**Edit:**
I mentioned the issue #356 here. From looking at theorems for extremally disconnected spaces, it seems like no other changes are necessary.

### CODE REVIEW

**Comment by prabau** [comment]
Thanks @Moniker1998 for your contribution.  A general comment: we always need a refs section pointing to a reference somewhere (paper or book in MR, or doi, or mathse or mo).  Like Steven likes to say, pi-base is not in the business of reviewing mathematics, but in reflecting peer-reviewed mathematics.

If the proof is pretty short, it's ok to give it here, but it should also be accompanied by a refs section.  Can you see if you can find a reference to this somewhere?

**Comment by Moniker1998** [comment]
Reference could be Engelking's General Topology, theorem 6.2.25 but that one is a bit stronger.

It says that [regular + extremally disconnected => strongly zero-dimensional]

Note on definitions: The empty set, by convention, has dimension -1, hence is not zero-dimensional nor strongly zero-dimensional.
However the definition on pi-base doesn't assume non-empty. So in the above, similarly, I mean simply $\text{dim }X \leq 0$ where $\text{dim}$ is Lebesgue covering dimension.

**Comment by Moniker1998** [comment]
I realized that I can't use the example in Engelking. He uses different dimension from large inductive dimension. His dimension is specifically for Tychonoff spaces and is non-standard. Not all extremally disconnected regular spaces are normal, but all strongly zero-dimensional spaces are normal.

**Comment by prabau** [comment]
A few general comments.

I haven't looked in detail at extremally disconnected (P49) before, but before we start adding a bunch of theorems using that notion, I think we should first revisit the definition.  It it currently defined assuming T2.

As a general principle for pi-base, we have tried to use more general definitions that don't make extra separation axiom assumptions if that makes sense, i.e., if they are not built-in.  (rationale: different papers often vary the assumptions.  By using the more general definition without extra assumptions, we are able to capture more of the literature.  We then have to add separation assumption explicitly in some theorems, which is not bad, and also indicates which result make use of the extra assumptions.  And often we get interesting mathematics even without the extra assumptions).

In addition, if possible, we try to use the definitions from Willard (who usually makes very few extra assumptions).  In this case, Willard defines ext. disc. in 15G without any separation assumptions.

So I would like to remove the T2 assumption from P49.  As far as I can tell, that should not invalidate any of the existing related theorems or the proposed theorem here.  @StevenClontz , @ccaruvana are you ok with this?

---
As for the strongly zero dimensional def you are proposing from Charalambous, does that make any separation assumptions?  If not, that would be good.

Regardless of that, let's not introduce so many new unrelated defs in the same PR.  I think it's great to add "strongly zero dim" to pi-base, but how about you do it in a different topic branch, together with basic results connecting that notion with others like zero dim, etc.  Alternatively, remove strongly zero dim from here and we can do it in a later PR.

Q: for your proposed thm, does [extr. disconnected + regular ==> strongly zero dim] or not?

**Comment by prabau** [comment]
@StevenClontz it seems that @Moniker1998 is using a branch from his own repo, which does not allow to preview the results easily.  I imagine that's a necessary limitation at this point?   Also, do you know if we can collaborate by adding commits directly into his branch?

**Comment by Moniker1998** [comment]
> As for the strongly zero dimensional def you are proposing from Charalambous, does that make any separation assumptions? If not, that would be good.
No, Charalambous doesn't make any separation assumptions. 

> Q: for your proposed thm, does [extr. disconnected + regular ==> strongly zero dim] or not?
No it doesn't. All zero-dimensional spaces are normal, but extremally disconnected regular space need not be normal.

The theorem in Engelking is for different closely related notion of zero dimensional space, namely $\text{Ind_0 }X = 0$ in terminology of Charalambous. This is something used when studying dimension of Tychonoff spaces.

**Comment by prabau** [comment]
> All zero-dimensional spaces are normal

That does not seem to be the case.  As mentioned in pi-base, the Sorgenfrey plane is not normal, but is zero dimensional (as product of two zero dim spaces).

**Comment by Moniker1998** [comment]
That was a typo

**Comment by prabau** [comment]
For the future, I think it would be pretty interesting to add to pi-base various closely related notions of zero dimensional and their interrelationships and examples and counterexamples.  But please, I am not suggesting to do this right now :-)  Let's finish the basics of what we have step by step first.  (For example you proposed a whole bunch of things for realcompact, and it will take a while to get these in.  I personally also have a whole backlog of things I'd like to add, but holding off on.)

**Comment by Moniker1998** [comment]
I've double checked, and to be precise, it seems like the definition in Engelking isn't the same as $\text{Ind}_0\ X = 0$, rather, the lemma 13.3 lists equivalent definitions for $\text{Ind}_0$ for normal spaces. Engelking seems to use one of those equivalent definitions, but it seems to be finite for a larger class of spaces.

**Comment by Moniker1998** [comment]
> For the future, I think it would be pretty interesting to add to pi-base various closely related notions of zero dimensional and their interrelationships and examples and counterexamples. 

I think the other types of zero-dimensional spaces don't matter than the already existing one and the one I'm trying to include.

I've only added the existing property because Engelking confused me, but I don't really want to delete it since I was planning to try and add it in the future in another pull request. See #359 .

**Comment by prabau** [comment]
> I don't really want to delete it

In that case, i'll more comments about this tomorrow.  Hope @StevenClontz can explain how to work collaboratively in that case.

**Comment by Moniker1998** [comment]
It's not a large pull request and that one already has a reference. It's the theorem I need a reference for, the sad thing is that almost no author discusses extremely disconnected spaces except for e.g. Engelking. 
But since Engelking uses a non-standard definition of strongly zero-dimensional space I can't use it. Worst case scenario we can ask a question on math.se just for referencing purposes.
I'll wait for @StevenClontz to decide how to handle this.

**Comment by prabau** [comment]
@Moniker1998 We don't want to "delete it all" like you said.  Your contributions are very valuable and we want to move forward with it as efficiently as possible.

Are you familiar with the notion of "topic branch" and why they are beneficial?

**Comment by Moniker1998** [comment]
Topic branch? Is it some github thing?

**Comment by prabau** [comment]
Hmm, it's more a general git workflow kind of thing.  In general, we don't want to do our work on our "main" branch.  Instead we keep a main branch, more or less up to date with the official pi-base main branch, and then when we want to work on something, we create a separate branch off of main and do our work for topic A on that so called "topic branch", say with a name of "topicA" for example.  Then when we are satisfied with the result, the topicA branch gets merged into the official main.  (and then later the official main gets merged into your private main).

But the advantage of this is things are kept isolated while you work on it.  So while topicA is being worked on, say you want to do something about a topic B.  Then you branch off "topicB" off of your main, and then work independently work on both in parallel.  The main advantage is that if topicA is held up for some reason, we can still move forward and release topicB in the mean time.  It's a lot easier to manage overall.

Does that make sense?  Is that something you encountered when you did some initial reading about git workflows?

**Comment by prabau** [comment]
A google search for "git topic branch" returns a lot of hits.  For example:
https://stackoverflow.com/questions/284514/what-is-a-git-topic-branch
https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
https://alvinalexander.com/git/git-topic-branch-workflow-pattern-pro-git/

**Comment by Moniker1998** [comment]
Oh I did have something like that but I didn't really see use in that and it allowed me to use main anyway.

**Comment by prabau** [comment]
Well, github allows you to use main like you said, but if you are going to be a regular contributor, you follow the recommended practice.  Otherwise we get into tangled messes like what we have now (admittedly on a very small scale here, but we are trying to illustrate the best way to do things since you have not used much git before) where two independent thing cannot be released independently.  Even though from your point of view it works anyway, it makes the work of reviewers and the overall process more difficult than it needs to be.
It's no big deal in this particular case, but you should learn to follow that.  It's a good thing to learn about best practices now, instead of later when you get into a real big mess with lots of changes, and then the changes would have to be blocked.  We don't want to do that.

Another reason to use topic branch is that there is also a way to allow previews of one's work in the pi-base web interface.  And for that topic branches are required.  More on that later maybe.  So bottom line, please do not do your work in a main branch.

Also note that branches are very cheap, they are very easy to create and delete in git.

Thoughts?

**Comment by prabau** [comment]
Apologies, I have to step our for a bit.  Will be back later.

**Comment by prabau** [comment]
I'm back.  Let me try to add a commit to your repo, if it allows me, to illustrate something.

**Comment by prabau** [comment]
Well, it does not allow me to commit anything.  I'll add my comment for T393 as a review comment.

**Comment by prabau** [comment]
OK, added a ref for T393, plus minor grammar fix.  See the list of commits.

Your proof was straightforward, so all we needed was a ref, which we now have.  T393 is now ready to go (but P165 is not).

How about you do the following: make a backup of the P165 file.  Then do a commit to remove it from this branch (= your main branch).  Then I'll approve this and we'll be done with that theorem and the corresponding issue.

Then sync you topic branch with official main, etc.  When everything is ok, practice creating a topic branch to add P165 again and we'll take it from there.

How does that sound?

**Comment by Moniker1998** [comment]
I'm surprised you found any references for this! Sure I'll back up this file

**Review by prabau — APPROVED** [review]

**Comment by prabau** [comment]
Hmm, seems I messed up something.  See the Actions tab at the top.

Let me fix it.

**Comment by prabau** [comment]
@Moniker1998 I tried to revert and reapply, but it seems I am not allowed to without creating a new PR.  So created a separate PR which fixes the problem.

In the mean time, if you are curious about the final result, you can go to https://topology.pi-base.org/dev, enter "prabau-patch-1" in the Branch box, and click Refresh.  Then you can examine the theorems as usual and you'll see T393 in there.

**Comment by StevenClontz** [comment]
Sorry I missed this conversation last weekend!

There are a number of ways to handle this; I'll make a note for our next meeting to work out and present a workflow. https://github.com/orgs/pi-base/discussions/364

**Pull request merged**
