### PR TITLE
Two Hemicompact but not Weakly Locally Compact examples

### PR DESCRIPTION
**Pull request by StevenClontz**
See discussion at https://math.stackexchange.com/questions/4566624/can-a-hemicompact-space-fail-to-be-weakly-locally-compact

### CODE REVIEW

**Comment by StevenClontz** [comment]
Apologies for the messy Git diff; I was working off a stale copy of master.

**Comment by prabau** [comment]
Very nice to add this.  I'll review in detail tonight.  But doesn't the word "compactum" mean something else in general (https://encyclopediaofmath.org/wiki/Compactum or https://ncatlab.org/nlab/show/compactum)? Maybe the property should be called "finite compact subsets"?

**Comment by StevenClontz** [comment]
Depends who you ask I suppose; in my circles I've heard "compacta" used for arbitrary compact (sometimes Hausdorff compact) spaces or subspaces. https://en.wikipedia.org/wiki/Compact_space#Open_cover_definition

Maybe "Compact subsets are finite"? It's a mouthful but very clear; I'm not aware of this property being named anywhere.

**Comment by prabau** [comment]
> Maybe "Compact subsets are finite"? It's a mouthful but very clear;

Sounds good to me. It's very clear, and not too long.

**Review by prabau — APPROVED** [review]
One typo, looks good otherwise.

**Comment by prabau** [comment]
Hmm, seems the result for T291 did not format right. Double backslashes should be single ones and an "and:" was missing.

**Pull request merged**
