### PR TITLE
add detail on T205

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
Searches to satisfy:

- [x] https://topology.pi-base.org/spaces?q=Pseudoradial%2B~Radial
- [ ] https://topology.pi-base.org/spaces?q=Pseudoradial%2B~Sequential
- [ ] https://topology.pi-base.org/spaces?q=Radial%2B~Fr%C3%A9chet%20Urysohn

**Comment by prabau** [comment]
Regarding S36 ($\omega_1+1$), it's fine to assert that P163 (card. at most continuum).  Do you think it might be worth adding "card. = $\omega_1$" as a pi-base property at some point?

**Comment by prabau** [comment]
Added T216: LOTS ==> radial.  I could not find a reference with a fully spelt out proof, but it's simple enough, so I picked the article that introduced radial spaces, which mentions the result.  Please see how it looks.

That allows to automatically deduce that $\omega_1+1$ is radial.

**Comment by prabau** [comment]
Some comments about T210 and T211 (countable + radial ==> Frechet-Urysohn).  It could be more subtle than it looks, as it's not true that "every transfinite sequence is a countable sequence", due to repetitions.  I think the following would do it, but maybe you have a shorter argument.

So assume there is a point $p\in\overline A\setminus A$ and a transfinite sequence $(x_\alpha)_{\alpha<\lambda}$ in $A$ that converges to $p$.  We have to show that there is an ordinary sequence that converges to $p$.  Wlog we can assume that $\lambda$ is infinite and of smallest cardinality possible, so in particular it's a regular cardinal.

If one of the $x_\alpha=a\in A$ is repeated cofinally many times, then extracting the subsequence of all the elements with value $a$ gives a constant (transfinite) sequence that converges to $p$.  Then every nbhd of $p$ contains $a$ and the ordinary sequence $(y_n)_{n<\omega}$ with each $y_n=a$ also converges to $p$.

Otherwise, for each $a\in A$ the set of indices $I_a=\\{\alpha<\lambda: x_\alpha = a\\}$ is not cofinal in $\lambda$, that is, $I_a$ has cardinality smaller than $\lambda$.  But there are only countably many values $a\in A$.  So we get a partition of $\lambda$ into countably many sets, each of cardinality smaller than $\lambda$.  If $\lambda$ were uncountable, that would contradict the fact that $\lambda$ is a regular cardinal.  So necessarily $\lambda=\omega$ and our original sequence was an ordinary sequence.

Note: The same argument works if we replace countable with locally countable.

**Comment by StevenClontz** [comment]
> Regarding S36 (ω1+1), it's fine to assert that P163 (card. at most continuum). Do you think it might be worth adding "card. = ω1" as a pi-base property at some point?

Yes, along with a theorem `card = omega_1 => card <= mathfrak c`.

**Comment by StevenClontz** [comment]
> Some comments about T210 and T211 (countable + radial ==> Frechet-Urysohn). It could be more subtle than it looks, as it's not true that "every transfinite sequence is a countable sequence", due to repetitions. I think the following would do it, but maybe you have a shorter argument.
> 
> So assume there is a point p∈A―∖A and a transfinite sequence (xα)α<λ in A that converges to p. We have to show that there is an ordinary sequence that converges to p. Wlog we can assume that λ is infinite and of smallest cardinality possible, so in particular it's a regular cardinal.
> 
> If one of the xα=a∈A is repeated cofinally many times, then extracting the subsequence of all the elements with value a gives a constant (transfinite) sequence that converges to p. Then every nbhd of p contains a and the ordinary sequence (yn)n<ω with each yn=a also converges to p.
> 
> Otherwise, for each a∈A the set of indices Ia={α<λ:xα=a} is not cofinal in λ, that is, Ia has cardinality smaller than λ. But there are only countably many values a∈A. So we get a partition of λ into countably many sets, each of cardinality smaller than λ. If λ were uncountable, that would contradict the fact that λ is a regular cardinal. So necessarily λ=ω and our original sequence was an ordinary sequence.
> 
> Note: The same argument works if we replace countable with locally countable.

I like replacing countable with locally countable.

I think my hand-waving should be recoverable, but since it's not obvious to me how to do it at the moment, I'll incorporate your arguments into an update.

**Comment by StevenClontz** [comment]
Actually let me know if you'll let me get away with b75ef7dd5faabd938abdf20def03ea032ee469d1

**Comment by prabau** [comment]
> Actually let me know if you'll let me get away with [b75ef7d](https://github.com/pi-base/data/commit/b75ef7dd5faabd938abdf20def03ea032ee469d1)

Hmm, I don't think that really works.  Can you ask a general question on mathse and I'll answer it, and then we can make reference to that?  Maybe something along the following lines: Suppose $X$ is a countable topological space and $A\subseteq X$. Suppose a point $p\in X$ that is the limit of a transfinite sequence $(x_\alpha)_{\alpha<\lambda}$ of points of $A$, where $\lambda$ blah blah ... blah blah. Is there an ordinary sequence of points of $A$ that also converges to $p$?

**Comment by StevenClontz** [comment]
Yeah, given there's been this much discussion, airing out on math.SE feels correct: https://math.stackexchange.com/questions/4785088/

**Comment by prabau** [comment]
I updated the list of searches above.

The last one: ample of space that is both radial and sequential, but not Frechet-Urysohn may not be easy to find.  The Encyclopedia of General Topology chapter mentions that [compact + radial + sequential ==> Frechet-Urysohn] without giving any reference.  We'll have to find more about it.  But that seems to imply that without compact there could be counterexamples.

**Comment by StevenClontz** [comment]
I added the MathSE reference at [4679c8d](https://github.com/pi-base/data/pull/452/commits/4679c8d484b12bc8a4ca43737897727390bd7832) but note that I did keep the claim that transfinite sequences contain countable subsequences, as I think that's still correct: take the tail end of the sequence in the countable neighborhood, then either it has countable cofinality and use any countable subsequence, or it must be eventually constant and use a constant sequence.

**Comment by StevenClontz** [comment]
I suggest adding `compact + radial + sequential ==> Frechet-Urysohn` and a (presumed) counterexample to `radial + sequential ==> Frechet-Urysohn` in a future PR.

**Comment by prabau** [comment]
> I added the MathSE reference at [4679c8d](https://github.com/pi-base/data/pull/452/commits/4679c8d484b12bc8a4ca43737897727390bd7832) but note that I did keep the claim that transfinite sequences contain countable subsequences, as I think that's still correct: take the tail end of the sequence in the countable neighborhood, then either it has countable cofinality and use any countable subsequence, or it must be eventually constant and use a constant sequence.

It's good you added the reference.

But I think the current text: `By {P93}, every converging transfinite sequence contains a converging countable subsequence.` needs to be changed.

What I am objecting to is the language in terms of subsequence.  Writing _sequence_ for"transfinite sequence" here, to me the notion of _subsequence_  means a "cofinal subsequence".  That is we have a sequence indexed by some limit ordinal $I=\lambda$, and then we pick of cofinal subset of the ordinal (i.e., pick an index set $J\subseteq I$, but $J$ itself has the order type of some ordinal $\mu\ge \mathrm{cof} \lambda$) and that gives our subsequence.  But if $J$ is not cofinal in $I$, that does not qualify as a subsequence.  So now going back to the theorem, if we have a transfinite sequence indexed by an uncountable regular cardinal $\lambda$ for example, there is no such thing as a "countable subsequence" of it, as $\lambda$ has no countable cofinal subset.

Now I know what it's trying to say.  But in your comment above: `or it must be eventually constant and use a constant sequence`, that constant (ordinary) sequence is what we want, but is not a "subsequence" of the original transfinite sequence (so the current text of the theorem is not valid for that case).  Also it's not the case that the original sequence needs to be eventually constant.

We could still say something along the lines of your comment above.  How about the following maybe?

Given a transfinite sequence with values in a set $A$ and converging to a point $p\in X$, first replace it by a tail end belonging to a countable neighborhood of $p$ by {P93}.  Then if the sequence has countable cofinality, extract a countable subsequence converging to $p$.  Otherwise, some value in the sequence repeats cofinally, which implies that value belongs to all neighborhoods of $p$. In this case, $p$ is the limit of an (ordinary) constant sequence with that value.  In both cases we get a countable sequence in $A$ that converges to $p$.  See {{mathse:4785088}} for details.

**Comment by prabau** [comment]
Actually, we could shorten this quite a bit, as long as we don't use the word "subsequence".  Like the following for example:

Given a transfinite sequence with values in a set $A$ and converging to a point $p\in X$, first replace it by a tail end belonging to a countable neighborhood of $p$ by {P93}. So we can assume without loss of generality that $A$ is countable.  Then, as explained in {{mathse:4785088}}, there exists a countable sequence of points of $A$ converging to $p$.

**Comment by StevenClontz** [comment]
I like your suggestion for wording. (Of course, I meant to imply that a subsequence can be any restriction of the domain of the transfinite sequence, but this does not preserve limits, so I understand the disagreement.)

**Review by prabau — APPROVED** [review]

**Pull request merged**
