### PR TITLE
Add GO-space + Locally Connected => Weakly Locally compact

### PR DESCRIPTION
**Pull request by Jianing-Song**
Per issue #727 . I also removed two redundant files S38/P23 and S62/P41 (note that the latter one is already redundant even without the newly-proposed theorem).

### CODE REVIEW

**Comment by prabau** [comment]
The comment I added for #741 basically gives a more detailed proof for the proposed T203.

Can you compare with your suggested proof and see if it's really the same thing, or if either one is missing something?

**Comment by prabau** [comment]
I am thinking the most instructive would be to have a question on mathse asking some general thing, not specific to this theorem or to pi-base.  And then we can just refer to that here.

Namely, in a LOTS and more generally in a GO-space, what do connected subsets look like?  What do connected components (maximal connected subsets) look like?  The answer would explain what's going on, relation with locally compact, cases of connected component has a min/max, does not have a min/max, examples, possible cardinalities, etc.  Anything you think could be interesting for this topic.

Let me know if you would like me to ask the question on mathse.  I'll let other people answer.

**Comment by Jianing-Song** [comment]
> This is a good result. Allows to derive that 5 more spaces are not GO-spaces.
> 
> As for the supporting text, the terminology "linear continuum" for a certain kind of ordered set is not used widely in topological books or papers. I could be mistaken, but I have only seen it in Munkres, and from there people copied it to several wikipedia articles (but always quoting Munkres). I am curious, have you seen this used in other sources? Anyway, I don't think it should be a problem. The wikipedia article is a good summary: linear continuum = least upper bound property + order-dense.
> 
> Now, what is "order-complete"?
> 
> I am not sure if the proposed proof is ok or if it's taking some non-obvious shortcuts. Just to convince myself, I'll think about it some more and add some comment below.

The name "linear continnum" what also what I learned in my own topology class, so I have a particular clear memory on it. Of course, this is just because my teacher followed Munkres.

"Order-complete" means exactly the least upper bound property, and I believe having seen this term several times on Math SE, but changing it to something else is completely OK for me.

**Comment by prabau** [comment]
> Yes, I would be very glad to see the question. Thanks!

Ok.  I will ask something by the end of the day.

**Comment by Jianing-Song** [comment]
> A _complete lattice_ is one in which every subset has a least upper bound (which implies also that every subset has a greatest lower bound). The same definition applies to a totally ordered set (which are lattices). That would seem to be what "order-complete" could mean. In particular, it implies that the set has a minimum element and a maximum element. So it's stronger than the "least upper bound property", which is also called Dedekind-complete (in Willard).

I believe having heard that $\mathbb{R}$ is order-complete. But as said, let's discard this term and change for "least upper bound property"?

(If you don't like "linear continnum" either, I will make another PR to change that because multiple files are involved.)

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces
and also
https://math.stackexchange.com/questions/4968515/cardinality-of-connected-lots

**Comment by prabau** [comment]
> Do you think of also discarding this one, or shall we keep it and just change the content to "See Math SE 4968515"?

I think this proposed theorem is very good to have.  It adds a non-trivial implication.  And it allows to derive that 5 more spaces are not GO-spaces, including Hilbert space:
https://topology.pi-base.org/spaces?q=%3FGO-space%2BLocally+connected%2B%7Ewlc

For the justification, I think we can just refer to both mathse posts.  But we first need an answer for
https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces
I think that's the important thing for understanding why the sentence you wrote is true:

> "By [(GO-space ∧ Connected) ⇒ LOTS](https://topology.pi-base.org/theorems/T131), the open neighborhood is a linear continuum (i.e., a [Connected](https://topology.pi-base.org/properties/P36) [LOTS](https://topology.pi-base.org/properties/P133)) with respect to the order in the definition of GO-space."

(In particular, it is not a priori completely clear why we can use the theorem that if the full space is a connected GO-space it has to be a LOTS, and conclude from that a similar thing for just a subset of the full space.)

I'll add an answer to that mathse question and then you'll tell me if it makes sense.

**Comment by Jianing-Song** [comment]
> > Do you think of also discarding this one, or shall we keep it and just change the content to "See Math SE 4968515"?
> 
> I think this proposed theorem is very good to have. It adds a non-trivial implication. And it allows to derive that 5 more spaces are not GO-spaces, including Hilbert space: https://topology.pi-base.org/spaces?q=%3FGO-space%2BLocally+connected%2B%7Ewlc
> 
> For the justification, I think we can just refer to both mathse posts. But we first need an answer for https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces I think that's the important thing for understanding why the sentence you wrote is true:
> 
> > "By [(GO-space ∧ Connected) ⇒ LOTS](https://topology.pi-base.org/theorems/T131), the open neighborhood is a linear continuum (i.e., a [Connected](https://topology.pi-base.org/properties/P36) [LOTS](https://topology.pi-base.org/properties/P133)) with respect to the order in the definition of GO-space."
> 
> (In particular, it is not a priori completely clear why we can use the theorem that if the full space is a connected GO-space it has to be a LOTS, and conclude from that a similar thing for just a subset of the full space.)
> 
> I'll add an answer to that mathse question and then you'll tell me if it makes sense.

Well I was thinking that a subspace of a GO-space is again a subspace. This was perhaps because I was more familiar with the "subspace of a LOTS" definition, so hereditary property was clear.

By the way, while I was looking forward to your answer to [https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces], I was somehow thinking that pointing to [https://math.stackexchange.com/questions/4968515/cardinality-of-connected-lots] is sufficient. I would like to write something like (and we can discuss the way to formulate):

A subspace of a GO-space is again a GO-space by definition, thus a connected base element of a GO-space is a LOTS by T131, and by [https://math.stackexchange.com/questions/4968515/cardinality-of-connected-lots] this base element is weakly locally compact.

**Comment by prabau** [comment]
> A subspace of a GO-space is again a GO-space by definition, thus a connected base element of a GO-space is a LOTS by T131, and by https://math.stackexchange.com/questions/4968515/cardinality-of-connected-lots this base element is weakly locally compact.

This is really good and simple.  Let me see if I understand this fully.  

Given a locally connected GO-space $X$, there is a base for the topology consisting of connected open sets.  Each of these open sets $U$ is itself a GO-space (as a subspace of a GO-space), hence is a LOTS by T131.  Mathse 4968515 shows that a connected LOTS is weakly locally compact.  So $U$ is weakly locally compact and the same holds for $X$.

I have posted an answer to https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces which also proves the result with more details about the order relation.  But your proof is a lot simpler.  That's all we need here.  For information, maybe we could add "See also mathse 4968678".

**Comment by prabau** [comment]
As an aside: "Dedekind complete" seems to be used in the literature for ordered sets.  But practically no one uses "linear continuum".  Compare:
https://zbmath.org/?q=%22Dedekind+complete%22+cc%3A06
https://zbmath.org/?q=%22linear+continuum%22+cc%3A06

**Comment by Jianing-Song** [comment]
> > A subspace of a GO-space is again a GO-space by definition, thus a connected base element of a GO-space is a LOTS by T131, and by https://math.stackexchange.com/questions/4968515/cardinality-of-connected-lots this base element is weakly locally compact.
> 
> This is really good and simple. Let me see if I understand this fully.
> 
> Given a locally connected GO-space X , there is a base for the topology consisting of connected open sets. Each of these open sets U is itself a GO-space (as a subspace of a GO-space), hence is a LOTS by T131. Mathse 4968515 shows that a connected LOTS is weakly locally compact. So U is weakly locally compact and the same holds for X .
> 
> I have posted an answer to https://math.stackexchange.com/questions/4968678/connected-sets-in-go-spaces which also proves the result with more details about the order relation. But your proof is a lot simpler. That's all we need here. For information, maybe we could add "See also mathse 4968678".

I like what you wrote which makes everything more clear. I've replaced the content with this one.

**Review by prabau — APPROVED** [review]

**Pull request merged**
