### PR TITLE
Adding fixed point property implies T0, plus giving property values to many more spaces

### PR DESCRIPTION
**Pull request by danflapjax**
I was already working on contributions relating to [P89 fixed point property](https://topology.pi-base.org/properties/P000089) before seeing PR #558, so I decided to wrap up some work and submit a supplementary PR of my own. I added two theorems: T446 saying fpp => nonempty and T447 saying fpp => T0. I also added property values for 20 other spaces either directly for the fixed point property or for properties allowing a deduction of the fixed point property.

### CODE REVIEW

**Comment by marswill** [comment]
oops I also added 446 saying exact same thing per @prabau's suggestion.  I guess one of us should remove it lest there be merge conflict?

**Comment by prabau** [comment]
@marswill yours is ready to go.  So let's go with that one first.

**Comment by prabau** [comment]
@danflapjax Thanks for this.  I like T447.
@marswill Would be like to review this?

**Comment by prabau** [comment]
Also curious, what would be an example of a space with ffp that is not T1?

**Comment by marswill** [comment]
> @danflapjax Thanks for this. I like T447. @marswill Would be like to review this?

I'd like to, one question though, is there any way to preview it?  not sure how to do that when its not a branch in the public repo.

> Also curious, what would be an example of a space with ffp that is not T1?

I think Sierpinski space cannot transpose the elements, right?  So must have fpp?

**Comment by danflapjax** [comment]
@prabau All of the included and excluded point spaces have fpp, but are not T1

**Comment by prabau** [comment]
Makes sense for Sierpinski space.

There is unfortunately no direct way to preview things from a private repo, even for the author himself, as far as I know.  But one can clone the repo to a branch on the public repo.  Let me find the info.

**Comment by prabau** [comment]
@marswill See https://github.com/pi-base/data/wiki/Reviewing

**Comment by marswill** [comment]
@danflapjax  There seems to be a problem building, it's hard to say exactly where but from the error message in the detail I see 
> error can not read an implicit mapping pair; a colon is missed at line 6, column 64:
>    ... ce with the fixed-point property

searching for "ce with the fixed point property" makes me think it might be something wrong with this file?

https://github.com/pi-base/data/pull/559/files#diff-5f12c5bff8f5e64817867fcc1ec800e6544861c8c97a791aa0a6f63a0219a3c1

Though I can't figure out what's wrong from just looking.  @prabau have you encountered difficulties like this?  Anything obviously amiss?

**Comment by danflapjax** [comment]
Looks like I forgot the `name:` part of the references; it should be fixed now.

**Comment by marswill** [comment]
Looks like we also have this problem with the entry for space S32, you have it in the file as S18

> path does not match space=S000018 and property=P000089

**Comment by marswill** [comment]
I'm noticing unformatted tex in S86's proof.  On that note, github.dev lets you preview individual markdown files, which can help catch that stuff - I didn't know about this myself until I was told the other day, its really handy.

**Comment by marswill** [comment]
Can we change T447 to just directly say Fpp +> T0?  I think in general we like to avoid stating theorems as contrapositives.

**Comment by marswill** [comment]
> I'm noticing unformatted tex in S86's proof. 

> Can we change T447 to just directly say Fpp +> T0? I think in general we like to avoid stating theorems as contrapositives.

@danflapjax  Other than these two things I think everything is in order, proofs all look good.  As soon as you get a chance to fix them I'll go ahead and double check it all works then merge.  Thanks for this considerable contribution!

**Comment by prabau** [comment]
For S32 (Hilbert cube): I guess it should be clear, but just to confirm:

We need to have the space embedded in some TVS, and in that case, we can choose the TVS to be $\mathbb R^\omega$ with the product topology. (It's homeomorphic to the Hilbert space $\mathscr l_2$, but I think that's non trivial.  I don't think I have seen a proof of it.)  In any case, $\mathbb R^\omega$ contains $[0,1]^\omega$ as a compact subspace.  So we can apply the Schauder fixed-point theorem.

**Comment by marswill** [comment]
> Unless you think it's completely obvious, maybe you should mention the TVS in question.

When I was looking at it I thought it was clear enough, but now that I think on it I agree it doesn't hurt to err on the side of being explicit about these kinds of things, just to keep the site as accessible as possible to students and such.

**Comment by danflapjax** [comment]
Thanks for the comments! I think everything should be good now.

**Comment by prabau** [comment]
Hmm, isn't linking to S30 confusing here?  It's easy that $\mathbb R$ is a topological vector space.  It's  not at all clear that it's the same as S30.

**Comment by danflapjax** [comment]
> Hmm, isn't linking to S30 confusing here? It's easy that $\mathbb{R}^\omega$ is a topological vector space. It's not at all clear that it's the same as S30.

Given that S30 says "This space is homeomorphic to $\mathbb{R}^\omega$ with the product topology" it seems to me that a link only improves connectivity and discoverability within the database. I can easily revert the change, however.

**Comment by marswill** [comment]
@prabau we assert that they are equivalent in the description of S30. If  Steen/Seebach (the reference for S30) asserts they are homeomorphic then I think that's fine.  If they don't assert that, but it's still true (too tired to think off top of my head), then I think we approve this PR as is and just fix the reference in S30.

Can you check Steen/Seebach if you have it on you?

**Comment by marswill** [comment]
Wait a sec, this is nonsense, $\mathbb R^\omega$ is $\sigma$-compact, right? whereas Hilbert space is not.

**Comment by prabau** [comment]
S&S mention that the two spaces are homeomorphic without giving any proof.  In the footnotes at the back, they mention it's a result of Anderson from 1966, and that Anderson and Bing gave an elementary but lengthy proof of the result in 1968.  It does not seem to be anything obvious. 
So maybe it's fine the way it is.

**Comment by prabau** [comment]
I am not sure $\mathbb R^\omega$ (with the product topology) is $\sigma$-compact.

**Comment by marswill** [comment]
> I am not sure Rω (with the product topology) is σ-compact.

It's not, tried to correct that bit of silliness on my part before anyone saw it, too late :)

**Comment by prabau** [comment]
FYI, $\mathbb R^\omega$ is called "Frechet space" (jspace 37) and not Hilbert space in S&S.

**Review by marswill — APPROVED** [review]
Thanks once again for the contribution, looks good!

**Comment by prabau** [comment]
@marswill For my own sake as a reviewer, how did you repeatedly update the preview branch to pick up the various added commits? I don't remember if there was an easy way to do that?

**Comment by marswill** [comment]
@prabau I actually just deleted the preview branch and remade it several times.  

While deleting the branch made sense when it became obsolete after updates, I probably should have labeled the branches differently each time, e.g., preview-pr-599-2, preview-pr-599-3, etc, to avoid confusion.  I hadn't realized you were also looking at it until later on, so I was thinking this was just a throwaway thing for me to look at.  

But as I'm describing what I did I'm realizing it's got to be terrible practice regardless to do things that way, particularly in a public repository, and will not do that again, and be sure to label new branches differently.

**Comment by prabau** [comment]
@marswill When I had done it before, I was doing the same thing, deleting the preview branch and recreating it.  Was just curious if there was an easier way.  As far as labeling the branches differently each time, I don't thing that's necessary at all as they are throwaway branches for reviewing purposes anyway.  And there is no confusion.  When reviewing, we want to see the latest one reflecting the latest commits.  So that's all fine.   No need for overkill.

**Comment by prabau** [comment]
> Given that S30 says "This space is homeomorphic to ... with the product topology" it seems to me that a link only improves connectivity and discoverability within the database. 

@danflapjax Thinking about it some more, I think you are right.  That makes perfect sense regarding connectivity/discoverability.  Even if the homeomorphism is not immediately obvious, pi-base only tracks spaces up to homeomorphism, so there will be cases where different incarnations of a space refer to the same pi-base page.

**Pull request merged**
