### PR TITLE
Quasi-sober property.

### PR DESCRIPTION
**Pull request by Almanzoris**
Theorem 511: $T_1$ $+$ Hyperconnected $+$ Has multiple points $\Rightarrow$ $\neg$ Sober.

I was reading about Sober spaces and read that there are $T_1$ spaces that aren't Sober and Sober spaces that aren't $T_1$. I tried to search in Pi-Base but found no examples.

I read that the cofinite topology on an infinite set isn't sober and, while proving it, I noticed that instead of adding the property to that space, it could be added as a theorem.

Note: I've also read that Hyperconnected spaces are also called Irreducible. Should it be added as an alias?

### CODE REVIEW

**Comment by Almanzoris** [comment]
For the pending examples of spaces that are Sober but not $T_1$, we could add that the spaces 7 - 10 (inclusive) are Sober.

If $p$ is the particular point, then $X \setminus \\{p\\}$ is discrete. So the only non empty irreducible closed subsets that don't have $p$ are the points distinct to $p$. And the only closed set that has $p$ is $X$, which is also irreducible and $X = \overline{\\{p\\}}$.

**Comment by prabau** [comment]
Pi-base does not have many results about Sober and that could definitely be improved.  I agree that it would be good to add "Irreducible" as an alias for Hyperconnected.

A few suggestions about the page for Sober (S73).  We should clarify things by spelling out at the end of the first paragraph what is meant by an irreducible set.  I can't comment on the second paragraph as I don't know about locales; I am sure it is interesting, but if it is not directly about general topology and does not help directly in proving results for pi-base, does it need to be there?   As for the refs, we could put the Wikipedia first, as it seems a good start for that concept and accessible. (I have not looked at Vickers' book.)

One accessible reference that also seems very good is the corresponding section from the Stacks project.  We could mention it directly in the text, maybe something like:
`See also the section on [Irreducible components](https://stacks.math.columbia.edu/tag/004U) from the Stacks project.`

I also think the related concept of "quasi-sober" (see Stack project page above) would be good to have in pi-base, as it illuminates some of the relationships between properties.  For example, as shown in https://math.stackexchange.com/questions/4198805 (answer by Eric Wofsey), all finite spaces are quasi-sober.  From this, it follows that  finite T0 spaces are sober.

As for the proposed T511, I find the explanation a little confusing, but isn't it more generally true that
[hyperconnected + T1 + multiple points ==> not quasi-sober]?  (because: if X is quasi-sober and irreducible (and nonempty), it has a generic point $x$.  But $x$ is a closed point by T1, hence $X=\\{x\\}$ is a singleton.)
Would it be better to state this as
[quasi-sober + T1 + multiple points ==> not hyperconnected] ?

Comments?

**Comment by Almanzoris** [comment]
Yeah, I agree that it would be good to have such property (quasi-sober). [hyperconnected + T1 + multiple points ==> not quasi-sober] is true, I wasn't aware of the concept of quasi-sober. Following your proof, I agree that it is better to state it as [quasi-sober + T1 + multiple points ==> not hyperconnected].

Relative to the second paragraph, we should definitely clarify what's meant by "irreducible set".

**Comment by Almanzoris** [comment]
How should the link [Irreducible components](https://stacks.math.columbia.edu/tag/004U) be included in the references?

**Comment by prabau** [comment]
> How should the link [Irreducible components](https://stacks.math.columbia.edu/tag/004U) be included in the references?

It can't be included in the `refs:` section because there is no doi and it's not a book or paper, hence not in mr or zb either.  But it's enough to have in the text like you did.

**Comment by Almanzoris** [comment]
Yeah, I suspected, thanks for the clarification.

**Comment by prabau** [comment]
Made a few minor tweaks and approving.  If you think anything should be changed, it can be done together with other things later.

**Review by prabau — APPROVED** [review]

**Pull request merged**
