### PR TITLE
Scrub uid's from traits (issue #58), part 1

### PR DESCRIPTION
**Pull request by prabau**
Trying to reduce the backlog of pending issues by tackling #58.  The following command

`grep '^uid: ' S*/properties/*.md | wc -l`

shows there is a total of 1504 files to be cleaned up.  As it seems a bit much to review in a single shot, I am breaking it into more palatable chunks.  The first chunk (323 entries) was generated like this:

`sed -b -i '/^uid: /d' S0000[012]*/properties/*.md`

I'll generate further chunks after each one gets approved.  But please let me know if you have different suggestions.

### CODE REVIEW

**Review by ccaruvana — APPROVED** [review]
Sorry for the delay on this. Based on @StevenClontz most recent comment about removing uids being reasonable, I will approve these.

**Comment by prabau** [comment]
Thanks a lot @ccaruvana for approving this.  I can do another chunk, or if you don't need to inspect everything by line, I can do the whole remaining thing in one shot and you can just sample the changes here and there.

Alternatively, and equally fine by me, maybe @StevenClontz or @jamesdabbs have the superpower to apply the same commands I used (or other ones) directly to the repository without a separate review?

What do you guys prefer?

**Comment by ccaruvana** [comment]
@prabau I'm personally indifferent if it's done in chunks or all done in one go. I just looked over all of the changed files in the pull request and made sure I only saw uid lines being removed. I'm not sure if anyone else has differing opinions.
Thanks for your contribution, @prabau !

**Comment by prabau** [comment]
Thanks @ccaruvana.  I have done another bigger chunk this time.

**Pull request merged**
