### PR TITLE
A topological view of P-spaces by Misra, theorems

### PR DESCRIPTION
**Pull request by Moniker1998**
I've gathered and included theorems from https://www.sciencedirect.com/science/article/pii/0016660X72900268

Note that when Misra says "locally compact" they mean weakly locally compact (or at least that's what they use in their proof).

### CODE REVIEW

**Comment by Moniker1998** [comment]
Some additions that I didn't want to include in this pull request slipped in. Sorry for that.

**Comment by prabau** [comment]
I have cloned this to a branch "pr379" in the repo for ease of review.

**Comment by prabau** [comment]
Again it's missing "doi:", etc.  Do you mind fixing this?

**Comment by prabau** [comment]
You can see the result without "doi:" in the preview by going to https://topology.pi-base.org/dev, etc, as explained before.

**Comment by Moniker1998** [comment]
Yeah sorry for this. It's probably something I'll keep on repeating

**Comment by prabau** [comment]
We don't need T395 and T396, as they can be deduced from T397, T398.

For T398, Prop. 4.1 in the paper refers to Gillman & Jerison.  As I am not too familiar with G & J, where should I be looking in that book?

Prop 4.1(d) in the paper is a result for locally compact.  Is it something that can be deduced from other theorems?  If not, it seems it would be good to have as well.

When referring to the results in the paper, I think it would be good to refer to the specific subitem in the proposition.  E.g., Proposition 4.2(b) instead of just Proposition 4.2, etc

**Comment by prabau** [comment]
Regarding connectivity properties, Prop 5.1 can be stated as [P-space + connected ==> strongly connected].  T401 can then possibly be derived?  Need to try it out.

**Comment by prabau** [comment]
If we could work in the "pr379" branch of the repo directly, it would be easier to test things.  I suspect not, but can you see if you can do an edit directly on that branch?

**Comment by prabau** [comment]
No need for T400, as pi-base already knows that Lindelof + T3 implies paracompact.

**Comment by Moniker1998** [comment]
> Prop 4.1(d) in the paper is a result for locally compact. Is it something that can be deduced from other theorems? If not, it seems it would be good to have as well.

No, I just deleted it on accident. I did have it added.

> For T398, Prop. 4.1 in the paper refers to Gillman & Jerison. As I am not too familiar with G & J, where should I be looking in that book?

See exercise 8A. For pseudocompact spaces $\nu X = \beta X$ where $\nu$ means Hewitt realcompactification. You can deduce that $X$ is a P-space iff $\nu X$ is a P-space. If $X$ is pseudocompact, this becomes $\beta X$.

**Comment by Moniker1998** [comment]
I've added [connected + P-space => strongly connected] but without the $T_1$ assumption (it's not needed)

**Comment by prabau** [comment]
Added a few minor tweaks.  Please check the latest commit.  In particular:

T395: the paper left the (easy) proof to the reader.  So I added and referenced https://math.stackexchange.com/questions/4744652/every-hausdorff-lindel%c3%b6f-p-space-is-normal/4744653#4744653

T399: added the converse

----
In addition:

T396: I think we can get rid of this and replace it by a general theorem [strongly connected + completely Hausdorff ==> totally disconnected].  (then the previous result can be deduced in combination with T400)  The proof is pretty easy, but we should have something to reference.  I can ask on mathse and you can answer there, or vice versa.  Let me know.  This all could be done in a separate PR if you want.

**Comment by prabau** [comment]
For T398 [P-space + T3.5 + pseudocompact ==> finite], I feel that the proof of Prop 4.1(e) is too cryptic.  It relies on unmentioned results in G & J, and for the benefit of users of pi-base it would be good if we could refer to something a little more detailed.  Having something in mathse would be good.  Or even better, I feel that should be a more elementary proof that does not make use of the Stone-Cech compactification or the Hewitt realcompactification.  What do you think?

@StevenClontz fyi

**Comment by prabau** [comment]
I think I found a relatively direct proof for T398 not involving any fancy compactifications or realcompactifications.  Posted this: https://math.stackexchange.com/questions/4744697/is-every-t-3-pseudocompact-p-space-finite
(note that for P-spaces, T3 is equivalent to T3.5, because of T351 [regular + P-space ==> zero dimensional]).

Feel free to give it a go or I'll let other people answer.  If no answer by end of tomorrow, I'll post my solution.

**Comment by Moniker1998** [comment]
@prabau I've included a proof of this using theory of rings continuous functions (which is the intended solution in the paper)

**Comment by Moniker1998** [comment]
> For T398 [P-space + T3.5 + pseudocompact ==> finite], I feel that the proof of Prop 4.1(e) is too cryptic. It relies on unmentioned results in G & J, and for the benefit of users of pi-base it would be good if we could refer to something a little more detailed. Having something in mathse would be good. Or even better, I feel that should be a more elementary proof that does not make use of the Stone-Cech compactification or the Hewitt realcompactification. What do you think?

Sure, if you found a short proof you can include, feel free to do so. While I think referencing the result is enough, including a short proof would probably be even better

**Comment by prabau** [comment]
> I've included a proof of this using theory of rings continuous functions (which is the intended solution in the paper)

I'll take a look.  Seems very interesting.

I have posted my elementary proof in https://math.stackexchange.com/questions/4744697.  Please double check me on this.

**Comment by Moniker1998** [comment]
No, it looks good, very cute (and short) proof. I like it

**Comment by Moniker1998** [comment]
@prabau tell me if this looks good to you

**Comment by prabau** [comment]
Thanks for checking it.  But I think it's missing an important part, namely, $f$ also needs to be defined on the intersection of all the $U_n$ and that intersection needs to be clopen to have continuity.

In any case, when a proof is just one or two lines, it's ok to have it in pi-base.  But if it's longer than that, we usually prefer to just have a reference.  In this case, I think the references are good enough.

To finalize this, could you do the following:
- T398: remove the explicit proof and change the mathse id to reference the whole question instead.
- remove T396 (as discussed 9 comments above).  What do you prefer to do here for the suggested replacement theorem?
- optionally move T400 to the T396 slot

**Comment by Moniker1998** [comment]
> Thanks for checking it. But I think it's missing an important part, namely, f also needs to be defined on the intersection of all the Un and that intersection needs to be clopen to have continuity.

Ah, yes, sorry. I wasn't paying enough attention it seems.

> In any case, when a proof is just one or two lines, it's ok to have it in pi-base. But if it's longer than that, we usually prefer to just have a reference. In this case, I think the references are good enough.

Sure, I'll just add a reference.

> T398: remove the explicit proof and change the mathse id to reference the whole question instead.

Yes, sorry, I didn't realize it's referencing a particular answer instead of the whole question. I'll change that.

> optionally move T400 to the T396 slot

I'll try changing this. In the meanwhile I noticed that T396 has id of theorem 401.

**Comment by Moniker1998** [comment]
> T396: I think we can get rid of this and replace it by a general theorem [strongly connected + completely Hausdorff ==> totally disconnected]. (then the previous result can be deduced in combination with T400) The proof is pretty easy, but we should have something to reference. I can ask on mathse and you can answer there, or vice versa. Let me know. This all could be done in a separate PR if you want.

Can you explain how would that replace T396?

**Comment by prabau** [comment]
Added a final fix.  Now approving.

**Comment by prabau** [comment]
@Moniker1998 @StevenClontz I merged this PR into main.  Then as I was trying to create a completely unrelated branch from main on my computer, I again got spurious differences due to whitespace setting (for theorems T395-T400).  Really annoying.  These files were merged from Moniker's repo.

@Moniker1998: how is your repository set up?  Are you working on your computer or from github or from ...?  And which operating system?  We've had these problems before when something is not set up right somehow.

**Comment by StevenClontz** [comment]
It's a GitHub.dev bug. I should look into it.

In the meantime if possible double-check that new files you create use LF line endings and not CRLF.

**Pull request merged**
