### PR TITLE
New theorem: countable + T1 implies totally path disconnected

### PR DESCRIPTION
**Pull request by prabau**
Also removed some correspondingly redundant trait files:

https://topology.pi-base.org/spaces/S000029/properties/P000046
https://topology.pi-base.org/spaces/S000052/properties/P000046
https://topology.pi-base.org/spaces/S000067/properties/P000046
https://topology.pi-base.org/spaces/S000098/properties/P000046
https://topology.pi-base.org/spaces/S000122/properties/P000046
https://topology.pi-base.org/spaces/S000123/properties/P000046

### CODE REVIEW

**Review by ccaruvana — APPROVED** [review]

**Comment by prabau** [comment]
Hi @ccaruvana Thanks for approving this.  But for some reason it did not get deployed properly (Checks tab says: "Workflow runs completed with no jobs").  Any idea what that means?
@StevenClontz

**Comment by StevenClontz** [comment]
My hotfix at https://github.com/pi-base/data/commit/8fcb5f9676b86cec3bbcabd49d8868c4870694ad seems to fix this. This is part of the redundancy I was talking to @jamesdabbs about the other day: having to edit the UID line to match the filename doesn't provide us necessary infrastructure (I think) but does add some frustration.

**Comment by StevenClontz** [comment]
For posterity: it was https://github.com/pi-base/data/runs/7157914948?check_suite_focus=true#step:3:5 that clued me into the issue.

**Comment by prabau** [comment]
That's my bad.  Thanks @StevenClontz for fixing this.  In retrospect, it should have been clear by looking at https://github.com/pi-base/data/actions that something was wrong.  Did not think of looking there.

**Pull request merged**
